### ISSUE TITLE
ActiveRecord globalid in whodunnit

### ISSUE THREAD

**Issue by attenzione** [airblade/paper_trail#1008]
There is extension for paper_trail, which implements ActiveRecord in whodunnit (https://github.com/ankit1910/paper_trail-globalid)

This repository is completely out of activity.

Maybe you can implement this feature inside paper_trail with option to enable/disable it?

Anyway, thanks for you great work.

**Comment by jaredbeck** [comment]
Hi Sergey, Thanks for the feature request.

According to its readme, the [`paper_trail-globalid`][1] gem will "add one more method actor to instances of PaperTrail::Version that will return you the ActiveRecord object who was responsible for change."

This sounds useful, but not everyone stores an ActiveRecord id (or gid) in the `whodunnit` column. Some people choose to store a name. Would the `actor` method raise an error for them?

> Maybe you can implement this feature inside paper_trail ..

It's not something I'm interested in doing, you'll have to implement it yourself.

Alternatively, you could fork the [`paper_trail-globalid`][1] gem.

> .. with option to enable/disable it?

What, exactly, would be disabled?

> Anyway, thanks for you great work.

You're welcome!

[1]: https://github.com/ankit1910/paper_trail-globalid

**Comment by jaredbeck** [comment]
Hi Sergey, are you still working on this? Do you want me to leave it open?

**Comment by attenzione** [comment]
@jaredbeck you can close it, thank you.
