### ISSUE TITLE
Reify on associations fails when associations were destroyed

### ISSUE THREAD

**Issue by excosy** [airblade/paper_trail#1011]
Situation 1:
Assume contract has_many invoices. When contract is modified, invoices are destroyed and created, by method called make_invoices. And make_invoices destroy old invoices before contract updated. That results to ```invoices.deleted_at < contract.updated_at < invoices.created_at```. While reifying contract, ``` contract.versions.last.reify(has_many: true, mark_for_destruction: true).invoices ``` won't rebuild destroyed invoices, due to their deleted_at < contract.updated_at = versions.created_at.
Is ```created_at > version_at``` at ```lib/paper_trail/reifiers/has_many.rb#104``` in ```load_versions_for_hm_association```
```where("created_at >= ? OR transaction_id = ?", version_at, tx_id)``` necessary?

**Comment by jaredbeck** [comment]
Thanks for the bug report. Per our [contributing guide][1] please use
our [bug report template][2].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by jaredbeck** [comment]
Closed due to insufficient information. Per our [contributing guide][1] please use
our [bug report template][2].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
