### ISSUE TITLE
object_changes contains numeric values serialized as strings and this causes a new Version to be created even if no attribute was changed

### ISSUE THREAD

**Issue by gustavobap** [airblade/paper_trail#1021]
I think this may be a bug, could someone check if this is worthy investigating ? Maybe this is the expected behavior ? Thanks !

I'm using rails 3.2.3 with paper_trail 5.2.3 and postgreSQL 9.3.6 

In order to track object_changes I created this migration:

```
		class AddObjectChangesToVersions < ActiveRecord::Migration
		  TEXT_BYTES = 1_073_741_823

		  def change
		    add_column :versions, :object_changes, :text#, limit: TEXT_BYTES
		  end
		end
```
	
When the user submits the update form without changing any value a version is being registered anyway. Checking the `object_changes` with the database console I can see the column "value" supposedly had changed, but it has compared a string with an integer:

```
		| object_changes |
		+----------------+
		| ---           +|
		| value:        +|
		| - '2.0'       +|
		| - 2.0         +|
```

And I also think the serialized object looks strange, the `reference_id` value is quoted and the `id`  is not, the `description` value is unquoted and is a string. 

```
		 |                  object                  |
		-+------------------------------------------+
		 | ---                                     +|
		 | id: 69973                               +|
		 | reference_id: '19908'                   +|
		 | description: An unqouted String         +|
		 | value: '2.0'                            +|
		 | active: t                               +|
```
		 

ps. I can see in the logs that rails is executing the update command, setting a new timestamp to `updated_at` column and the same old value to the `value` column.  maybe this would make paper_trail to register the new Version? In this case I will have to check if any attribute changed before executing the `model.update_attributes(params)` method?

**Comment by gustavobap** [comment]
closing until I use the bug template

**Comment by jaredbeck** [comment]
Thanks for the bug report. Per our [contributing guide][1] please use
our [bug report template][2].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by gustavobap** [comment]
Thanks for the answer Jared. I know about the bug report template, just wanted to know if this actually looks like a bug or it's the expected behavior. I mean: when rails execute a update command setting the same old values to the respective columns, should paper_trails create a new Version or not ?

**Comment by jaredbeck** [comment]
Hi Gustavo, Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub. If you can't use our [bug report template][4], please close this and ask your question on  [StackOverflow][2]. Once you create a question on StackOverflow, please feel free to comment here with the URL.

[2]: https://stackoverflow.com/tags/paper-trail-gem
[4]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
