### ISSUE TITLE
Slow SQL query on versions table

### ISSUE THREAD

**Issue by fredngo** [airblade/paper_trail#1031]
Not really a bug but more of a performance issue.

I've noticed that after installing paper_trail, the following query has popped up as the "Slowest Execution Time" query in my postgres database.

```
COPY "public"."versions" ("id", "created_at", "transaction_id", "whodunnit", "event", "item_type", "item_id", "object", "object_changes") TO stdout;
```

It takes about 3 seconds to run this query.

Is there any way to disable this query? What feature could be causing this?

<img width="1373" alt="screen shot 2017-12-27 at 9 26 58 am" src="https://user-images.githubusercontent.com/11791/34384174-683ff6c2-eae8-11e7-9ebd-d6f3ed6f084d.png">

**Comment by jaredbeck** [comment]
AFAIK, PT does not execute any `COPY` commands. Can you reproduce this using our [bug report template][1]?

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by fredngo** [comment]
Unfortunately I have no idea what is causing this. I only saw this because Heroku keeps track of these slow queries. It is the only `COPY` query that shows up in the Heroku Postgres dashboard.

Very strange. If you guys don't know, then probably nobody will know. :-/

**Comment by fredngo** [comment]
For any random googlers: It appears that the `COPY` commands are caused by Heroku itself when creating automated backups of the database.

See https://devcenter.heroku.com/articles/expensive-queries:

> Large databases size or lock contention, causing slow COPY operations (usually used for logical backups).
