### ISSUE TITLE
master CHANGELOG.md is missing entry for v8.1.2

### ISSUE THREAD

**Issue by jalada** [airblade/paper_trail#1032]
`master` still looks like 8.1.1.

**Comment by jaredbeck** [comment]
> master still looks like 8.1.1.

Hi David. There are major differences between `master` and `v8.1.1`.

```
git diff --stat v8.1.1 master
 176 files changed, 602 insertions(+), 233 deletions(-)
```

Can you be more specific?

**Comment by jalada** [comment]
Oh...I think I understand now. `master` is tracking the unreleased v9?

The problem I had was when I came to find the changelog for 8.1.2, I couldn't, because the changelog only goes up to 8.1.1 before stopping. It was actually on a different tag. And the `README` is out of date; it only contains info up to 8.1.1.

So perhaps this issue is more 'update README on master to link to 8.1.2'?

**Comment by jaredbeck** [comment]
> master is tracking the unreleased v9?

yes

> The problem I had was when I came to find the changelog for 8.1.2, I couldn't, because the changelog only goes up to 8.1.1 before stopping.

Oh yeah, I made an entry to the `8-stable` changelog and forgot to make the same entry in `master`. Can you open a PR for that please? Thanks!

**Comment by jaredbeck** [comment]
Closed by https://github.com/airblade/paper_trail/pull/1034; thanks Anton.

I'm tempted to not have changelogs in the branches, ie. `master` would be the only branch with a changelog. The other branches could have a CHANGELOG.md that says "look in master". WDYT?

**Comment by jalada** [comment]
I think people look at `master` for `CHANGELOG`s and assume it will contain everything. So yes that sounds like a good idea.
