### ISSUE TITLE
Issue with version reify (and YAML serializer)

### ISSUE THREAD

**Issue by abrom** [airblade/paper_trail#1041]
Hi,

I've been updating a Rails 4.2 project from PT 4 to 5+ and found an issue relating to reify'ing versions created with v4 that have serialized columns. An `ActiveRecord::SerializationTypeMismatch` exception is raised when the already deserialized attribute is deserialized 'again' (attempting to deserialize a Hash object). PT 4 (using YAML serialization) appears to store version object data with serialized columns as objects, whereas PT 5+ appears to store them as serialized strings of objects

I've searched through forums/readme's etc but couldn't find anything specific to this. 

I've created a gist based on the bug template that demonstrates the issue:

https://gist.github.com/abrom/31fdd46413eae6aed559c00edf2f8b60

Steps to reproduce are:
* With PT < 5, create a version for a model containing a serialized attribute
* With PT >= 5, try reify the version

My assumption is that the object data is expected to be updated when migrating from pre 5 to 5+ to accomodate for this issue? 

An alternative that 'works' is to update the `deserialize` method on `CastAttributeSerializer` to something like the following. 

```
def deserialize(attr, val)
  if defined_enums[attr] && val.is_a?(::String)
    # Because PT 4 used to save the string version of enums to `object_changes`
    val
  else
    type = @klass.type_for_attribute(attr)
    if type.is_a?(ActiveRecord::Type::Serialized) && val.is_a?(type.coder.object_class)
      # Because PT 4 stores serialized objects as objects, rather than serialized strings of the object
      val
    else
      val = type.type_cast_from_database(val)
      if defined_enums[attr]
        defined_enums[attr].key(val)
      else
        val
      end
    end
  end
end
```

**Comment by abrom** [comment]
To somewhat answer my own question RE migrating from PT < 5 to PT 5+, the following will do so:

```
PaperTrail::Version.where(item_type: '<model name with PT and serialize>').each do |version|
  next unless version.object.present? && version.object_deserialized.any? { |k, v| v.present? && v.is_a?(Hash) }

  new_object = version.object_deserialized.transform_values do |value|
    if value.present? && value.is_a?(Hash)
      PaperTrail.serializer.dump value
    else
      value
    end
  end
  version.update_columns object: PaperTrail.serializer.dump(new_object)
end
```

Can update all records by removing the `where` filter but wouldn't recommend if you've got a lot of version records that don't need fixing!

Happy to see the issue closed if the above is the preferred solution

**Comment by jaredbeck** [comment]
> I've been updating a Rails 4.2 project from PT 4 to 5+ ..

It is good that you are updating one version of PT at a time. Keep an eye out for deprecation warnings, and read the changelog carefully.

It looks like you are trying to use PT 5.0.0? I'd recommend going straight to 5.2.3. There was some work done on (de)serialization in 5.2.1.

PT 5 -> 6 is another potentially big upgrade, but 7 and 8 should be pretty easy for most people.

**Comment by abrom** [comment]
Thanks @jaredbeck 

Yes, I am now using 5.2.3; I was just using 5.0.0 in the example to demonstrate that it was a v4->v5 update issue (rather than a minor version problem within v5)

**Comment by jaredbeck** [comment]
Given that it sounds like 5.2.3 fixes the problem you identified in 5.0.0, and given that we're probably not going to release any new 5.x versions anyway, should we close this? Thanks.

**Comment by abrom** [comment]
Hi @jaredbeck, sorry if I wasn't clear above, but unfortunately 5.2.3 is behaving the same as 5.0.0. The issue applies to all versions 5+. The solution, as I see it, is to either do something like the modification from  my first comment (extra check in `deserialize` method of `CastAttributeSerializer`) or to iterate existing data and modify it as per my second comment.

I ended up taking the 2nd option. Happy to close the issue if this behaviour is expected? I could put together a PR to document this properly. Would just need to know where/how the preferred location for such docs would be. Clearly it's an edge case so I expect the main readme isn't the place.

**Comment by jaredbeck** [comment]
> The issue applies to all versions 5+.

To clarify, version 4 serializes differently from all subsequent versions?

> I could put together a PR to document this properly.

Honestly, I still don't understand this issue, so I have no idea if documentation is the right solution.

Can you put together a bug report using our [template][1]? Insert some PT4-flavord records using raw SQL `execute` and then deserialize using PT >= 5? Thanks.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by abrom** [comment]
> To clarify, version 4 serializes differently from all subsequent versions?

Yes, correct

> Honestly, I still don't understand this issue, so I have no idea if documentation is the right solution.

Sure, understand. I've resolved this issue with my dataset by using the migration detailed in my first comment. If you don't see it being an issue for others, happy to just close.

> Can you put together a bug report using our template? Insert some PT4-flavord records using raw SQL execute and then deserialize using PT >= 5? Thanks.

I created the gist in the initial issue description using the standard template, but needed to tweak the template a smidge to support the two different gems at the same time (one after the other). I wanted to avoid static SQL in the example as I would consider that a valid test of v4 vs v5 per se.

The gist in it's current form will:
* Install v4.0
* Setup the DB with a basic user/version table setup
* Serialize some Hash data (using the default YAML serializer) - circa L91

* Install v5.0
* Assert that there is a serialization type mismatch trying to read the previous user version - circa L114

Happy to create another version of the gist without the two PT versions and SQL insert the data instead if the above description isn't cutting it 👍

**Comment by jaredbeck** [comment]
Thanks for the detailed response Andrew. I'm sorry, I had forgotten about your gist. It's a great gist, thanks. Interestingly, when I run it with 4.0.0/5.0.0 it reproduces the `SerializationTypeMismatch` but when I run it with 4.2.0/5.0.0 it does not. Are you seeing the same?

**Comment by jaredbeck** [comment]
Hi Andrew, are you still working on this? Want me to keep it open?

**Comment by abrom** [comment]
Hi @jaredbeck, sorry about that.. You're right, the issue appears to be when updating from v4.0.2 to v4.1.0.  Although I had been on v4.2.3 for some time?! Really can't explain it given I only saw the problem when changing to v5. Weird

Given it's such an old change it doesn't seem there is much else to do.

**Comment by kirichkov** [comment]
Just to expand on @abrom's solution, as serialized Arrays are suffering from the same faith as Hashes:

**Please note:** I haven't tested this with both serialized Array and Hash present, only with serialized Arrays.

```ruby
PaperTrail::Version.where(item_type: '<model name with PT and serialize>').each do |version|
  next unless version.object.present? && version.object_deserialized.any? { |k, v| v.present? && (v.is_a?(Hash) or v.is_a?(Array)) }

  new_object = version.object_deserialized.transform_values do |value|
    if value.present? && (value.is_a?(Hash) || value.is_a?(Array))
      PaperTrail.serializer.dump value
    else
      value
    end
  end
  version.update_columns object: PaperTrail.serializer.dump(new_object)
end

```

**Comment by lukeasrodgers** [comment]
also encountering this - issue seems to be this code in 4.1.0 (essentially same code is present in master still, but moved to class `AttributeSerializers`)

```
    def alter_attribute_changes_for_paper_trail!(serializer, changes)
      # Don't serialize before values before inserting into columns of type
      # `JSON` on `PostgreSQL` databases.
      return changes if paper_trail_version_class.object_changes_col_is_json?

      changes.clone.each do |key, change|
        type = type_for_attribute(key)
        changes[key] = Array(change).map { |value| type.send(serializer, value) }
      end
    end
```

In my case, `serializer` is `type_cast_for_database`, `type` is instance of `ActiveRecord::Type::Serialized:` using a YAML coder with `object_class` `Hashie::Mash`, which then tries to dump the value, but the value is a hash instead of hashie mash (since this is how rails reports the changes), which causes the `ActiveRecord::SerializationTypeMismatch` error. It's possible to workaround this with something like 

```
changes.clone.each do |key, change|
  type = type_for_attribute(key)
  changes[key] = Array(change).map do |value|
    if (type.respond_to?(:coder) && object_class = type.coder.try(:object_class))
      type.send(serializer, type.coder.object_class.new(value))
    else
      type.send(serializer, value)
    end
  end
end
```

but this is ugly/fragile, and makes assumptions about how to initialize `object_class`. OTOH cursory glance at current rails code in rails seems like this would probably be compatible from 4.x to 6.x, don't appear to be any changes to the `Type` classes or YAML column coder that would break the above code.
