### ISSUE TITLE
DEPRECATION WARNING: The behavior of attribute_changed?

### ISSUE THREAD

**Issue by abuhtoyarov** [airblade/paper_trail#1044]
Hey.
I get warnings when I create a new record

``
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead. (called from changes_in_latest_version at
``

```
Rails 5.1.2
PaperTrail 8.1.2
```

**Comment by jaredbeck** [comment]
```
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md
```

**Comment by jaredbeck** [comment]
Just to clarify, this does sound like something we should investigate. Please open a new issue using our [bug report template](https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb).
