### ISSUE TITLE
Skip object on update

### ISSUE THREAD

**Issue by seanlinsley** [airblade/paper_trail#1046]
Around 50% of a long-lasting `versions` table of mine is storing the `object` on updates:

```sql
select event,
  pg_size_pretty(sum(pg_column_size(object))) as object_size,
  pg_size_pretty(sum(pg_column_size(object_changes))) as object_changes_size
from versions
group by event;

  event  | object_size | object_changes_size 
---------+-------------+---------------------
 create  | 4736 bytes  | 7418 MB
 update  | 13 GB       | 4246 MB
 destroy | 830 MB      | 
```

In this application that's not really storing useful information; the only time `object` becomes useful is when a record needs to be reified after being destroyed.

Would a PR be welcome to add the ability to skip `object` on update? It'd essentially be the inverse of #507.

**Comment by jaredbeck** [comment]
Hi Sean, 

If the problem is table size, one could use `version_limit`.

You might also see some small savings by using a `jsonb` column instead of `text`.

If neither of those helps, and you want to proceed with your original idea, I think I'd prefer it be a separate gem at first, to see how many people have the same problem. It sounds like an uncommon problem. We can mention the new gem in various places in the readme.

**Comment by seanlinsley** [comment]
It's important to track every update, so `version_limit` wouldn't work.

`jsonb` is already being used. I started looking at options to compress the data when I realized that half of the storage space used isn't hold useful data.

How would you imagine the gem would be structured? The existing code doesn't seem easy to extend.

I doubt we're going to get many people interested in trying this out; time-crunched app developers are much more likely to pay for a bigger database or delete old data.

Unless there's something I'm missing, it seems like this should be the default behavior of Paper Trail. Storing duplicates of all the columns on every update just isn't scalable over long periods of time. Though of course that'd be a breaking change, so the better choice would be to recommend it in the documentation.

**Comment by jaredbeck** [comment]
> How would you imagine the gem would be structured? The existing code doesn't seem easy to extend.

I think it could be done as-is by re-opening classes or via module-prepend, but those techniques are brittle and I'm open to suggestions on how make it easier to extend without those techniques.

> Unless there's something I'm missing, it seems like this should be the default behavior of Paper Trail. Storing duplicates of all the columns on every update just isn't scalable over long periods of time. Though of course that'd be a breaking change, so the better choice would be to recommend it in the documentation.

I agree, I've always wondered why Andy chose to design PT that way. Some of his original comments about that decision can still be found in the readme:

> PaperTrail stores the pre-change version of the model, unlike some other auditing/versioning plugins, so you can retrieve the original version. This is useful when you start keeping a paper trail for models that already have records in the database.
> ..
> This also means that PaperTrail does not waste space storing a version of the object as it currently stands. The versions method gives you previous versions; to get the current one just call a finder on your Widget model as usual.
> https://github.com/airblade/paper_trail#1c-basic-usage

I've always had my own questions about this explanation. It doesn't seem to be a complete analysis of the trade-offs. However, I'm hesitant to even discuss changing such a fundamental design decision. Also, incremental diffs have their own drawbacks. They make reification much more expensive, for example.

**Comment by jaredbeck** [comment]
Sean, Re-reading this discussion, I'm really hesitant to make such a fundamental change, and I'm fairly convinced this needs to be a separate gem, at least at first. So, is this something you're still interested in working on? Want me to keep this issue open?
