### ISSUE TITLE
override version_associations table name?

### ISSUE THREAD

**Issue by mcconkiee** [airblade/paper_trail#1049]
hi - I was getting this error 
```
Table 'db.version' doesn't exist
```
Turns out my models had a conflict with the name convention since we have a version property already being used. I solved this by being explicit about the `table_name`, setting the `class_name` as instructed

```
class Versions < PaperTrail::Version
  self.table_name = :versions
end

class MyModel < ActiveRecord::Base 
 has_paper_trail class_name: 'Versions', versions: :paper_trail_versions, version:  :paper_trail_version
end
```

Apparently I also need to do this with the `version_associations` table. I'd imagine the  i could declare

```
class VersionAssociations < PaperTrail::VersionAssociation
  self.table_name = :version_associations
end
```

but how do set that on MyModel class?

**Comment by mcconkiee** [comment]
update: thanks to [828](https://github.com/airblade/paper_trail/issues/828)!

i added 

```
PaperTrail::VersionAssociation.class_eval do
  self.table_name = 'version_associations'
end
``` 

to my initializer....its working!

**Comment by jaredbeck** [comment]
Hi Eric, Glad you found a solution. I don't understand why you had to specify `table_name=`. Are you sure it's necessary?

Re: model configuration, it is documented here: https://github.com/airblade/paper_trail#5b-configuring-the-versions-association

I'd appreciate any suggestions for improving that documentation; please open a PR.
