### ISSUE TITLE
Missing documentation for PaperTrail.controller_info

### ISSUE THREAD

**Issue by aried3r** [airblade/paper_trail#1059]
The README only mentions it two times wrt testing paper_trail, basically that it will be set to `{}` after the tests. But nowhere is it mentioned where this should be set and what could be achieved with it, how it works together with `info_for_paper_trail` etc.

I quickly glimpsed over the code and am beginning to understand how it works. Still, I think there should be official documentation about it. The best I could find was this comment https://github.com/airblade/paper_trail/issues/524#issuecomment-123160485.

A little background: I was researching how I can have ìp` and `user_agent` always set, while individual controllers can add more with `info_for_paper_trail`, if I have to manually merge the hashes etc. Basically the part of the documentation that I think was missing.

**Comment by jaredbeck** [comment]
Thanks, Anton. I think that would be a useful addition to the docs. I recommend putting it in section 4. "Saving More Information About Versions".

`controller_info` was recently added to `paper_trail-sinatra` (https://github.com/jaredbeck/paper_trail-sinatra/pull/5) so we should mention that gem in the docs.

**Comment by jaredbeck** [comment]
Still working on this, Anton? Want me to keep it open?

**Comment by aried3r** [comment]
Ahh, sorry. I actually don't really know how it works and I was missing documentation 😅. But I can take a jab and look at the source and tests to see how it works with merging and everything. Can't promise a time line, though. You can close it if you want and hopefully I'll get to it soon.
