### ISSUE TITLE
touch_with_version should accept more than one argument

### ISSUE THREAD

**Issue by westonganger** [airblade/paper_trail#1061]
The method `touch_with_version` only accepts one optional attribute:

https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/record_trail.rb#L465

To behave the same as the ActiveRecord `touch` method it needs to accept multiple optional attributes (and apparently a Time as well since Rails v5.0)

http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-touch

Just documenting this issue before I create a PR.

**Comment by jaredbeck** [comment]
> To behave the same as the ActiveRecord touch method ..

If this is going to be a goal of ours, maybe it's time to re-investigate hooking into the `after_touch` callback and deprecate `touch_with_version`.

**Comment by westonganger** [comment]
Okay fair enough. Im gonna start looking into this.

**Comment by westonganger** [comment]
Closing this issue because the `touch_with_version` method is deprecated in v9.0.0
