### ISSUE TITLE
Please restore without_versioning - cannot use 3.0.0 without it

### ISSUE THREAD

**Issue by david-a-wheeler** [airblade/paper_trail#1072]
I've learned that paper_trail version 3.0.0 dropped the "without_versioning" method; without it, I can't use paper_trail.  Can that capability be restored?

In our project we use the field "updated_at" to mean "updated by a user", not "updated by random processes not visible to anyone outside".  This works nicely, however, when we send email reminders we need to do this:

~~~~
    projects.each do |inactive_project| # Send actual reminders
      ReportMailer.email_reminder_owner(inactive_project).deliver_now
      # Save while disabling paper_trail's versioning through self.
      # Don't update the updated_at value either, since we interpret that
      # value as being an update of the project badge status information.
      inactive_project.paper_trail.without_versioning do
        inactive_project.last_reminder_at = Time.now.utc
        inactive_project.save!(touch: false)
      end
    end
~~~~

Thus we need the "without_versioning" method to use paper_trail.

Can that please be restored?

Thanks!

**Comment by jaredbeck** [comment]
Hi David. 

You're upgrading to 3? The latest version is 9. I recommend upgrading slowly, one major version at a time.

Once you get to PT 9 you can do:

```
projects.each # ...
  PaperTrail.request(enabled: false) do
    # whatever
  end
end
```

Hope that helps.

If you identify any problems in PT 9, please open a new issue. If you have further questions about upgrading, please ask on StackOverflow, thanks. Good luck with your upgrade!

**Comment by david-a-wheeler** [comment]
Sorry, I meant version 9.0.0.  I was simultaneously updating something else to its version 3 and totally scrambled them in my mind.

Thanks VERY MUCH for the workaround!

I'll create a *separate* issue that I think the deprecation warning should be made clearer, because it never mentions "request(enabled: false)".  But I'll do that separately.

**Comment by david-a-wheeler** [comment]
Hmm, on further investigation, the "request(enabled: false)" *is* noted in the deprecation warning from paper_trail.  Clearly I'm just having a bad day; the problem appears to be between my chair and my keyboard :-).

Sorry to bother you, and thanks VERY MUCH for the kind answer to what in retrospect was obvious.

**Comment by jaredbeck** [comment]
Haha, no worries, don't beat yourself up :)

I'm glad to hear you're not still on version 3!
