### ISSUE TITLE
Track changes on destroy

### ISSUE THREAD

**Issue by cyrilchampier** [airblade/paper_trail#1075]
It is said [in the documentation](https://github.com/airblade/paper_trail/blob/a0697ceb929f4f12bedf25d06983dd5b9812b8c6/README.md#L683):
> The object_changes are only stored for creation and updates, not when an object is destroyed.

In our app, we do modifications during destroy (`status = 'deleted'`) and would like to track the changes.
To try to understand, I quickly modified the gem here:
https://github.com/airblade/paper_trail/blob/f6e6e89a2851a45e93031e55963917cfa62dc667/lib/paper_trail/record_trail.rb#L319
by adding 
```
      if record_object_changes? && changed_notably?
        data[:object_changes] = recordable_object_changes
      end
```
and the behavior is exactly what we expect.

Would you accept a PR adding this behavior ?

**Comment by jaredbeck** [comment]
Hi Cyril, thanks for the suggestion. I'm a little confused though.

> In our app, we do modifications during destroy (status = 'deleted')

So when your app calls `destroy`, what SQL occurs: `update`, `delete`, both?

**Comment by cyrilchampier** [comment]
here is the "full code" of our model:
```
  paper_trail.on_destroy :after

  def destroy(with_attributes: { status: 'deleted' })
    assign_attributes(with_attributes)
    run_callbacks :destroy do
      timestamp = Time.current
      update_columns(with_attributes.merge(deleted_at: timestamp, updated_at: timestamp))
    end
  end
```

so in fact, it's a simple update.
on top of that, we have a synchronizable concern included in version class that send modifications to a third party software.
what we need is to have `object_changes == { status: { -'something' +'deleted' } }`
and we achieve this by simply adding the `data[:object_changes]` assignation in `data_for_destroy`.

is it more clear ?

**Comment by cyrilchampier** [comment]
if I understand metadata well, we would store a hash of changes of this "statuts" column,
which would probably be a workaround but would duplicate the gem work.

I see your point, but that would be a good reason to factorise some code,
and introduce a common method used in `data_for_create`,  `data_for_destroy`,  `data_for_update` and `data_for_update_columns`
```
    def data_for_changes(event_type, changes)
      data = {
        event: @record.paper_trail_event || event_type,
        object: recordable_object,
        whodunnit: PaperTrail.request.whodunnit
      }
      if record_object_changes?
        data[:object_changes] = recordable_object_changes(changes)
      end
      add_transaction_id_to(data)
      merge_metadata_into(data)
    end
```

this way, our use case would be covered, and the PT code would not be complexified ?
do you want me to make a sample pr ?

**Comment by jaredbeck** [comment]
> .. introduce a common method used in data_for_create, data_for_destroy, data_for_update and data_for_update_columns ..

That does not seem necessary, given that you can overwrite `object_changes` using metadata. I just clarified this in the docs yesterday. See ["Metadata can Override PaperTrail Columns"](https://github.com/airblade/paper_trail#metadata-can-override-papertrail-columns)

**Comment by cyrilchampier** [comment]
ok, i think I understand why you spoke about metadata now.
do you mean I should add something like this in my model ?

```
  has_paper_trail(
    meta: {
      object_changes: proc { |appointment| { status: { '-' => appointment.status, '+' => 'deleted' } } }
    },
    on: %i(destroy)
  )
```

**Comment by jaredbeck** [comment]
>  do you mean I should add something like this in my model ?

Yes, `:object_changes` can be a key in the `:meta` hash and whatever value you give will overwrite what PT would normally insert into that column.

**Comment by cyrilchampier** [comment]
ok, thanks for the workaround. It's far from perfect, but it could work, thanks.

**Comment by chabgood** [comment]
> It is said [in the documentation](https://github.com/airblade/paper_trail/blob/a0697ceb929f4f12bedf25d06983dd5b9812b8c6/README.md#L683):
> 
> > The object_changes are only stored for creation and updates, not when an object is destroyed.
> 
> In our app, we do modifications during destroy (`status = 'deleted'`) and would like to track the changes.
> To try to understand, I quickly modified the gem here:
> https://github.com/airblade/paper_trail/blob/f6e6e89a2851a45e93031e55963917cfa62dc667/lib/paper_trail/record_trail.rb#L319
> by adding
> 
> ```
>       if record_object_changes? && changed_notably?
>         data[:object_changes] = recordable_object_changes
>       end
> ```
> 
> and the behavior is exactly what we expect.
> 
> Would you accept a PR adding this behavior ?

It should track a destroy:

PaperTrail.config.has_paper_trail_defaults = {
  on: %i[create update destroy]
}
