### ISSUE TITLE
Touch not saving changes. touch_with_version did

### ISSUE THREAD

**Issue by key88sf** [airblade/paper_trail#1076]
Simple example of the difference:
```
> p = Person.last
> p.name = "New Name"
> p.touch
# UPDATE people SET updated_at = ....
```
^^ This **does not** update the name in either the database or the versions table.
```
> p.paper_trail.touch_with_version
# UPDATE people SET updated_at=..., name='New Name' ...
```
^^ This updates **both** the name in the database, **and** adds a correct version row for the updated name in the versions table.

This is a huge difference in behavior, and one which is relied upon likely by many people besides us -- it is **integral** to the behavior of the [counter_culture](https://github.com/magnusvk/counter_culture) gem's support of the `with_papertrail` option.

Please either do not deprecate this, or fix the behavior of `touch` to be equivalent. Right now they are two completely different behaviors.

**Comment by westonganger** [comment]
Okay so touch_with_version should almost be called save_with_version

**Comment by key88sf** [comment]
Sure, that would be fine. I definitely do not think this should just be deprecated though, as it's completely different behavior.

**Comment by jaredbeck** [comment]
Closing via https://github.com/airblade/paper_trail/pull/1078

> Okay so touch_with_version should almost be called save_with_version

I like the idea of having a `save_with_version` method, but if that's what it's called, I'd rather have it just do a `save` and not (simulate) a `touch`. So, that led me to the implementation in https://github.com/airblade/paper_trail/pull/1078. I hope it works for you, @key88sf.

**Comment by key88sf** [comment]
Yes thanks!
