### ISSUE TITLE
NoMethodError: undefined method `asc' for nil:NilClass when initializing test database

### ISSUE THREAD

**Issue by samstickland** [airblade/paper_trail#1080]
Hi,

I am trying to upgrade an old Rails app for a non-profit organisation, but I am having issues getting paper_trail to work. On Rails 3.0.20, with paper_trail 5.2.3 I get:

```
NoMethodError: undefined method `asc' for nil:NilClass
/Users/samuelstickland/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.0.20/lib/active_support/whiny_nil.rb:48:in `method_missing'
/Users/samuelstickland/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-5.2.3/lib/paper_trail/version_concern.rb:108:in `timestamp_sort_order'
/Users/samuelstickland/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-5.2.3/lib/paper_trail/model_config.rb:130:in `setup_associations'
/Users/samuelstickland/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-5.2.3/lib/paper_trail/model_config.rb:76:in `setup'
/Users/samuelstickland/.rvm/gems/ruby-1.9.3-p551/gems/paper_trail-5.2.3/lib/paper_trail/has_paper_trail.rb:65:in `has_paper_trail'
/Users/samuelstickland/development/maloca/app/models/news_item.rb:7:in `<class:NewsItem>'
```

when executing:

`RAILS_ENV=test bundle exec rake db:schema:load`

It seems to me that when rake is starting up it processing `has_paper_trail` in the `NewsItem` model, which causes `paper_trail` to attempt to look for the `versions` table properties.. but as the schema has not yet been loaded into the test database this fails.

Any ideas how to resolve this will be gratefully received!

**Comment by jaredbeck** [comment]
Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub. 

Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/airblade/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by samstickland** [comment]
@jaredbeck I found the problem.

In our version of Rails3 the referencing of observers in config/application.rb in `config.active_record.observers` causes Rails to parse the observers and the observed classes during Application/Rake startup as well.

This means that the class DSL for gems like paper_trail are invoked during commands like `bundle exec rake db:schema:load` and in paper_trail's case this will cause this method to attempt look up fields on a table that does not exist

To work-around this we are monkey patching `timestamp_sort_order` with a guard clause.

```
module PaperTrail
  module VersionConcern
    module ClassMethods
      def timestamp_sort_order(direction = 'asc')
        return unless ActiveRecord::Base.connection.table_exists? arel_table.name

        [arel_table[PaperTrail.timestamp_field].send(direction.downcase)].tap do |array|
          array << arel_table[primary_key].send(direction.downcase) if self.primary_key_is_int?
        end
      end
    end
  end
end
```

**Comment by jaredbeck** [comment]
Sam, I'm glad you were able to find a workaround, thanks for sharing it. 

> On Rails 3.0.20, with paper_trail 5.2.3 ..

As I'm sure you know, the latest versions are 5.2 and 9.0, respectively. The versions you are using are no longer supported. Please continue to upgrade slowly and steadily. With rails, I recommend going 3.0, 3.1, 3.2. With PT you can go 5, 6, 7. Please do one at a time and resolve deprecations before continuing. Good luck!
