### ISSUE TITLE
Mysql Cluster support

### ISSUE THREAD

**Issue by Fivell** [airblade/paper_trail#109]
In MySQL Cluster auto_increment values are stored in the distributed database
since they are global (per table). Since it is much more expensive to manage such
counters than in a local non-distributed database, the auto_increment values are
pre-fetched in batches (currently of size 32).

so running two clients, where  inseringt in the first I get 0 (since it has a batch 0 - 31) and  inserting in the
second I get 32 (since it has a batch of 32-63).

So scopes of version class where primary_key is used are not working with Mysql Cluster

**Comment by jaredbeck** [comment]
> This issue should technically be solved now I think, in the sense that I've mostly removed the usage of the primary key for logic to determine order of rows. 

@Fivell Given Ben's comment (above) from 2013, it sounds like this is fixed (assuming you can synchronize the system clocks across your cluster :) ).  If so, can you close this issue?  Thanks.

**Comment by Fivell** [comment]
Sure.
