### ISSUE TITLE
Track timestamp of destroy event

### ISSUE THREAD

**Issue by Cashaca** [airblade/paper_trail#1425]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

It appears that when an item is destroyed/deleted there is no way to query when this happened. The object_changes["updated_at"] field will show the updated_at timestamp before the destroy event and then change into nil

**Describe the solution you'd like to build**

Add a timestamp to the versions table that record the timestamp of the "event"

**Describe alternatives you've considered**

It is probably also possible to add this information as a custom meta data column. Would be useful in that case to show how to do this in the readme. 

Would this be correct ?

has_paper_trail(
    meta: {
      event_at:  proc { Time.now } # a Proc
    }
  )

**Comment by iiwo** [comment]
@Cashaca `PaperTrail` already includes a [created_at timestamp column](https://github.com/paper-trail-gem/paper_trail/blob/1fe26c9e445b0bcb2f7c20a5791ec01003632517/lib/generators/paper_trail/install/templates/create_versions.rb.erb#L34) that [holds the time of the event](https://github.com/paper-trail-gem/paper_trail#1c-basic-usage)
