### ISSUE TITLE
Compatibility problems with optimistic locking / lock_version

### ISSUE THREAD

**Issue by saizai** [airblade/paper_trail#163]
Suppose you have a Widget with a lock_version column.

If you try to do `widget.previous_version.save!`, you'll get a `ActiveRecord::StaleObjectError`.

I'm not sure how to override this. Ideally what should happen is that the newly reified object should have the same staleness / lock properties as the original object, so that if `widget` is OK to save then `widget.previous_version` should be too (since it hasn't changed out from under you).

Any ideas for how to implement this?

**Comment by jaredbeck** [comment]
> The only workaround I have found to to change the lock_version attribute after reifying to the current lock_version and then saving the object. -Justin

I'm not sure I'd describe that as a workaround.  I haven't used [optimistic locking][1] personally, but based on the documentation it sounds like you're using it as intended; you want to update a record, so you must increment the lock_version.

I'm adding a note to the readme about this. (https://github.com/airblade/paper_trail/issues/550)

> I did: model.lock_version += 1 if model.respond_to? :lock_version in version_concern.rb, line 125 just before returning 'model' -Walther

I think this would work in a single-threaded app, but without concurrency control would not be sufficient in a multi-threaded app.

> I don't know if it makes sense to .. code that into PaperTrail .. -Ben

I agree.  If PaperTrail ever adds a high-level undo function, this is something we'll have to keep in mind.

[1]: http://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html
