### ISSUE TITLE
Wrong DateTime in created_at field

### ISSUE THREAD

**Issue by ejmm320** [airblade/paper_trail#170]
Hi all, i have a problem with the created_at field, the value saved is not correct.
Example: 

Output for date command in shell:

<pre>jue ago 30 09:16:05 VET 2012</pre>

Output for psql> select now();

<pre>
 now                
----------------------------------
 2012-08-30 09:17:36.247966-04:30
</pre>

Value saved in my versions table about 15 min ago:

<pre>
created_at         
----------------------------
 2012-08-30 13:25:41.439961
</pre>

Rails console:

<pre>
1.9.3-p125 :001 > Time.now
 => 2012-08-30 09:23:20 -0430 
</pre>

Is possible to config paper_trail to work with my timezone? Maybe i'm missing something here...

Any help will be appreciated.

Thanks!

**Comment by pranayjeurkar** [comment]
Hi all,
Setting up 
config.time_zone = 'Caracas' changes the time in my model 
My versions.created_at column still records UTC time, how can I set this value to config.time_zone = 'Caracas' ?

**Comment by jaredbeck** [comment]
> My versions.created_at column still records UTC time ..

Rails always records UTC time in the database. In ruby objects, you can have Caracas-time, but in the database rails will store UTC time. This is unrelated to PaperTrail, it's just how rails works. It's a good thing, too. Having a standard timezone in your database makes your database easier to understand.

It may be possible to change this with `config.active_record.default_timezone = :local` but I've never tried that, and it sounds like a bad idea.
