### ISSUE TITLE
A way to automatically limit the number of stored versions

### ISSUE THREAD

**Issue by snoblenet** [airblade/paper_trail#213]
I know there are tools for manually deleted versions created before a certain date.

I'm looking to configure PaperTrail globally so it only ever stores n many versions of each instance.

something like

config.version_limit = 5

If there are n versions stored, and PaperTrail wants to store a new one, it automatically deletes the oldest to make room.

Is this possible?

**Comment by vanboom** [comment]
+1 for model specific version limits

**Comment by jaredbeck** [comment]
> +1 for model specific version limits

Please see https://github.com/airblade/paper_trail/pull/915 if you'd like to help implement this feature or have something constructive to add.
