### ISSUE TITLE
Way to retrieve version that was just created?

### ISSUE THREAD

**Issue by iwarshak** [airblade/paper_trail#215]
If I do @model.save, a new Version is created. is there a good way to atomically retrieve this version? Is @model.versions.last the only way? Would I wrap this in an AR transaction to ensure I get the correct version (in case someone else way manipulating the model at the same time?

**Comment by TylerRick** [comment]
@iwarshak, Good idea wrapping that in a transaction.  Seems like that is necessary to avoid a race condition.

Also like your idea of an activity feed that references a` version_id`.  I may have to try that...

**Comment by idreesibrahim** [comment]
> Here is a solution that I have come up with. Pretty simple, actually.
> 
> First, my use case is: I am versioning my changes. I am also generating an activity feed entry anytime a change is made. I want to keep a reference to the version number in my activity feed entry model.
> 
> Previously, I was doing something like
> 
> ```
> if @post.save
>   version_id = @post.versions.last.id
>   FeedEntry.create(text:'Post created', version_id:version_id
> end
> ```
> 
> The problem is that if 2 requests come in modifying @post, one of those requests could get a reference to the wrong version id.
> 
> My solution is
> 
> ```
> class Post
>     def save_with_version
>     transaction do
>       if save
>         return self.reload.versions.last.id
>       else
>         return false
>       end
>     end
>   end
> end
> 
> ....
> 
> if version_id = @post.save
>   FeedEntry.create(text:'Post created', version_id:version_id
> end
> ```



> Here is a solution that I have come up with. Pretty simple, actually.
> 
> First, my use case is: I am versioning my changes. I am also generating an activity feed entry anytime a change is made. I want to keep a reference to the version number in my activity feed entry model.
> 
> Previously, I was doing something like
> 
> ```
> if @post.save
>   version_id = @post.versions.last.id
>   FeedEntry.create(text:'Post created', version_id:version_id
> end
> ```
> 
> The problem is that if 2 requests come in modifying @post, one of those requests could get a reference to the wrong version id.
> 
> My solution is
> 
> ```
> class Post
>     def save_with_version
>     transaction do
>       if save
>         return self.reload.versions.last.id
>       else
>         return false
>       end
>     end
>   end
> end
> 
> ....
> 
> if version_id = @post.save
>   FeedEntry.create(text:'Post created', version_id:version_id
> end
> ```

let me know if there are concurently request at same time how can you differentiate which one is last request ?? it is very difficult to find. there should be another way ...

**Comment by avneetmalhotra** [comment]
Hi @batter 
I saw your comment - https://github.com/paper-trail-gem/paper_trail/issues/215#issuecomment-19049427.

Are you still open to adding add an option to allow users to save_with_version to track the current persisted data?
I was thinking something on the line of `has_paper_trail save_with_version: true`
