### ISSUE TITLE
paper_trail doesn't seem to work with acts-as-taggable-on

### ISSUE THREAD

**Issue by aaronjensen** [airblade/paper_trail#224]
paper_trail tries to set the fake attributes that acts-as-taggable-on uses resulting in:

```

ActiveModel::MissingAttributeError: can't write unknown attribute `tag_list'
    vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0.rc1/lib/active_record/attribute_methods/write.rb:45 • write_attribute
    vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0.rc1/lib/active_record/attribute_methods/dirty.rb:70 • write_attribute
    vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0.rc1/lib/active_record/attribute_methods.rb:317 • []=
    vendor/bundle/ruby/2.0.0/bundler/gems/paper_trail-6d446564d92e/lib/paper_trail/has_paper_trail.rb:266 • block (2 levels) in item_before_change
    vendor/bundle/ruby/2.0.0/bundler/gems/paper_trail-6d446564d92e/lib/paper_trail/has_paper_trail.rb:266 • each
    vendor/bundle/ruby/2.0.0/bundler/gems/paper_trail-6d446564d92e/lib/paper_trail/has_paper_trail.rb:266 • block in item_before_change
    vendor/bundle/ruby/2.0.0/bundler/gems/paper_trail-6d446564d92e/lib/paper_trail/has_paper_trail.rb:264 • tap
    vendor/bundle/ruby/2.0.0/bundler/gems/paper_trail-6d446564d92e/lib/paper_trail/has_paper_trail.rb:264 • item_before_change
    vendor/bundle/ruby/2.0.0/bundler/gems/paper_trail-6d446564d92e/lib/paper_trail/has_paper_trail.rb:208 • record_update 
```

**Comment by dhruvbhatia** [comment]
Seems paper_trail doesn't track tag list changes under Rails 5. I think it may have something to do with [API changes, as per this issue](https://github.com/mbleigh/acts-as-taggable-on/issues/836).

Anybody else experiencing this?

**Comment by jaredbeck** [comment]
> Seems paper_trail doesn't track tag list changes under Rails 5.

Hi Dhruv, I was just discussing this with someone on S.O. (https://stackoverflow.com/questions/45156752/rails-how-to-enable-papertrail-auditing-for-tags) 

> Two suggestions: 1. use Version Metatadata (github.com/airblade/paper_trail#4c-storing-metadata) 2. use Association Tracking (github.com/airblade/paper_trail#4b-associations)

I haven't heard back from them if they tried either.
