### ISSUE TITLE
undefined local variable or method `has_paper_trail' 

### ISSUE THREAD

**Issue by ebinjo13** [airblade/paper_trail#227]
I am using the latest version 2.7.1. After the gem installed and table created I have added "has_paper_trail" in my model and end up with getting "undefined local variable or method has_paper_trail'"

**Comment by jerryclinesmith** [comment]
FWIW, you get this error if you add "has_paper_trail" to a non-ActiveRecord model.  Might help someone who finds this in the future.

**Comment by zainonrails** [comment]
@batter 
In the latest version of PT, using rails 5.2.1 I faced this issue on an AR Model.
The error was 
```
NoMethodError (undefined method `before_action' for Order (call 'Order.connection' to establish a connection):Class)
Did you mean?  before_commit
```
Using `before_commit` rather than `before_action` resolved my issue.
The docs doesn't say anything about it, is this expected behavior..?
