### ISSUE TITLE
PaperTrail for all models

### ISSUE THREAD

**Issue by nicholaide** [airblade/paper_trail#234]
Is it possible to extend PaperTrail so that it is available to all models? Monkey-patching ActiveRecord::Base does not work as expected, and probably rightly so, because associations aren't taken into account.

Thank you.

**Comment by SandipBhowmick** [comment]
Can nay one please answer my question https://stackoverflow.com/questions/53814888/unable-to-create-audit-log-for-associate-object-value-change-with-papertrail
