### ISSUE TITLE
workaround for superclass mismatch for class Version (TypeError)

### ISSUE THREAD

**Issue by talbright** [airblade/paper_trail#267]
Unfortunately, I have other gems in my project that use the name Version, so I get a superclass mismatch error. I realize this isn't really the fault of Papertrail, but is there a workaround? Maybe if Papertrail used namespaces/modules this would alleviate the potential conflict for such a common named class?

Or just use a new classname with less potential conflict, and set the table name explicitly, or even just use a brand new class name like "PaperTrailVersion".

**Comment by danielbecker** [comment]
I am using paper_trail 5.2.3 with rails 3.2.22.5 and have the same problem.

`/Users/db/.rvm/gems/ruby-2.2.6@metriamo-rails4/gems/paper_trail-5.2.3/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:8:in `<module:PaperTrail>': superclass mismatch for class Version (TypeError)
	from /Users/db/.rvm/gems/ruby-2.2.6@metriamo-rails4/gems/paper_trail-5.2.3/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:3:in `<top (required)>'`

Any advice on how to solve is much appreciated.
