### ISSUE TITLE
Duplicate versions created for the same operation

### ISSUE THREAD

**Issue by suan** [airblade/paper_trail#27]
We are having a problem in production where paper trail is creating duplicate version objects, literally only milliseconds apart but otherwise identical, for some operations. What's weird is that I have not been able to reproduce this in development. Have you heard of any problems like this? We're using paper trail 1.1.2 btw.

**Comment by kwent** [comment]
Actually having the same issue with `paper_trail (10.3.1)` and rails `5.2.0`. Two records are created and `created_at` timestamps are identical. 

```irb
PaperTrail::Version.find(1351832).created_at.to_i
=> 1569955962
PaperTrail::Version.find(1351833).created_at.to_i
=> 1569955962
PaperTrail::Version.find(1351832).attributes.reject{|k| k == 'id'} == PaperTrail::Version.find(1351833).attributes.reject{|k| k == 'id'}
=> true
```

Any idea ?

**Comment by mattholtom** [comment]
@kwent I am experiencing the same behaviour (only on certain models) w/ `paper_trail (10.3.1)` and `rails (5.1.7)`.

In my case, like yours, the objects are identical, and have the same created_at timestamp. I see that you had this issue ~6 weeks ago, did you have any luck figuring out what was going on?

Thanks, have a great day!

**Comment by kwent** [comment]
I unfortunately did not and i'm experiencing this issue only on certain models as well

**Comment by mattholtom** [comment]
@kwent Not sure what it was about your comment but it actually helped me figure out my (possibly the) issue, so thank you!

In `app/models/application_record.rb` I had 
`has_paper_trail skip: [:updated_at]`, as I did want to audit all models. 

However, then in `app/models/user.rb` I wanted to trim the audited attributes significantly, so I had again `has_paper_trail skip: [:updated_at, :encrypted_password, :last_sign_in_at, etc. etc. long list of attributes]`, thinking it would overwrite the parent, but it was additive. So there we go, it was being called once by the subclass definition, and again in the parent.

To have my cake and eat it too, after some stackoverflow research I went with:
```
class ApplicationRecord < ActiveRecord::Base
...
  def self.inherited(subclass)
    super
    return if [User].include?(subclass)
    # Enable paper-trail w/ standard options for all classes except User
    subclass.send(:has_paper_trail, skip: [:updated_at])
  end
```

and 

```
class User < ApplicationRecord
...
has_paper_trail skip: [.........]
```

Not sure if this is the issue you were having, but good luck on your journey!

**Comment by kwent** [comment]
Hi @mattholtom. Thanks for answering. I had actually the similar issue but with

```ruby
class MyModel
   include MyConcern
   has_paper_trail
end
```

with 

```ruby
module MyConcern
  extend ActiveSupport::Concern
     has_paper_trail
  end
end
```

Looks like we good now ! Thanks !
