### ISSUE TITLE
attr_accessible with PaperTrail 3 and Rails 4

### ISSUE THREAD

**Issue by mishrarohit** [airblade/paper_trail#279]
I am using PaperTrail from Github (version: 39decb3de446c4aa7c5a0fe3cd196d4262bc5fd4) with Rails 4 and  protected_attributes (1.0.3)

I see [this commit](https://github.com/airblade/paper_trail/commit/a91d56cd741dd2331109c42dfb538099247f2d6e) which adds `attr_accessible` support in PaperTrail - 

But, this is not working for me. I get the following error when I try to create a new instance for a model which uses PaperTrail.

```
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes for PaperTrail::Version: event, whodunnit, object_changes
from /usr/local/opt/rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/protected_attributes-1.0.3/lib/active_model/mass_assignment_security/sanitizer.rb:60:in `process_removed_attributes'
```

I looked around and found this very [old issue](https://github.com/airblade/paper_trail/issues/62) about protected attributes. I modified the resolution suggested there and added a new file.

_config/initializers/paper_trail.rb_

```
module PaperTrail
  class Version < ActiveRecord::Base
    attr_accessible :item_type, :item_id, :event, :whodunnit, :object, :object_changes
  end
end
```

Doing this solves my issue. Looking at the tests, I believe the initializer I added should not be needed. How can I go about testing whether this is an issue in PaperTrail or something specific to my setup?

**Comment by herringtown** [comment]
had this same issue using protected_attributes 1.0.9 / rails 4.2.8 / paper_trail 7.0.3.  Fixed it by adding the following entry into app/models/paper_trail  (which i have in order to add the abstract_class flag)

```ruby
module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern
    attr_accessible :item_type, :item_id, :event, :whodunnit, :object, :object_changes, :created_at
    self.abstract_class = true
  end
end`

**Comment by jaredbeck** [comment]
Greg, looking through our readme, I don't see any mention of `attr_accessible`. Oh wait, there is a [section that says we don't support `protected_attributes`][1].  Hmmm. I know that `protected_attributes` is no longer officially supported (as of the release of rails 5.0) but I think a lot of people may still be using it, so do you want to expand this section, keeping some form of that warning, and adding instructions for `attr_accessible`?

[1]: https://github.com/airblade/paper_trail#5d-protected-attributes

**Comment by herringtown** [comment]
@jaredbeck oops -- yep, I definitely missed that section, but there it is.  Guessing there are still some folks out there that haven't migrated off protected_attributes yet that might get tripped up as well, so expanding hat out a bit probably couldn't hurt...

**Comment by jaredbeck** [comment]
Yeah, I'm thinking that we can still have a some help in our readme for `attr_accessible`, even if we don't officially support it. Go for it! Please open a PR. The example you give above would be a good start.

**Comment by herringtown** [comment]
@jaredbeck PR opened!

**Comment by jaredbeck** [comment]
Closed by https://github.com/airblade/paper_trail/pull/977
