### ISSUE TITLE
Rails 4 not working?

### ISSUE THREAD

**Issue by JacobEvelyn** [airblade/paper_trail#283]
I was previously using the rails4 branch and everything worked great, but I noticed that Rails 4 support has become officially supported so I tried switching to the gem version 3.0.0.beta1. Now, however, I get `undefined method 'has_paper_trail' for #<Class:0x007faf65a81b48 (NoMethodError)` errors. Any thoughts?

If it helps, I'm using a separate versions table for each model.

**Comment by vijaymallya** [comment]
Problem upgrading to model object with PaperTrail.

NoMethodError (undefined method `request' for PaperTrail:Module):
