### ISSUE TITLE
"whodunnit" name

### ISSUE THREAD

**Issue by Silex** [airblade/paper_trail#284]
Hello,

Why not alias/rename `whodunnit` do something less k-rad, like `author` or whatever makes sense. Is that to prevent name collisions?

**Comment by eternalfool** [comment]
Are there any downsides to renaming this?
I was thinking of using 
`info_for_paper_trail` 
instead of using 
`user_for_paper_trail`

and pass in something like 
`
def info_for_paper_trail
    { user: user[:id], user_type: user[:type]}
 end
`
Sorry for replying to an old issue.
