### ISSUE TITLE
updated_at info in the changeset

### ISSUE THREAD

**Issue by jfeltesse** [airblade/paper_trail#291]
Hi,

Following up on the issue I opened on globalize (https://github.com/globalize/globalize/issues/285) I wanted to ask if there was any specific reason to include the updated_at timestamp in the changeset.

Honestly I have a hard time understanding the usefulness of this piece of info in the changeset, seems pretty redundant with the version's own created_at timestamp.

I can only imagine it's a policy to serialize whatever rails marks as a changed attribute so if there's something else please enlighten me!

**Comment by bartoszkopinski** [comment]
Solved by adding this to the `config/initializers/paper_trail.rb` file:
```ruby
PaperTrail::Model::ClassMethods.module_eval do
  alias_method :old_has_paper_trail, :has_paper_trail
  def has_paper_trail(options = {})
    options[:ignore] ||= []
    options[:ignore] << :updated_at
    old_has_paper_trail(options)
  end
end
```
