### ISSUE TITLE
Possible to parse the version states in Paper Trail to return a single column?

### ISSUE THREAD

**Issue by ml242** [airblade/paper_trail#300]
Ideally, I would like to iterate through the versions to get a history of a column, say... price. I do not believe that meets the intention perfectly of this software, but it is quite close.

In my model I have

```
has_paper_trail :only => [:price]
```

And in the console I would like to do something like

```
widget.versions[1][:object][:price]
```

On an each block in Rails I'd have something like:

``` ruby
<% @account.versions.each do | version | %>
  <li><%= version[:price] %></li>
<% end %>
```

Am I overlooking a way do this and have it return plain text, or is this not what the Gem was designed for? 

Regardless, even as a new backend person I appreciate the functionality this gives to rollback states. Very cool and impressive. Thanks for the great gem.

**Comment by owen2345** [comment]
Is there an alternative to this?
```
my_model.history_from_audits_for(:name)
=> [{changes: {name: "Arglebargle"}, changed_at: 2015-05-13 15:28:22 -0700},
{changes: {name: "Baz"}, changed_at: 2014-05-13 15:28:22 -0700},
{changes: {name: "Foo"}, changed_at: 2013-05-13 15:28:22 -0700}]
```
Skip non changed versions

**Comment by jaredbeck** [comment]
There are currently four ways to query the history of a particular attribute.

1. If you are using [postgres json/b columns][1] you can query the history of a specific attribute with the `->` operator. This is the most efficient.

    ```sql
    select object->'name' 
    from versions 
    where item_type = 'User'
      and item_id = ?  
      and object->'name' is not null;
```

2. If you are storing [JSON in a text column][2], you can use the same query if you cast `object::json`, though it is less efficient.
3. If you are storing YAML in a text column (the default) you may want to use a [metadata column][4], [as Ben described above][3].
4. Finally, if you're not able to add a metadata column, you could use ruby to parse the records. This would be, by far, the lease efficient.

As you can see, it is possible to query the history of a particular attribute no matter how it is serialized. So, if someone wants to add this feature to `PaperTrail::RecordTrail`, I'd be happy to review a PR.

[1]: https://github.com/airblade/paper_trail/#postgresql-json-column-type-support
[2]: https://github.com/airblade/paper_trail/#6b-custom-serializer
[3]: https://github.com/airblade/paper_trail/issues/300#issuecomment-29215510
[4]: https://github.com/airblade/paper_trail/#4c-storing-metadata

**Comment by owen2345** [comment]
Great,
Thank you!
