### ISSUE TITLE
Let library consumers use custom before_filter ordering

### ISSUE THREAD

**Issue by vemv** [airblade/paper_trail#301]
paper_trail appends a `before_filter` at an apparently arbitrary order.

In order to work correctly with other plugins that are concerned with the `current_user` method, the paper_trail filters must be appended *after* the filters of those other plugins.

That, of course, is just my particular case (in principle).

So, my need is to tell paper_clip to append its filters in a specific order relative to other filters. I achieved this in a fork I made by:

* grouping the filter-called methods in a single one (called `paper_trail_workaround`),
* disabling the injected before_filter call,
* and then calling `before_filter :paper_trail_workaround` after the other `before_filter` calls

https://github.com/vemv/paper_trail/commit/64242b6e79dad7c08769ca88bccf09c79d5a33cd

While my changes are comprehensible, I intend to keep my paper_clip updated so a fork is not viable.

Please provide an 'official' way to achieve this!

Thank you and congratulations for the excellent work.

Victor

**Comment by rarneson** [comment]
@amnwebmaster Also using Devise, along with a multi-tenancy setup following Ryan Bates' Railscast. I implemented your solution and it seems to be working. I'm actually using an around_filter, but I put it in place of your load_current_site. Thanks!

**Comment by jaredbeck** [comment]
> My current workaround is .. skip_before_action

Glad to hear y'all found a workaround, but I still think this is something we should fix.

> So, my need is to tell paper_clip to append its filters in a specific order relative to other filters.

This has always been a problem with libraries that add callbacks.  CanCan comes to mind.  I've opened a PR which stops adding the `set_paper_trail_whodunnit` callback, giving you the control over the order.

Please take a look at my PR.  I'll close this issue and we can continue the conversation there.
