### ISSUE TITLE
user_for_paper_trail should return an id instead of a user

### ISSUE THREAD

**Issue by dnagir** [airblade/paper_trail#316]
The `user_for_paper_trail` on the controller returns the the `current_user` when available.

I'm not sure why the user (rather than an `id`) should be returned from there because the `whodunnit` column is a string.

This became a problem when I changed the type of `whodunnit` from a string to an integer (so that I can join on the `whodunnit` in SQL queries). As a result, the `whodunnit` column is no longer being saved.

The workaround was to override `user_for_paper_trail`:

``` ruby
# application_controller.rb
#...
  def user_for_paper_trail
    current_user.try(:id)
  end
# ...
```

Either way, `user_for_paper_trail` needs to correspond to whatever type of `whodunnit` is.

Does that make sense?

**Comment by sjobe** [comment]
I believe the documentation should be updated to cover this. It currently says `If your ApplicationController has a current_user method, PaperTrail will store the value it returns in the version's whodunnit column.`. Going by what the documentation said, we ended up having a versions table with the `to_s` representation of the user in some versions' whodunnit value and the user's id in others.

**Comment by batter** [comment]
You're right, looks like the docs need to be updated. I will try to give them an update this afternoon, thanks for pointing that out.

**Comment by sjobe-fighthack** [comment]
:+1: :-)

**Comment by sjobe** [comment]
:+1: :-)

**Comment by batter** [comment]
@sjobe - I just pushed b106aef7c6cf17479359569b22675869e383289f, is that a better / more accurate summary of the behavior?  [Here is the the default method definition for `user_for_paper_trail` to populate it for the record](https://github.com/airblade/paper_trail/blob/v4.0.0.beta2/lib/paper_trail/frameworks/rails/controller.rb#L17).

**Comment by dnagir** [comment]
@batter in [this  commit](https://github.com/airblade/paper_trail/blob/v4.0.0.beta2/lib/paper_trail/frameworks/rails/controller.rb#L17) why are you returning `id` "normally" but the `current_user` again in case of `NoMethodError`??

When do you expect a `NoMethodError` there at all?

That looks even more inconsistent and confusing :(

Seriously, just return `current_user && current_user.id` and let the gem user override the behaviour.

This will raise explicit and obvious error if there's no `current_user` or user has no `id` method.
100% obvious, normal Ruby error without the hacks for AS 3-4.

Why use `try` and `try!` plus the hack of checking the AS version if it's as simple as `current_user && current_user.id`?

It's much easier to look at the method:

```
      def user_for_paper_trail
        return nil unless defined?(current_user)
        current_user && current_user.id
      end
```

than the one in the commit.

And there's no benefit for the complexity of a method.

Also I can understand the check for the existance of `current_user` (`defined?(current_user)`) and that's how it always worked.

But think about this.

99% of use cases we want the versions with `whodunnit`.
So when there's no `current_user` method, I'd rather have an error raised rather than silently NOT storing the current user details with the versions.

Sometimes there's just too much magic for no benefit :)

Just my $0.02.

**Comment by batter** [comment]
@dnagir - simply put, not all `current_user` methods always return an object that will respond to an `id` method, and in those cases `current_user && current_user.id` will throw an error by default with this out of the box implementation for those users, which should be avoided at all costs. This is a simple avoidable issue for a user if they read the documentation in the README regarding how this works.

Also, that is not a recent commit, that has been the implementation since v3.0.1. See #346 for historical context as to why it works the way it does.

**Comment by sjobe** [comment]
@batter yes, the update definitely is a better description of what's happening. thanks!

**Comment by dnagir** [comment]
Ben, curious where did you see the user object that doesn't respond to id?
