### ISSUE TITLE
Sign up for Gittip?

### ISSUE THREAD

**Issue by seanlinsley** [airblade/paper_trail#318]
[Gittip](https://gittip.com) is a site for no-strings-attached, recurring gifts to people and teams you love. @batter I appreciate the work you've put into paper_trail, and I'd love to be able to give you some money via Gittip.

A [team](https://www.gittip.com/about/teams/) would be preferable even if you're the only one on it, though I'd have no problem giving to [you personally](https://www.gittip.com/on/github/batter/).

:heart:

**Comment by jaredbeck** [comment]
> .. I don't work on PaperTrail for monetary purposes, I do it because I enjoy working on it and giving back to the community from which I have benefitted from so much.

:+1:
