### ISSUE TITLE
Losing connection ActiveAdmin because it's trying to load all record on versions

### ISSUE THREAD

**Issue by raulsouzalima** [airblade/paper_trail#322]
Hi,

It's not a bug actually, I'm using activeadmin with paper_trail in a project. I've a Business Model that I'm tracking with has_paper_trail, but on admin, when I try to access the Business list, it's losing connection with the mysql, because it tries to load all record on versions.

I couldn't find a way to fix it, is there anything I could do?

Tks

![console](https://f.cloud.github.com/assets/10306/1984471/b15456ea-842c-11e3-8da2-1304d2439405.jpg)

**Comment by jaredbeck** [comment]
> It is not a bug in this project and not a bug in Active Admin. The appropriate solution here is to customize your filters. Read the documentation. (http://www.activeadmin.info/docs/3-index-pages.html)

Given Evadne's comment (thanks!), and the lack of activity after it (15 months) I'm going to close this issue.  Please let us know if it's still an issue with up-to-date versions of paper_trail and (a properly-configured) activeadmin.

**Comment by seanlinsley** [comment]
https://github.com/activeadmin/activeadmin/issues/2692 is the ticket to track if you want to be notified when Active Admin is capable of handling large datasets by default. Someone recently volunteered to work on it, so one of you might like to help test once there is something to try out :octocat:
