### ISSUE TITLE
Changes to the Rails updated_at column don't appear in version changesets

### ISSUE THREAD

**Issue by brightbytes** [airblade/paper_trail#323]
If I update some Rails model attribute then Rails will perform the update I requested and also update the updated_at field for that model.

However, the PaperTrail version changeset for the change doesn't contain a hash key `updated_at: [<pre_value>, <post_value>]`.

PaperTrail does correctly record both :created_at and :updated_at when a record is initially created.  The bug only appears with subsequent attribute updates.

I'm using Rails 3.2.16 with Ruby 1.9.3p429.

And yes, I do know I can reconstruct the approximate updated_at from the created_at field on the Version.  Still, it would be nice if the changeset record recorded the change.

**Comment by batter** [comment]
`v4.0.0` will now use `after_` callbacks for all version generation, so that should address the issue you see here. Feel free to give `v4.0.0.beta2` a whirl and that should fix your issue.  (See #375 and #374 for more details)
