### ISSUE TITLE
Support for tracking batch updates

### ISSUE THREAD

**Issue by aserafin** [airblade/paper_trail#337]
I have a case when I'm updating bunch of records using `update_all` for performance reasons. I would still want to be able to keep track of these changes (author and whats changed). 

Maybe PaperTrail could expose static method on model, like: `User.record_changes(ids = [], changes = {})` that could be called by developer manually?

I think this is pretty common issue and may be worth resolving - I'm open to suggestion and eager to write some code and send pull request once some consensus will be reached.

**Comment by batter** [comment]
I know it's late but if you still want to make a PR we can try to get it merged in prior to the `4.0.0` release..

**Comment by jaredbeck** [comment]
Since there hasn't been any activity on this, maybe it makes sense to postpone to a 4.1 release?

**Comment by batter** [comment]
Agreed.  Still open to contributions / suggestions for how to accomplish this.

**Comment by jaredbeck** [comment]
>> I'm open to suggestion and eager to write some code and send pull request
>>
> I think this is a good idea .. if you want to submit a PR, that would be great.
>

Again, I think this would be a good feature, but given the lack of activity, my preference is to close the issue. If anyone wants to implement this in the future, please open a PR, thanks!

**Comment by mpapis** [comment]
+1 for adding this functionality since I just had a case that would make use of tracking batch updates

**Comment by rskelley9** [comment]
+1 as well.

**Comment by kikikiblue** [comment]
+1 !!

**Comment by Abaxial** [comment]
+1 still.

**Comment by renadshaaban** [comment]
+1

**Comment by yuri-karpovich** [comment]
so.... +1 :)

**Comment by wscourge** [comment]
+1

**Comment by pk8189** [comment]
+1

**Comment by dapx** [comment]
+1

**Comment by MaicolBen** [comment]
I think we should file a new issue since this one got ignored after getting closed

**Comment by wscourge** [comment]
@MaicolBen will you please do that and link it here?
