### ISSUE TITLE
How to not switch on last saved version automatically?

### ISSUE THREAD

**Issue by kronos** [airblade/paper_trail#338]
Assume I have a blog and posts in it is under version control with paper_trail.
After I've done a post I would like to save it (not publish) and see it in my admin's sandbox and if everything is ok I'll go ahead and publish it.

How I can implement this two features (save and publish) with paper trail? After every save the gem "activate" last version but I don't want it to do this.

Flag like "published" in post is a bad solution because, for example, some time later I will edit my post (create new version) and I do not want it to go live before I publish it.

**Comment by jaredbeck** [comment]
How about adding a `published_at` timestamp to your [version metadata][1]?  The published record would be the one with the most recent `published_at` timestamp.

```ruby
PaperTrail::Version.
  where(item_type: "Post").
  order(published_at: "desc").
  limit(1)
```

Given the lack of activity here (before this comment, 16 months) I will close this issue.

[1]: https://github.com/airblade/paper_trail#storing-metadata
