### ISSUE TITLE
Problem upgrading to paper_trail v3 with functional tests when PaperTrail is not enabled globally

### ISSUE THREAD

**Issue by gamov** [airblade/paper_trail#341]
After bundling the new gem (v3), I had to change a Custom Version Class from

``` ruby
class ItemVariantVersion <  Version
```

to

``` ruby
class ItemVariantVersion <  PaperTrail::Version
```

When I executed my functional tests creating versions via paper_trail, they complained that none of the versions were created when they should have. If I launch those failing tests one by one, they pass. If I switch PaperTrail.enabled = true globally, they work again.
All those failing tests are encapsulated in a with_versioning block as described in the read_me.
It seems that the switching mechanism is not working properly under v3. What would be the next step of the investigation?

PS: Environment is Rails 3.0.20 / minitest

**Comment by gamov** [comment]
Hello @batter,
I'm so sorry, I've just realised that I've never said thank you for your thorough explanation. I used your surefire way but somehow thought I've reported back… 

Thank you again!

**Comment by vijaymallya** [comment]
NoMethodError (undefined method `request' for PaperTrail:Module):
