### ISSUE TITLE
Feature Request: Mongoid ORM support

### ISSUE THREAD

**Issue by aziz** [airblade/paper_trail#35]
mongoid support simple versioning but it's far from a usable solution at the moment and I do prefer the paper_trail way of version management. Is it possible to add support for mogoid beside active record? something like orm_adapter (https://github.com/ianwhite/orm_adapter) might be handy

**Comment by Radagaisus** [comment]
Hi there! The year is 2015. Does Paper Trail works with Mongoid? :cake:

**Comment by gazsp** [comment]
+1 :-)

**Comment by jaredbeck** [comment]
> Does Paper Trail works with Mongoid?

No. PaperTrail is tightly coupled to ActiveRecord. See the discussion in https://github.com/airblade/paper_trail/issues/308 for reasons why breaking that coupling would be a huge undertaking.

Locking issue to prevent "+1" comments.
