### ISSUE TITLE
Destroy Behavior

### ISSUE THREAD

**Issue by tpendragon** [airblade/paper_trail#364]
I may be doing something wrong, but in combining @radar 's [paranoia](https://github.com/radar/paranoia) and this I came to discover that, contrary to spec, it looks like the destroy hook actually saves the state the object was in AFTER the destroy runs. This results in strange timestamps in the version history as well as a deleted_at for Paranoia.

This seems to be a result of https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/has_paper_trail.rb#L80 (record_destroy being called as an after_destroy hook - probably to avoid creating a version record if it fails to be created.) I've patched this locally by setting an instance variable to the result of #item_before_change and utilizing that in record_destroy - thoughts?

**Comment by webhat** [comment]
In case somebody stumbles on this, there is no version `3.1.0`
