### ISSUE TITLE
Updating versions when schema changes

### ISSUE THREAD

**Issue by siassaj** [airblade/paper_trail#402]
When table names or attributes change we need to have a way to maintain coherence with version records. Not just item_type, but also the serialised attributes in the object attribute. Since it's a string it's non trivial and requires special SQL in many cases.

I've ended up doing it this way because I didn't want to write that SQL, we aren't sure what db we'll end up with in prod. It's far from ideal, this sort of code ought to be in a tool with paper_trail, specifically to facilitate migrations.

Is this in the works, or does someone need to get started on it?

``` ruby
namespace :db do
  namespace :data_migration do
    namespace "20140726211253_rename_refill_report_to_service_report" do

      task :set_model do
        class PaperTrail::Version < ActiveRecord::Base
        end
      end

      desc "Rename 'RefillReport' item_types to 'ServiceReport'. PaperTrail::Version records have a polymorphic item relation."

      task up: :set_model do
        PaperTrail::Version.where(item_type: "RefillReport").update_all(item_type: "ServiceReport")
        PaperTrail::Version.where("item_type = 'Refill' OR item_type = 'Count'").each do |v|
          if v.object.present?
            v.update_attributes(object: v.object.gsub(/refill_report_id:/, "service_report_id:"))
          end
        end
      end

      desc "Rename 'ServiceReport' item_types to 'RefillReport'. PaperTrail::Version records have a polymorphic item relation."

      task down: :set_model do
        PaperTrail::Version.where(item_type: "ServiceReport").update_all(item_type: "RefillReport")
        PaperTrail::Version.where("item_type = 'Refill' OR item_type = 'Count'").each do |v|
          if v.object.present?
            v.update_attributes(object: v.object.gsub(/service_report_id:/, "refill_report_id:"))
          end
        end
      end

    end
  end
end
```

**Comment by jaredbeck** [comment]
Closing after three years of inactivity.

**Comment by siassaj** [comment]
yeah... i forgot about this, sorry

**Comment by jaredbeck** [comment]
> yeah... i forgot about this, sorry

No worries! I enjoyed reading your discussion with Ben. It sounds like a difficult problem to solve generally, but interesting to think about.

**Comment by robwise** [comment]
Sorry to comment on an old issue, but I just had this one come up. 

On it's own, this isn't a showstopper. 

But, if I combine this scenario with the rails_admin integration, the whole rails_admin interface 500s if I ever change a model name because PaperTrail is referencing an uninitialized constant.

Maybe it doesn't require a code change, but some mention in a "Gotchas" section of the README?
