### ISSUE TITLE
Is it possible to get the hash of the object?

### ISSUE THREAD

**Issue by hendricius** [airblade/paper_trail#411]
I didn't find anything in the code that already deserializes the object of each version for you. Instead I had to manually deserialiize the version.object. Is that correct that there is no code yet to do that for you?

Else I will create a quick pull request.

Awesome gem!

**Comment by batter** [comment]
I'm closing this for now since I'm pretty sure this isn't a bug, and you never followed up on this. Feel free to ask if you have any other questions though.

**Comment by hendricius** [comment]
Thanks @batter
