### ISSUE TITLE
Rails 5 is removing `serialized_attributes` without replacement

### ISSUE THREAD

**Issue by thetron** [airblade/paper_trail#416]
Hey papertrailers,

We're currently building a Rails 4.2 app with paper_trail (love it, btw), and getting the following warning:

```
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will
be removed in Rails 5.0.
```

Which I noticed paper_trail calls several times in `has_paper_trail.rb`. 

I'm sure you're aware of it already - but just wanted to flag it. I did have a little poke around to see if there was an obvious solution - but I couldn't come up with one. Happy to put together a PR, if someone could offer some guidance.

**Comment by cnk** [comment]
Thanks. The beta appears to work fine on my rails 4.2 project. I needed run `rails generate paper_trail:install --with-associations` to get the new table and column and then add `require 'paper_trail/frameworks/rspec'` to spec/rails_helper.rb

**Comment by yule** [comment]
Beta works fine for me on 4.2. as same as @cnk : had to run generate and require to spec_helper

**Comment by klacointe** [comment]
Rails 4.2 and paper_trail 4.0.0.rc2 : :ok: 
Thanks :kissing_heart:

**Comment by jasdeepsingh** [comment]
Rails 4.2 with paper_trail 4.0.0.beta2 :+1:

**Comment by SDEagle** [comment]
after silencing the serialized attributes warning I just noticed, that there was also another similar warning:
```
DEPRECATION WARNING: `#reset_updated_at!` is deprecated and will be removed on Rails 5. Please use `#restore_updated_at!` instead.
```

**Comment by batter** [comment]
@SDEagle - what version of PaperTrail are you using?  That message should not appear in `4.0.0.beta2` and higher.

**Comment by SDEagle** [comment]
latest stable

**Comment by stephenbaidu** [comment]
@sgrif, I can't seem to find the "type objects" you mentioned. Some links would be helpful. Thanks.

**Comment by sgrif** [comment]
https://github.com/rails/rails/tree/master/activerecord/lib/active_record/type

**Comment by stephenbaidu** [comment]
Thanks
