### ISSUE TITLE
undefined method `changeset' for #<Version

### ISSUE THREAD

**Issue by atstockland** [airblade/paper_trail#444]
v3.0.6, ruby 2.1.5p273

I see this was addressed in issues #154 && #249.  Neither of those issues seemed to address my problem.  Ive been using changeset successfully, but recently (not sure if it was the 3.0.6 update or ruby update)...I have been getting the error "undefined method `changeset' for #<Version".  I have a versions/show view. 

@version = Version.find(params[:id])

<% if @version.changeset.present? %>
  <code>
      <% @version.changeset.reject { |a, b| ["created_at", "updated_at"].include?(a) }.each do |k,v| %>
          <% if @version.event == "create" %>
            <%= k %>: <%= v[1] %>
          <% else %>
            <%= k %> - from: <%= v[0] %> to: <%= v[1] %><br>
          <% end %>
      <% end %>
  </code>
<% end %>

As you can see the changeset is being called on Version.  Any ideas why I am now getting the error?

**Comment by sbpipb** [comment]
@atstockland  hi, i'm experiencing the same problem, what's the resolution for this issue?
