### ISSUE TITLE
changeset not work

### ISSUE THREAD

**Issue by piya23300** [airblade/paper_trail#446]
I use rails 4.1.8 , paper_trail 3.0.6

event = 'update'
object_changes = "--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\nstatus_id:\n- 1\n- 2\n" 
when I call object.versions.last.changeset, it returns {}

Cloud you help me?

**Comment by piya23300** [comment]
@batter Thank you to alert me haha I forget it ^^

I tests it,  I found error
```
NameError: undefined local variable or method `version_class_name' for #<Class:0x007f8152ceb578>
```

I think because my class use STI

```AAA::BBB::CCC``` class that use paper_trail
but ```object.version.last.item_type = AAA::BBB```
```AAA::BBB``` class doesn't want use paper_trail
this reason of error

and then
I changed ```object.version.last.item_type = AAA::BBB``` to ```object.version.last.item_type = AAA::BBB::CCC```

```object.versions.last.changeset``` it work!

I try to fix it , I found cause from ```belongs_to :item, :polymorphic => true```
http://stackoverflow.com/questions/21886440/combine-sti-and-polymorphic-with-rails-4

When I new version object ```object.versions.new```
```item_type``` alway sets  ```self.class.base_class.name```

I can't solve it.
Cloud you help me? please....

**Comment by batter** [comment]
Does #362 help you at all? I'll have to take a closer look at this and try to generate a test case. If you can provide a dummy app or PR w/ failing tests that would help a lot.

**Comment by batter** [comment]
This is a dup of #404, closed in favor of that one, clearly there is an issue when PaperTrail is used in conjunction with STI that needs to be addressed.
