### ISSUE TITLE
Reverting has_many (using v4.0.0.beta1)

### ISSUE THREAD

**Issue by rikkipitt** [airblade/paper_trail#457]
Hi guys,

I'm playing with the latest version of paper_trail and using Ryan Bates versioning technique for reverting changes - http://railscasts.com/episodes/255-undo-with-paper-trail

```ruby
class VersionsController < ApplicationController
  def revert
    @version = PaperTrail::Version.find(params[:id])
    if @version.reify(:has_many => true)
      @version.reify(:has_many => true).save!
    else
      @version.item.destroy
    end
    link_name = params[:redo] == "true" ? "Undo" : "Redo"
    link = view_context.link_to(link_name, dashboard_revert_version_path(@version.next, :redo => !params[:redo]), :method => :post)
    redirect_to :back, :notice => "Undid #{@version.event}. #{link}"
  end
end

```

I have a slight issue that I can't figure out just yet from the new docs... Example:

If I create a Book which has_many :pages and edit a page in a nested form a few times. When I revert the parent book to it's last version, it doesn't reify the last page, but the original one... is that expected?

I assume I have to do some kind of transaction or autosave tweak?

Thanks for any advice you may have!

Rikki

**Comment by batter** [comment]
Yes, that is the expected behavior. It attempts to restore the associated objects as they were at the point in time the version was generated. So if you don't want that behavior, then you can just skip passing in the `:has_many => true` option into the `reify` method.

**Comment by rikkipitt** [comment]
Thanks @batter, is there a way of reverting to the last relational change (if that makes sense)? I appreciate this is quite a new feature. Cheers for the advice!

**Comment by batter** [comment]
Sorry I'm not sure I'm understanding what the question is exactly, can you give me an expanded explanation of the example with the book and the pages and what you're trying to accomplish?
