### ISSUE TITLE
Has And Belongs To Many Support

### ISSUE THREAD

**Issue by awesomebambam** [airblade/paper_trail#466]
This is not a bug but a question.
I am able to restore has_many associations to a previous version but I am looking for a way to restore 'has and belongs to many' associations for an object. 

Does paper trail support it? the only way I can think of as of now is to add column which stores the ids of habtm relationship. Is there an elegant way for this?

**Comment by batter** [comment]
@bli - did the work that was merged from #439 address this?  I don't believe it did,and I think it would be even more complex, but I'm not certain?

**Comment by bli** [comment]
No, I don't think it did either. But I think a Has And Belongs to Many association can be easily converted to a Has Many Through one.

**Comment by batter** [comment]
Good point, @muzamil, though not quite as clean, you could use a join table and use `has_many :through`, which is supported for reification.

**Comment by bli** [comment]
Exactly, and if I am not wrong, the join table is already there if you are using Has And Belongs To Many. You only need to add a model class for it and change the association type.

**Comment by muzamil** [comment]
Yes, Sounds good but as of now we had like 4-5 habtm relationships and we were not looking to change habtm to has many through.  
So we took the route of 
1. Adding an additional column to 'versions' table  
2. Whenever a version record gets created for an object, we were updating the new column with the ids of habtm relationships. 
3. While retrieving the version, we were constructing the habtm relationship back.

**Comment by genius-devil** [comment]
The thing I am addressing in Issue #530 is having a has many through relationship from table A to C through B, and then having a one to many relationship between table B and C.

In this case, the intermediate through model will not be having foreign keys of both the tables as in a proper many-many relationship and the existing code checks for the foreign key of the association in the intermediate through model which can't be there in a One to Many Relationship in my Example.

**Comment by jaredbeck** [comment]
I'm going to go ahead and close this because we're really close to merging https://github.com/airblade/paper_trail/pull/771 which implements HABTM support.
