### ISSUE TITLE
Ignore isn't working the way I expect it to

### ISSUE THREAD

**Issue by walterdavis** [airblade/paper_trail#469]
I have set up paper_trail to ignore all changes except a Paperclip attachment, so that any of the metadata can change (title, description) without forcing a new version, but if a new version of the image is uploaded, the new version is created. No matter what I do, I can't seem to get it to ignore non-image changes. Could this be related to the fact that I also have a meta key on the paper trail?

~~~
  has_paper_trail ignore: [:user_id, :project_id, :title, :description, :approval_status, :genre, :created_at,
    :updated_at, :key, :version_number], :meta => {:version_number => :version_number, :key => :key}
~~~

Any suggestions about this?

**Comment by batter** [comment]
What versions of PaperTrail and ActiveRecord are you using?

**Comment by walterdavis** [comment]
PaperTrail 3.0.6 and ActiveRecord 4.1.8. 

Walter

**Comment by batter** [comment]
So what exactly is the issue?  It is generating new versions when you don't expect it to?

**Comment by walterdavis** [comment]
Yes, it makes a new version every time I save, even when the only thing (I think) that should trigger a version is me uploading a different image to the model. I change the name or another of the ignored attributes, I get a new version.

**Comment by batter** [comment]
Can you try taking `:created_at` and `:updated_at` out of your ignored attributes list and seeing if that fixes the issue? It shouldn't be necessary to have those.

**Comment by walterdavis** [comment]
They were added after I noticed the problem. The only thing I can think may be affecting this is the version_number method, which counts the number of versions and adds 1. When you choose to ignore a version, does it exist? In the life-cycle of the object, if you make (ignored) changes to the object, then call versions.length (before you save) does the version count increment before those ignored fields are discounted? Or does the ignore code simply avoid counting those attributes in its calculation of what version we are currently in before anything else is considered? I guess I need to read the source and see how you figure these out.

**Comment by batter** [comment]
Apologies for delayed response, but if you can provide a dummy app or template, I can probably give you a hand debugging this better.  

But no, a version doesn't get built until after the fact of the update, and it will only start being built [if the object has "changed notably"](https://github.com/airblade/paper_trail/blob/3.0-stable/lib/paper_trail/has_paper_trail.rb#L272), in other words, if an attribute that is not being ignored/skipped has changed.

And you would only need to ignore the timestamp attributes if you are making explicit calls to update those attributes, and those only, like this:

```ruby
ModelKlass.create!(created_at: Time.now)
# or
model_instance.update_attributes!(updated_at: Time.now)
```

**Comment by walterdavis** [comment]
Okay, I will go back through my branches and find a version that still has this on it (I had to move ahead, and dug back in time to vestal_versions to get things working for my client). I'll try to put something together for you tonight or tomorrow.

**Comment by batter** [comment]
Closing this for now since I never heard back from you @walterdavis, if you do end up digging up your project and you can provide a bit more information, feel free to ping me/us again and we'll see if we can fix your problems.
