### ISSUE TITLE
ActiveModel::MissingAtrributeError can't write unknown attribute 'updated_at'

### ISSUE THREAD

**Issue by bytheway875** [airblade/paper_trail#472]
Hello!

I'm getting this ActiveModel::MissingAttributeError when I try to create an object that has paper_trail on the model. A little background, I'm attempting to create the record through nested attributes on an associated model. I even added ignore: [:updated_at] when I set up has_paper_trail in the model, but I get the same error. 

When I remove the has_paper_trail line in the model, it creates the record no problem, so I'm pretty sure its an issue with the way i have paper_trail set up.

**Comment by batter** [comment]
Did you solve your issue?

**Comment by bytheway875** [comment]
I upgraded to 3.0.6 and it doesnt seem to be an issue anymore, but I'm going to keep an eye on it.

**Comment by batter** [comment]
Great, yes, `3.0.6` contains a fix for the `ignore` option when the gem is used with ActiveRecord 4

**Comment by bytheway875** [comment]
fantastic, thank you!
