### ISSUE TITLE
Calling `reify` on the first version returns `nil`

### ISSUE THREAD

**Issue by mhuggins** [airblade/paper_trail#475]
I'm trying to use this plugin to track a revision history, but the actual *object history* does not seem to line up with the *version history*.  Take this simple example:

```ruby
person = Person.create(first: 'John', last: 'Smith')
 => #<Person id: 1, first: "John", last: "Smith">

person.versions.count
 => 1

version = person.versions.last
 => #<PersonVersion id: 1, ... , object: nil, object_changes: "---\nfirst:\n- \n- John\nlast:\n- \n- Smith\n">

version.reify
 => nil
```

If I then update the object, I can see the changes, but `reify` seems to return the `prior` version.  In other words, it seems like `reify` is only working when `event` is "update", but not "create".

```ruby
person.update(first: 'Joe')
 => #<Person id: 1, first: "Joe", last: "Smith">

person.versions.count
 => 2

version = person.version.last
 => #<PersonVersion id: 1, ... , object: "---\nid: 1\nfirst: John\nlast: Smith\n", object_changes: "---\nfirst:\n- John\n- Joe\n">

version.reify
 => #<Person id: 1, first: "John", last: "Smith">
```

Is this the intended behavior?  If I'm just trying to show a history of changes in my app, should I simple ignore the "create" and "delete" action, tracking only "update" events?

**Comment by batter** [comment]
Yes, that is the intended behavior, please read the README, the plugin is designed not to persist a copy of the current version, since it is already persisted in the DB as the live copy

**Comment by mhuggins** [comment]
I think the issue I'm trying to solve (diffing versions) will just need me to record `on: :update`.  Please ignore this issue. :)

**Comment by joshuapinter** [comment]
I think this is a valid question. Essentially, 

**How do you get the original object?**

Doing `item.versions.first.reify` returns `nil` so the best way I could find is this: 

`item.versions.second.reify` 

But that doesn't work when the object doesn't have any changes. So you need a check in there: 

`item.versions.second&.reify || item`

This looks for the second version and if it's present will call `reify`, which returns the original object. If it's not present it will simply return the item itself.

**Comment by joshuapinter** [comment]
I created a Issue / Feature Request to add a method called `original_version` that easily returns the original version: 

https://github.com/paper-trail-gem/paper_trail/issues/1204

We forked the library and did it in our own fork. Works great. Happy to write tests and whatever else is necessary to incorporate this into the core library itself.

**Comment by ngouy** [comment]
It's hacky, but I wanted that + the fact to have the LIVE version of an object in the version table too (because I needed to reference the version_id in another table, and I needed it to reference the LIVE version)

so here is how I did (It's hacky)
```
class MyModel
  has_paper_trail on: [:touch]
  after_save { touch }
end
```
That way:

- you have the created version in your versions
- you have the live version in your versions
- BUT you cannot leverage the version#event anymore (it will always be "touch")
- and it probably have some side effect that I can ignore in my use-case but maybe not yours
