### ISSUE TITLE
PaperTrail breaks rails/rake commands...

### ISSUE THREAD

**Issue by rikkipitt** [airblade/paper_trail#477]
Hi guys, I'm using rbenv and when I include paper_trail 3.0.6 in my Gemfile I get the following errors in the command line using and rails or rake command. Any ideas?

Cheers, Rikki

E.g.

```
rake --version
 
/Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/paper_trail-3.0.6/lib/paper_trail/frameworks/sinatra.rb:35:in `<module:PaperTrail>': undefined method `register' for Sinatra:Module (NoMethodError)
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/paper_trail-3.0.6/lib/paper_trail/frameworks/sinatra.rb:3:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/paper_trail-3.0.6/lib/paper_trail.rb:129:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
  from /Users/username/.Trash/test_test 21.39.36/config/application.rb:15:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:82:in `preload'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/username/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from -e:1:in `<main>'
```

**Comment by rikkipitt** [comment]
This is on Rails 4.2.0 by the way...

**Comment by batter** [comment]
Are you using [Sinatra](https://github.com/sinatra/sinatra/) as part of your bundle for some reason?  It looks like what is happening is [this line](https://github.com/airblade/paper_trail/blob/v3.0.6/lib/paper_trail/frameworks/sinatra.rb#L35) is triggering an error, but it shouldn't be invoked at all in a normal Rails app, since `Sinatra` wouldn't be part of the object namespace..

**Comment by batter** [comment]
What happens when you run `gem list sinatra`?

**Comment by batter** [comment]
Weird, I just attempted to reproduce it on my local with an app that had Sinatra as part of it's bundle and was unable to do it.  Could be an issue w/ RBenv or Ruby 2.2.. I was using RVM and Ruby 2.0.0

**Comment by rikkipitt** [comment]
Hi @batter thanks for looking into this for me. I think I've figured it out though... another one of my dependencies is liveeditor/draftsman (which is based off paper_trail and has a Sinatra dependency too).

I reordered the two gems in my Gemfile to place paper_trail first, then draftsman. This alleviated the problem.

**Comment by batter** [comment]
Good to know, thanks for the update!

**Comment by batter** [comment]
Interesting gem there [draftsman](https://github.com/liveeditor/draftsman), looks very similar to PaperTrail :wink:, I guess the author stated it was cloned from PaperTrail at one point and modified from there...

So the issue appears to be that [this module in Draftsman](https://github.com/liveeditor/draftsman/blob/0.3.1/lib/draftsman/frameworks/sinatra.rb) has a base namespace of `Sinatra`, which is inadvisable, since the module is actually part of the `Draftsman` library, and not the `Sinatra` library.  See #277 for more details as to why that can be an issue.

**Comment by rikkipitt** [comment]
Good catch there. Maybe I should inform @chrisdpeters about it...

I'm looking to develop an extension using PaperTrail and/or Draftsman for [rails_admin](https://github.com/sferik/rails_admin) to allow users to create and manage draft records in CMS area. Needs a bit more thought and planning though yet!

**Comment by batter** [comment]
I just did actually: liveeditor/draftsman#9, hopefully will help them.

**Comment by rikkipitt** [comment]
Ah brilliant, well done Ben!
