### ISSUE TITLE
Manual versioning?

### ISSUE THREAD

**Issue by marnen** [airblade/paper_trail#481]
I have a use case where I don't want versions to be created on every update (at least for the time being), but only when I call `touch_with_version` on the object. I would think that `has_paper_trail on: []` would make this happen, but it doesn't seem to work: I get automatic versions on every update. What am I doing wrong?

FWIW, I'm using paper_trail 3.0.6 with Rails 4.2 and Ruby 2.2.0.

**Comment by marnen** [comment]
Ah, I see what's going on. `on: []` is treated as if the `:on` key weren't there. I'll submit a pull request to fix this.

**Comment by marnen** [comment]
Hmm, this may be harder than I thought; see my branch at https://github.com/marnen/paper_trail/tree/handle-on-nothing-correctly. I was able to get `on: []` to turn off all automatic versioning, but now `touch_with_version` doesn't create a version. Help?

**Comment by batter** [comment]
Why not just do `has_paper_trail on: :destroy`?

**Comment by marnen** [comment]
How will that help?

**Comment by batter** [comment]
It will only generate versions when a record is destroy, and if you want to workaround that / eliminate those records, you could put something like `after_destroy { versions.last.delete }` as a callback on the record or something. I know it's not perfect, but I think it will server your purposes.

With `4.0.0` I'm going to work on something that allows for easier manual versioning and / or versioning upon association changes only.

**Comment by marnen** [comment]
That's not my use case. I don't want to generate versions when a record is destroyed; rather, as I said above, I want to record snapshots of a record's state at particular times of my choosing (not necessarily coincident with an update).  So really what I need is `on: []` and some sort of `create_version!` method -- either that or custom versioning events. 

(Actually, default settings and `touch_with_version` would work, but would give me far more versions than I need, at least at this stage of the project.)

**Comment by marnen** [comment]
Pull request #500 should implement what I'm talking about.
