### ISSUE TITLE
ActiveRecord::SerializationTypeMismatch from #version_at

### ISSUE THREAD

**Issue by matiaskorhonen** [airblade/paper_trail#482]
Calling `#version_at()` on a model instance (which has PaperTrail enabled for it) raises a `ActiveRecord::SerializationTypeMismatch` exception.

Confusingly the exception doesn't seem to be raised for all times so, for example, it will blow up with the `created_at` time but work with `Time.now`.

The model has some serialized attributes, so it's probably related to that?

* Ruby 2.2.0
* Rails 4.2.0
* PaperTrail 3.0.6, 4.0.0.beta2, and HEAD (4ced77bdad5dc813a123a6bc40e3cd291181886a)

Backtrace (excluding the application frame): https://gist.github.com/matiaskorhonen/8dd0bb495ac56d173040

**Comment by batter** [comment]
Did you explicitly [enable serialized attributes?](https://github.com/airblade/paper_trail#serializedattributes-support). You will need to do that for full serialized attribute support with PaperTrail 4.x (that option doesn't exist with 3.x).

The other thing you may want to take a look at is #331.

You may also want to try [setting your serializer as `PaperTrail::Serializers::JSON`](https://github.com/airblade/paper_trail#using-a-custom-serializer), as JSON seems to be more efficient and smooth at serialization than YAML for some reason.

**Comment by matiaskorhonen** [comment]
Oh thanks, that solved the issue.

**Comment by batter** [comment]
Which part exactly solved it?

**Comment by matiaskorhonen** [comment]
Enabling serialized attributes worked.
