### ISSUE TITLE
Custom classes & Rails' console reload!

### ISSUE THREAD

**Issue by lacco** [airblade/paper_trail#483]
I just updated to PaperTrail master/ 4.0.0.beta2, added ```PaperTrail::Rails::Engine.eager_load!``` to ```config/initializers/papertrail.rb```, and now I get the following error when using Rails' console in development:

    > PostVersion.first
    => #<PostVersion id: 7 ...
    > reload!
    > PostVersion.first
    PG::UndefinedTable: ERROR:  relation "versions" does not exist

**Comment by batter** [comment]
I'm actually not familiar with the `reload!

**Comment by batter** [comment]
I'm actually not familiar with the `reload!` method. What do you use it for?

Also, does it return `true` or `false` from the `reload!` method? And did you try dropping in `PaperTrail::Rails::Engine.eager_load!` after you executed `reload!`?

**Comment by lacco** [comment]
I am using ```reload!``` from time to time to play around with local changes and test them in the console immediately without reopening it (in my current case I was debugging performance issues in my application with papertrail's ```reify``` method).

Calling ```PaperTrail::Rails::Engine.eager_load!``` after ```reload!``` didn't help. What does help is to resetting ```self.abstract_class = true``` as done in my initializer. I have no clue why this is causing in issue - as far as I know ```reload!``` only reloads the application's code and not the code from gems...

> PostVersion.first
=> #<PostVersion id: 7 ...
> reload!
=> true
> PostVersion.first
PG::UndefinedTable: ERROR:  relation "versions" does not exist  
> PaperTrail::Rails::Engine.eager_load!
 => ["../lib/paper_trail/frameworks/active_record/models"] 
> PostVersion.first
PG::UndefinedTable: ERROR:  relation "versions" does not exist  
> PaperTrail::Version.module_eval do; self.abstract_class = true; end
=> #<PostVersion id: 7 ...

**Comment by lacco** [comment]
I just saw this error outside of the Rails console during a page load: I opened a page that loads a ```PostVersion``` in development mode and then edited a file (e.g. adding some code to a controller). When I now reload the page, I get the ```PG::UndefinedTable: ERROR:  relation "versions" does not exist``` exception.

Could somebody try to reproduce my issues with ```reload!```? If I am the only one experiencing this, I'll dive into my code and try to find out the reason for this behavior.

**Comment by lacco** [comment]
Okay, it seems that the application itself must cause the problems. I created a new app with the same gems and initializers, and I can't reproduce the issue there. I can't figure out what else might cause these issues, so I'll just create the ```versions``` table and just hope that this will fix all problems. I close the issue for now because it seems it's nothing papertrail can solve...
