### ISSUE TITLE
versions association set order to "DESC"

### ISSUE THREAD

**Issue by gurgelrenan** [airblade/paper_trail#489]
I have been searching for a way to get for example: ```Widget.versions.order("created_at DESC")``` and not the default ```ASC``` as I see in the code on https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/version_concern.rb#L77

However, I didn't found a way to overwriting this. For while I'm using the ```reverse``` method from ruby (http://stackoverflow.com/questions/23251749/default-sort-versions-with-papertrail?answertab=active#tab-top), but this is not the best way to do this.

How can I do this better?

**Comment by batter** [comment]
Please see #448

**Comment by gurgelrenan** [comment]
Thanks @batter
