### ISSUE TITLE
Attempting to set up paper trail to debug some issues (from master)

### ISSUE THREAD

**Issue by dvito** [airblade/paper_trail#490]
Getting these Rspec failures when running.

I've created a mysql and sqlite database.  I've done migrations and both.  Now from the root directory, when I run 'rspec', I get some transient errors.

I'm just trying to figure out if there is a configuration issue or perhaps its just a known issue:

If master is not the preferred branch for this, which should I be using?

Errors here:
![screen shot 2015-02-25 at 10 12 21 am](https://cloud.githubusercontent.com/assets/1225922/6373251/7754c396-bcd7-11e4-8a48-0c695a6663cf.png)

**Comment by batter** [comment]
What version of PaperTrail are you rolling? PaperTrail 3.x has a [test helper that needs to be utilized](https://github.com/airblade/paper_trail/tree/3.0-stable#testing) when using the gem within RSpec

**Comment by dvito** [comment]
I meant running the rspec tests in the gem directly on master for this projects directory.

I could be confused though... that is a distinct possibility.

**Comment by batter** [comment]
Not sure what the issue is. I haven't seen this when I run the test suite, and the tests are all passing on Travis CI, so I would recommend recreating your DB's and trying the tests again, as if you look at those #'s they are of by 1 nanosecond (or some tiny fraction of the timestamp).

**Comment by dvito** [comment]
Yeah, I was really hoping it might've just been something you've run into before / seen. 

I'll look into it some more as I find time, was having some problems with has_many associations with the source option set not-gracefully failing.  If I can pinpoint that issue, I'll make a different ticket.  Want to make sure I wasn't just doing something wrong.

Thanks anyway, I'll come back if I find a solution / cause that isn't purely my fault!

**Comment by batter** [comment]
Haven't seen that (recently at least), but if you dig something up that's wrong with the test suite than be sure to let me know!
