### ISSUE TITLE
version_associations table

### ISSUE THREAD

**Issue by Celadon** [airblade/paper_trail#491]
Hello,

Just installed paper trail for Rails. Wish to track associations as per GitHub documentation. Cannot find version_associations table to install. Tried 'generate paper_trail:install --with-associations'. No version_associations migration created. Inspected gem. No version_associations template provided. Internet search unearthed the following migration in post #474. Is this the proper table? What am I doing wrong? 

create_table :version_associations do |t|
      t.integer  :version_id
      t.string   :foreign_key_name, null: false
      t.integer  :foreign_key_id
end

add_index :version_associations, [:version_id]
add_index :version_associations, [:foreign_key_name, :foreign_key_id], name: 'index_version_associations_on_foreign_key'

**Comment by batter** [comment]
What version of PaperTrail are you using? You need `4.0.0.beta2` or the current master branch or higher.

**Comment by Celadon** [comment]
bingo. my bad. thank you very much for quick reply. and even more for great gem.

**Comment by batter** [comment]
No worries. I would recommend current master since it's actually more stable than `4.0.0.beta2` to my knowledge (there's a known issue w/ deleting versions from the `versions` association on that release).  I am going to try to put some work in on things today and tomorrow and cut another release.
