### ISSUE TITLE
Batch updates without versioning

### ISSUE THREAD

**Issue by paulmenzel** [airblade/paper_trail#495]
Is there a way to disable versioning for an `update_all` call for example to avoid the following?

    GreatModel.all.each do |gm|
      gm.without_versioning :save # indirectly sets something
    end

**Comment by batter** [comment]
I actually was under the impression that batch updates don't get tracked / that versioning was broken as of now for batch updating (see #337). Are you seeing versions getting generated when you do an `update_all` call or are you just expecting it to happen?

FTR the easiest way to accomplish what you want as of now would probably be to do this:
```ruby
GreatModel.paper_trail_off!
GreatModel.upddate_all()
GreatModel.paper_trail_on!
```

**Comment by paulmenzel** [comment]
> I actually was under the impression that batch updates don't get tracked /
> that versioning was broken as of now for batch updating (see #337). Are you
> seeing versions getting generated when you do an `update_all` call or are you
> just expecting it to happen?

I was just expecting it to happen.

> FTR the easiest way to accomplish what you want as of now would probably be to do this:
> ```ruby
> GreatModel.paper_trail_off!
> GreatModel.update_all()
> GreatModel.paper_trail_on!
> ```

Awesome. Thank you for the quick help.

**Comment by batter** [comment]
But you shouldn't even need that as far as I know because `update_all` I believe skips callbacks, so it won't trigger version generation until we implement something to get it working.

**Comment by tahirror** [comment]
"batter" wondering if someone implemented update_all ?

**Comment by batter** [comment]
Not to my knowledge, would be challenging to do, but feel free to take a stab.
