### ISSUE TITLE
Thread Safety Issue with Thread.current[:some_key]?

### ISSUE THREAD

**Issue by justin808** [airblade/paper_trail#499]
See attached screen shots.

I've been dealing with replacing Thread.current[:some_value] because some app servers use the same thread across requests, **concurrently!**

https://github.com/steveklabnik/request_store

![steveklabnik_request_store](https://cloud.githubusercontent.com/assets/1118459/6719318/c84a0cac-cd5d-11e4-8547-6e7a4cb749c9.jpg)

![has_paper_trail_rb_-_topo_-____clients_paynearme_topo__-_rubymine__satsuki__rm-141_96](https://cloud.githubusercontent.com/assets/1118459/6719294/a32d4182-cd5d-11e4-9fa1-50e61a255e2e.jpg)

**Comment by batter** [comment]
Thanks for the concern, PaperTrail has already switched over to using RequestStore for version 4.x

See #413

**Comment by justin808** [comment]
@batter Any ETA for releasing 4.x? Will it work with Rails 3.2x?

**Comment by batter** [comment]
Hopefully by end of month, but you can bundle the current `master` branch in the meantime, which is stable.
