### ISSUE TITLE
Yaml getting stripped

### ISSUE THREAD

**Issue by brandonhilkert** [airblade/paper_trail#504]
We're stuck at version `1.6.5` because of Rails 2...I know it's probably no very well supported any more, but I was hoping someone could offer some insight. We're on Ruby 1.9.3 and have the following specified in the app:

```ruby
  YAML::ENGINE.yamler= 'syck'
```

`reify` works on some of our models, but not others. I tracked it down to the fact that, when the `object` gets in to the database, it looks like this:

```
--- \naccount_id: 1\ncached_tag_ids: \ncompany_id: \ncompany_name_d: \"\"\nconverted_at: \ncreated_at: 2014-12-12 14:28:47 Z\nwork_postal_code: \nwork_state:"
```

If from a Rails console, I run `person.attributes.to_yaml` (the same thing the get seems to be doing, I get:

```
--- \naccount_id: 1\ncached_tag_ids: \ncompany_id: \ncompany_name_d: \"\"\nconverted_at: \ncreated_at: 2014-12-12 14:28:47 Z\nwork_postal_code: \nwork_state:  \n"
```

Notice the ending ` \n` that's missing from the object in the database. I've experienced the same thing on 2 different models and it doesn't appear to be related to the number of characters, it seems to exclude the ending `\n` for each causing them to no be parsed when loaded back in.

Any idea why this would happen?

**Comment by batter** [comment]
Looks to me like you have YAML that is parsable by newer versions of the YAML library (re: Psych) but not older ones (Syck).  Older versions of YAML have consistency issues as far as I know but I don't know what to tell you in terms of getting it to work with psych, but you may be able to workaround by setting it like to Psych like so:

```ruby
YAML::ENGINE.yamler= 'psych'
```

I was able to get both of those yaml dumpouts to load via calls to `YAML.load` when the YAMLER was set to `Psych`. Did you give that a try?

**Comment by batter** [comment]
[This article may help educate you on the differences between the Psych and Syck libraries](http://devblog.arnebrasseur.net/2014-02-yaml-syck-vs-psych)

**Comment by batter** [comment]
The inconsistencies and deficiencies I've witnessed in the `YAML` libraries over the years have been enough to tempt me to switch to `JSON` as the default serializer for this gem, the only problem being that it would immediately break everyone's applications who were using older versions of PaperTrail and didn't realize they needed to either switch their default serializer back to YAML or convert their serialized data to `JSON`.

**Comment by brandonhilkert** [comment]
Hmmm...yeah you're right. Works for me with `psych` too. We have a bunch of columns that have yaml content in them. I'm worried about the global effect of that change. Guess I'll have to go digging through those columns to see what'll happen. Hopefully it doesn't mean full conversion of those columns. 

Out of curiosity, with the basic datatypes in `JSON`, wouldn't you have some headaches around conversion of data back to their original types?

**Comment by brandonhilkert** [comment]
Looks like we had some crazy `strip_attributes! :only => [:none]` on the model to avoid these issues. I probably shouldn't ask. Thanks for the info!
