### ISSUE TITLE
Question about associations

### ISSUE THREAD

**Issue by npearson72** [airblade/paper_trail#506]
I'd like to use this gem in the following way:

I have a Product with a price, and an Order that has many products.

Lets say I create a few orders and associate a product with them.

Then later, I decide to change the price on the product. I don't want the orders to reflect the live version, but rather use the previous version (i.e. latest version created after the price change on the product).

Is this possible without wiring up callbacks myself?

**Comment by jaredbeck** [comment]
Please use GitHub issues to report bugs and request features.  For questions about how to use PaperTrail, please use StackOverflow.  Thanks.
