### ISSUE TITLE
touch_with_version with specific attributes

### ISSUE THREAD

**Issue by HassanJaveed84** [airblade/paper_trail#508]
I am curious if touch_with_version is working as expected or not.
I have this in my model:

`has_paper_trail only: [:foo, :bar]`

Now when I issue `my_model_object.touch_with_version`, it does not create a new version.
I am guessing because I have have not included `updated_at` in the list it ignores it?
Is this the expected behaviour ?

How can I force create a version whilst not including `updated_at` in the attributes to monitor?

**Comment by batter** [comment]
For the time being, you can bundle from source (the current `master` branch) and call [`my_model_object.send(:record_update, true)`](https://github.com/airblade/paper_trail/blob/b97b29900dd42e8ff3b3764bfa8a4117cab67b37/lib/paper_trail/has_paper_trail.rb#L305).

I'm trying to come up with a more eloquent solution for this as it has already been brought up. See #456, #463.
