### ISSUE TITLE
Strict mode with tracking always enabled

### ISSUE THREAD

**Issue by jgonera** [airblade/paper_trail#514]
Would you be open to a PR enforcing a strict mode where `paper_trail` can never be disabled and works for all columns and actions? I can imagine this working by either:

* `PaperTrail.enabled` and arguments to `has_paper_trail` being ignored
* or raising exceptions if someone tries to set them.

Let's say it could be activated by putting something like this in `Gemfile`:
```ruby
gem 'paper_trail', '~> 4.0.0.beta', require: 'paper_trail/strict'
```

We are considering using `paper_trail` for some payments-related code at Airbnb and we would like to enforce tracking changes at all times in some models.

**Comment by batter** [comment]
Sure, sounds like a reasonable thing to me.  I'm thinking it should be a config option on [`PaperTrail::Config`](https://github.com/airblade/paper_trail/blob/v4.0.0.beta2/lib/paper_trail/config.rb) too (or in addition)... it could work in conjunction pretty straightforwardly I would expect.

**Comment by jaredbeck** [comment]
Given that there hasn't been any activity on this, can we postpone it to 4.1?

**Comment by batter** [comment]
Good thinking

**Comment by jgonera** [comment]
Definitely. We're still evaluating other options. We might end up not implementing this. The biggest issue is that we probably don't want to store versions in YAML blobs. We're still debating on this. I'll post here when we make a decision.

**Comment by batter** [comment]
@jgonera - You [can store them as JSON, or swap in your own serializer](https://github.com/airblade/paper_trail#using-a-custom-serializer)... you could even consider using Postgres's native JSON format. The gem is somewhat flexible, just let me know if you have any questions.

**Comment by jgonera** [comment]
@batter Postgres's JSON column is an interesting option, but unfortunately we're on MySQL. We'd like the versions table to mirror the original table's schema, so that it's easy to query outside of the Rails app. I know that this is less plug-and-play than paper_trail's current solution (need to migrate two tables), but it's a safer bet for us.

I didn't look at paper_trail's source code closely, but I'm assuming this would be a bigger change. Am I right?

**Comment by batter** [comment]
@jgonera - The short answer is yes. To get the exact same table schema in your versions table as the original table you are mirroring isn't how PaperTrail performs out of the box.

That being said, if there are a few select columns that most frequently end up being the attributes you need to query against you should take a look at the [metadata column feature](https://github.com/airblade/paper_trail#storing-metadata) which would serve this purpose well. It's not an exact mirror, so if you need every attribute to be query-able on your versions table, this solution may not be plausible for you, but if the queries are scoped to certain attributes this might be a good middle ground. Hope that helps.

**Comment by jgonera** [comment]
@batter thanks for all the help and being so responsive with this. We will most likely be writing our own solution which will be less plug and play, but will put a stronger emphasis on data integrity.

**Comment by jaredbeck** [comment]
> We will most likely be writing our own solution ..

Given that we don't have someone to implement this, my preference is to close the issue.  If anyone wants to implement this in the future, please open a PR, thanks!
