### ISSUE TITLE
Paper trail 4.0.0beta is not compatible with rspec

### ISSUE THREAD

**Issue by craftboy** [airblade/paper_trail#516]
After introducing paper_trail 4.0.0.beta to my project, all my controller tests failed. The error message is bellow:
       undefined method `authenticate' for nil:NilClass
Then I downgrade the version to 3.0.7, all the things go well. 
My Rails version is 4.2.0, and ruby version is 2.2.0.

**Comment by batter** [comment]
If you want to use the RSpec helper with `4.x` you need [to manually require it on your `spec_helper.rb`, see the README](https://github.com/airblade/paper_trail#rspec).  In 3.x it was automatically included.
