### ISSUE TITLE
Please release 4.0.0.beta3

### ISSUE THREAD

**Issue by jaredbeck** [airblade/paper_trail#517]
Hi Ben, thanks for all your work on 4.0! :heart:

4.0.0.beta2 was released January 16, 2015 (https://rubygems.org/gems/paper_trail).  I've been using `master` in production without any issues so far.  Please release `beta3`.  Thanks!

**Comment by batter** [comment]
Was trying to release an `rc1` after resolving one or two more open issues, hopefully by the end of the week. I've been super busy traveling, but I haven't forgotten about this, will try to see what I can do tonight.

**Comment by jaredbeck** [comment]
Thanks Ben, you're awesome!
