### ISSUE TITLE
PaperTrail doesn't play nice with Carrierwave and `remove_previously_stored_files_after_update` option

### ISSUE THREAD

**Issue by jmuheim** [airblade/paper_trail#521]
As I don't know whether this is a Carrierwave or a PaperTrail problem, I added a StackOverflow question here:

[PaperTrail doesn't play nice with Carrierwave and `remove_previously_stored_files_after_update` option](http://stackoverflow.com/questions/29624223/papertrail-doesnt-play-nice-with-carrierwave-and-remove-previously-stored-file).

Please help.

**Comment by batter** [comment]
In the past I've had success with a setup where I setup a model to attach carrierwave objects to, and have that model have a `has_one` association with another model that is versioned, that way you can put a callback on the carrierwave features to generate a new version every time you change the files attached to the first model you can generate a new version of the versioned model and keep track of the old carrierwave images as they change by pointing to the different model instances. I understand its not ideal but it worked well for me.

I'll try to take a look at the dummy app when I get some time.
