### ISSUE TITLE
Sidekiq job class name as meta data

### ISSUE THREAD

**Issue by kbaum** [airblade/paper_trail#524]
We would like to store the sidekiq job class as metadata on the versions table for all ActiveRecord objects.  This would help us track how certain objects were updated.  It looks like the meta data is stored on either a specific active_record class or the ApplicationController.  I don't want to make the declaration on each AR class that uses paper trail.  On the other hand it feels funny to declare this on ApplicationController since this has nothing to do with controllers.  What's the best way to set the sidekiq class on meta data?

thx!

-karl

**Comment by batter** [comment]
MetaData traditionally in the sense of PaperTrail is just an easy way to store custom data in their own columns on the versions table, so it seems like it would work for your case.

Why wouldn't you want to store these values in your DB? Where else would you store them?

**Comment by kbaum** [comment]
We do want to store them within our database but on the versions table.  Basically we want to know which sidekiq job was responsible for making the version change.  This would help us in our debugging efforts.  The problem is i don't know a generic way to use metadata from a sidekiq background job.

**Comment by batter** [comment]
> We do want to store them within our database but on the versions table

The versions table is in the database isn't it?

Essentially it sounds like you could just pass the value(s) you want to store as a virtual attribute onto your model (declare an `attr_accessor` or something), and [then follow the standard directions for setting up metadata on the README](https://github.com/airblade/paper_trail#storing-metadata).

**Comment by kbaum** [comment]
Our versions table is in the database yes.  

The issue is that i would want this virtual attribute on every model that declares paper trail.  Don't want to repeat this declaration all over the place:

```ruby
  has_paper_trail :meta => { sidekiq_job: :sidekiq_job }
```

Would rather take the `info_for_paper_trail` approach on application_controller as this is a global declaration.  Just seems kind of hacky as this will only ever be used from a sidekiq background job which has nothing to do with ApplicationController.

Thanks for your help!

**Comment by batter** [comment]
Good point, sorry it's been a while since I have actually used the gem in a production application myself, but I would recommend defining an `info_for_paper_trail` method on your `ApplicationController` and/or a module to be included on the controllers you need to derive the sidekiq job id's from. This type of thing is exactly what that feature was made for. Does that work for you?

Apologies if I'm not describing the best process, I'm also not very familiar with sidekiq (although I've heard it's a kick ass background processing tool).

**Comment by kbaum** [comment]
Thanks for your response!   I like the ApplicationController#info_for_paper_trail approach as it is DRY.  That being said, sidekiq jobs are executed outside the scope of a request and leveraging ApplicationController#info_for_paper_trail has a bit of a smell to it.  I really think that there should be somewhere more view agnostic to set info_for_paper_trail.

Thanks again!
-karl

**Comment by batter** [comment]
If you have any suggestions feel free to make a pull request :smiley:

**Comment by kbaum** [comment]
Of course… why not move this to PaperTrail.info_for_paper_trail?  Doesn’t seem much different than PaperTrail.whodunnit?

**Comment by jaredbeck** [comment]
> Of course… why not move this to PaperTrail.info_for_paper_trail?  Doesn’t seem much different than PaperTrail.whodunnit?

@kbaum There is already a class method `PaperTrail.controller_info=` that you can use.

```ruby
# paper_trail.rb
# Sets any information from the controller that you want PaperTrail
# to store.  By default this is set automatically by a before filter.
def self.controller_info=(value)
  paper_trail_store[:controller_info] = value
end
```

The `before_filter` mentioned is `set_paper_trail_controller_info`.

```ruby
# paper_trail/frameworks/rails/controller.rb
# Tells PaperTrail any information from the controller you want
# to store alongside any changes that occur.
def set_paper_trail_controller_info
  ::PaperTrail.controller_info = info_for_paper_trail if ::PaperTrail.enabled_for_controller?
end
```

Anything you put in `PaperTrail.controller_info` gets merged over any other metadata:

```ruby
# paper_trail/has_paper_trail.rb
def merge_metadata(data)
  # First we merge the model-level metadata in `meta`.
  # .. snip ..
  # Second we merge any extra data from the controller (if available).
  data.merge(PaperTrail.controller_info || {})
end
```

I know it's weird to use a variable called `controller_info` when there's no controller involved, but otherwise this sounds like exactly what you're looking for.

PS: I think we'd be open to a PR that renames `PaperTrail.controller_info` to something more generic, like `PaperTrail.metadata`.  If we do rename this variable, we should deprecate it in 4.1 and rename in 5.0.

**Comment by jtomaszewski** [comment]
Thanks guys for your notes, they helped me a lot.

For future guests, I share my code. I added a `:context, type: :json` column to `versions` table, and then in ApplicationController / ApplicationWorker I just set up the context of the action that created the version, for example:

```rb
# ApplicationController
  def info_for_paper_trail
    {
      context: {
        origin: "ApplicationController",
        request_ip: request.remote_ip,
        request_user_agent: request.user_agent
      }
    }
  end
```

```rb
## NOTE all your workers have to inherit from ApplicationWorker, 
## and implement #perform! method, instead of #perform
class ApplicationWorker
  extend ActiveModel::Callbacks
  define_model_callbacks :perform

  around_perform :set_paper_trail_context

  def set_paper_trail_context
    PaperTrail.controller_info = {
      context: {
        origin: "ApplicationWorker",
        class_name: self.class.name
      }
    }

    yield

    PaperTrail.controller_info = {}
  end

  def perform
    run_callbacks(:perform, &:perform!)
  end

  def perform!
    raise "Missing your #perform! method implementation"
  end
end
```

**Comment by kumud-b5a** [comment]
How thread-safe is this workaround?

> Thanks guys for your notes, they helped me a lot.
> 
> For future guests, I share my code. I added a `:context, type: :json` column to `versions` table, and then in ApplicationController / ApplicationWorker I just set up the context of the action that created the version, for example:
> 
> ```ruby
>   # ApplicationController
>   def info_for_paper_trail
>     {
>       context: {
>         origin: "ApplicationController",
>         request_ip: request.remote_ip,
>         request_user_agent: request.user_agent
>       }
>     }
>   end
> ```
> 
> ```ruby
> ## NOTE all your workers have to inherit from ApplicationWorker, 
> ## and implement #perform! method, instead of #perform
> class ApplicationWorker
>   extend ActiveModel::Callbacks
>   define_model_callbacks :perform
> 
>   around_perform :set_paper_trail_context
> 
>   def set_paper_trail_context
>     PaperTrail.controller_info = {
>       context: {
>         origin: "ApplicationWorker",
>         class_name: self.class.name
>       }
>     }
> 
>     yield
> 
>     PaperTrail.controller_info = {}
>   end
> 
>   def perform
>     run_callbacks(:perform) do
>       perform!
>     end
>   end
> 
>   def perform!
>     raise "Missing your #perform! method implementation"
>   end
> end
> ```

**Comment by marcelkooi** [comment]
Adding a follow-up to this as an alternative method of making this work, using sidekiq middleware:

```rb
class PaperTrailMessageMiddleware
  include Sidekiq::ServerMiddleware

  def call(job_instance, job_payload, queue)
    message = "worker: #{job_instance.class.name}, job_id: #{job_payload['jid']}, queue: #{queue}"
    PaperTrail.request.controller_info = { message: message }

    yield
  ensure
    PaperTrail.request.controller_info = nil
  end
end

Sidekiq.configure_client do |config|
  config.server_middleware do |chain|
    chain.add(PaperTrailMessageMiddleware)
  end
end

```
