### ISSUE TITLE
Polymorphic Bug in 4.0.0beta2?

### ISSUE THREAD

**Issue by AlanMcCann** [airblade/paper_trail#527]
With 4.0.0.beta2, I have the following error that works fine on version 3.0.7. I have seen a previous issue/fix that might have addressed this but I thought the pull request was merged into 4.0.0.beta2

    class Query < ActiveRecord::Base
      has_paper_trail
      belongs_to :queryable, polymorphic: true
    end

    class Universe < ActiveRecord::Base
      has_many :queries, as: :queryable, dependent: :destroy
    end

Updating queryable results in a NameError: uninitialized constant Query::Queryable error 

    q = Query.last
    q.queryable = Universe.last
    q.save

    SQL (13.2ms)  UPDATE "versions" SET "transaction_id" = $1 WHERE "versions"."id" = $2  [["transaction_id", 3548], ["id", 3548]]
       (15.4ms)  ROLLBACK
      PaperTrail::Version Load (14.5ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC  [["item_id", 4], ["item_type", "Query"]]
    NameError: uninitialized constant Query::Queryable
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:158:in `compute_type'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:271:in `compute_class'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:267:in `klass'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.beta2/lib/paper_trail/has_paper_trail.rb:376:in `block in save_associations'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.beta2/lib/paper_trail/has_paper_trail.rb:375:in `each'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.beta2/lib/paper_trail/has_paper_trail.rb:375:in `save_associations'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.beta2/lib/paper_trail/has_paper_trail.rb:322:in `record_update'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_update_callbacks'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:310:in `_update_record'
    ... 25 levels...
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:286:in `block in save'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:285:in `save'
      from (irb):11
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      from /Users/alanmccann/railsapps/papertailtest/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
      from bin/rails:4:in `require'
      from bin/rails:4:in `<main>'

**Comment by batter** [comment]
You need to bundle from source for now. I'm hoping to push out 4.0.0.rc1 in a couple days.

**Comment by AlanMcCann** [comment]
Perfect. Thanks for the quick response.
