### ISSUE TITLE
whodunnit is wrong

### ISSUE THREAD

**Issue by UnConundrum** [airblade/paper_trail#528]
I'm having an issue where whodunnit is wrong when the user record is updated.  The item_id is the correct id for the user and that user record would only be updated when the user is active.

This is happening with both Rails 2.3.11 using PaperTrail 1.6.5 and Rails 4.2.0 using PaperTrail 4.0.0.beta2

The executing code is used to track user activity and is the same in both versions of Rails:

	def last_request_at
		if current_user.class.name == "User"
			last_seen = current_user.last_seen
			if last_seen.nil? or last_seen > 5.minutes.ago
				current_user.update_attributes(:last_seen => Time.now)
			end
		end
	end

The incorrect values I'm seeing for whodunnit are legitimate possible values (i.e. we have about 140 possible users with sequential ids. and the value doesn't exceed 140).  This problem is sporadic, happening about 2/3 of the time.

**Comment by batter** [comment]
Are you sure you're not misunderstanding the difference between the `whodunnit` and the `originator` method?

**Comment by UnConundrum** [comment]
Well, I wasn't sure before your post.  whodunnit " Returns who changed the item from the state it had in this version." while originator "Returns who put the widget into its current state."   Fine line there, but in my situation, they'd be the same.  A user should be updating their own user record, so they should be "whodunnit" for the new record, and I guess originator for the prior change/update.  No one else should be entering the mix, or am I missing something?

**Comment by batter** [comment]
sorry for the delayed response but I'm a bit confused as to what exactly the problem is. You are saying you are seeing incorrect values but that they are legitimate possible values.

You could also consider invoking the `touch_with_version` method instead of `update_attributes`:

```ruby
def last_request_at
    if current_user.class.name == "User"
        last_seen = current_user.last_seen
        if last_seen.nil? or last_seen > 5.minutes.ago
            current_user.touch_with_version(:last_seen)
        end
    end
end
```

That will ensure version creation.

You don't have `user_for_paper_trail` overwritten on one of your controllers do you?  Such [as is explained on the README](https://github.com/airblade/paper_trail#finding-out-who-was-responsible-for-a-change)

**Comment by UnConundrum** [comment]
Thanks for getting back to me.  I tried the touch_with_version but it doesn't seem to have helped, and no, I haven't overridden user_for_paper_trail.

By "legitimate possible values" I meant that the whodunnit is within the set of active user ids, but not the id for the user object being updated.  So, if current_user is me, id 17, and my user record is updated/touched as I use the application, whodunnit might have the value of 141 for example.  The item_id will correctly reflect 17.  

The problem is sporadic, happening only about 1% of the time.  Most frequently, the values are correct.  I'm wondering if the issue could be related to a session having expired and the user logging back in, however, I'd expect whodunnit to be nil or empty in that event.

I guess I could use user_for_paper_trail or PaperTrail.whodunnit= to resolve the issue, but that doesn't identify the problem.

**Comment by yusufnb** [comment]
We have seen this exact issue as well in our application. Have been searching on the net for any resolution. Unless we find a fix, we will have to find an alternative solution or build our own. Any help would be appreciated.

**Comment by jaredbeck** [comment]
Can you reproduce this issue in a new rails app with a clean install of the latest version of paper_trail (currently 4.0.0.rc1)?  Thanks!

**Comment by jaredbeck** [comment]
One month ping.  Are either of you two able to reproduce this issue in a new rails app with a clean install of the latest version of paper_trail?  Thanks.

**Comment by yusufnb** [comment]
Sorry Jared, couldn't get back earlier. Thanks for the ping. Our versions table has over 40 million records, with 1000s of users. So it sure is not the typical use case. paper_trail is a great gem and served us well so far (besides that little issue). I haven't found time to simulate our use case and repro this issue, but we are in the process of separating this function out into its own micro-service. Thanks.

**Comment by jaredbeck** [comment]
Thanks Yusuf.  Please let use know if you find a way to reproduce the issue.

**Comment by mkpb** [comment]
Same issue here.
Devise created users table is also versioned on our system.
We currently use paper_trail 3.0.0.
While investigating other issue, I was checking paper_trail audit entries, and was a little shocked, that according to paper_trail records of user A are updated by user B (whodunnit) while user A was logging into the system (last / current IP / last login time changes).
Now, at least I know our system is not falling apart, and it's something to do with paper_trail.

**Comment by jaredbeck** [comment]
> We currently use paper_trail 3.0.0.

The latest version is 8.1.0. Please update (carefully, one major version at a time) ASAP.

**Comment by adrianDY** [comment]
We're also facing the exact same issue. Our customers reported seeing users they do not recognize on their "last modified" tables
After research we found that this issue sporadic and cannot be replicated willingly although we have seen several cases but one case is severe enough to spark alarm with security-centric users...

Was this ever confirmed by PaperTrail as a known issue and if so, was it resolved with any specific version?

**Comment by shanmugarajan** [comment]
> We're also facing the exact same issue. Our customers reported seeing users they do not recognize on their "last modified" tables
> After research we found that this issue sporadic and cannot be replicated willingly although we have seen several cases but one case is severe enough to spark alarm with security-centric users...
> 
> Was this ever confirmed by PaperTrail as a known issue and if so, was it resolved with any specific version?

What version are you using ?

**Comment by adrianDY** [comment]
@shanmugarajan We're using an old version: `paper_trail (3.0.9)` because we're currently upgrading our entire Rails instance.
In the meantime we wrapped the hooks with our own code to protect against incorrect users.
Hoping that a more recent version of papertrail resolves the issue
