### ISSUE TITLE
i need to integrate paper_trail in rails 2 application , but couldnt integrate it....

### ISSUE THREAD

**Issue by karthikGV** [airblade/paper_trail#529]
below steps are which i  followed  to integrate 

$gem install paper_trail -v 1.2.13
$ruby ./script/generate paper_trail
$rake db:migrate

after migration i added has_paper_trail in my model , then when i restart the server i am getting error 

NameError (undefined local variable or method `has_paper_trail' for #<Class:0x7fa9325e4a60>):
  vendor/plugins/alphena_audit_customisation/app/models/alphena_paygrade.rb:2
  vendor/plugins/alphena_audit_customisation/app/controllers/alphena_paygrades_controller.rb:4:in `add_paygrade'
  pdfkit (0.6.2) lib/pdfkit/middleware.rb:17:in `call'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /home/rank/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:82:in `start'

**Comment by batter** [comment]
Hard for me to assist on this since I haven't worked on the Rails 2 compatible code base at all, but I would says checkout the [`rails2` branch](https://github.com/airblade/paper_trail/tree/rails2), and possibly try integrating the most recent 1.x version, which appears to be [`v1.6.5`](https://rubygems.org/gems/paper_trail/versions/1.6.5)
