### ISSUE TITLE
Problem with Has Many Through Association Rails

### ISSUE THREAD

**Issue by genius-devil** [airblade/paper_trail#530]
class Document < ActiveRecord::Base
  has_many :sections
  has_many :paragraphs, through: :sections
end
 
class Section < ActiveRecord::Base
  belongs_to :document
  has_many :paragraphs
end
 
class Paragraph < ActiveRecord::Base
  belongs_to :section
end

Paper_Trail 4.0.0 Beta doesn't cater this situation. It looks for foreign key of association Paragraph i.e, section_id in the through model i.e, Section which will not be available in the above mentioned case.

**Comment by batter** [comment]
Please see #466
