### ISSUE TITLE
DISABLE_SPRING=1 disables PaperTrail

### ISSUE THREAD

**Issue by borgand** [airblade/paper_trail#532]
First off: I can't reproduce this with a new Rails app, but it appears in a complex app on multiple machines.

Background: I'm trying to set up CI for my project and for some reason `spring` hangs and leaves `<defunct>` ruby processes there. Disabling Spring seems to work (and CI runner only wins from disabling spring), but suddenly all my specs fail that depend on PaperTrail versions being created.

The problem is: silently no versions are created as if PaperTrail is disabled, but `pry`-ing into spec gives:

    u.paper_trail_enabled_for_model?
    # => true

And no errors are given, just silently ignored.

I have debugged this as far as I'm able and found that both:

    DISABLE_SPRING=1 bin/rails c
    DISABLE_SPRING=1 bin/rails c test

are **OK**, whereas

    DISABLE_SPRING=1 bin/rspec

has **failures** only in my PaperTrail specs.

Also, production environment (i.e. without spring) works fine.

Currently I have:
Rails 4.1.9
PaperTrail 3.0.3
Rspec 3.0.0
Database: Postgres
Additional: Apartment based multi-tenancy

But this happened with PaperTrail 3.0.8 too.

Can you give me some pointers where to look next and how to debug better. I'm not entirely sure this is PaperTrail issue, but I'm out of ideas.

**Comment by batter** [comment]
PaperTrail 3 has a helper feature built in for RSpec where PaperTrail gets disabled globally when tests execute, and then you need to opt in to turning versioning on for the tests where you want versioning to occur. Please see [the README section regarding RSpec on the `3.0-stable` branch](https://github.com/airblade/paper_trail/tree/3.0-stable#rspec) for more details on how to use it.

**Comment by borgand** [comment]
I thought that if I don't require the RSpec helper `paper_trail/frameworks/rspec` then PaperTrail would be **on** globally even during testing.

Our app depends on PaperTrail for some deeper change detections and it was easier to enable PaperTrail globally for testing with:

```ruby
# file: spec_helper.rb
require 'paper_trail/frameworks/rspec'
config.before(:each) do
  ::PaperTrail.enabled = true
end
```

Curiously, without the helper loaded, the same before action did not enable PaperTrail.

Am I on the right track assuming that what _Spring_ did was preload and enable PaperTrail before forking to run RSpec, thus fooling PaperTrail not to turn off itself while disabling Spring allowed PaperTrail to detect RSpec?

BTW, when trying out the helper, using `versioning: true` for Context worked fine, but when I tried to wrap `it`'s with `with_versioning` they were always filtered out. Is this normal?

If all this was expected behaviour, then you can close this issue - I'm fixed now. Thanks.
Perhaps a small note in the README that the RSpec helper should always be loaded or Spring could cause issues with tests would do good.

**Comment by batter** [comment]
> I thought that if I don't require the RSpec helper paper_trail/frameworks/rspec then PaperTrail would be on globally even during testing.

That's only for PaperTrail 4.x  (hoping to release `4.0.0.rc1` later today), on PaperTrail 3.x the helper is always loaded when the gem is used in conjunction with RSpec.

> Am I on the right track assuming that what Spring did was preload and enable PaperTrail before forking to run RSpec, thus fooling PaperTrail not to turn off itself while disabling Spring allowed PaperTrail to detect RSpec?

I'm not certain because I haven't used Spring much, there is [a separate section of the README regarding usage with Zeus and Spring on the `3.0-stable` branch, please see this](https://github.com/airblade/paper_trail/tree/3.0-stable#zeus-or-spring).

> BTW, when trying out the helper, using versioning: true for Context worked fine, but when I tried to wrap it's with with_versioning they were always filtered out. Is this normal?

No, the `with_versioning` blocks should execute as normal, none of the versioning executed inside those blocks for you?

**Comment by borgand** [comment]
Ok, RTFM for me:

> If you wish to use the RSpec or Cucumber helpers with Zeus or Spring, you will need to manually require the helper(s) in your test helper

This explains exactly what I was seeing: helper not loaded with Spring, i.e. PaperTrail enabled and loaded w/o Spring, i.e. PaperTrail disabled.

> No, the with_versioning blocks should execute as normal, none of the versioning executed inside those blocks for you?

I copied the example RSpec code from the README with **3** examples and when run, it warned me about deprecated `should_not` in the first example and reported:

```
1 deprecation warning total

Finished in 0.68839 seconds (files took 8.79 seconds to load)
2 examples, 0 failures
```

That means that it filtered out the middle example that used `with_versioning`

**Comment by batter** [comment]
Unless you can provide a code example in a gist or something I'm not sure what else I can do to help..

**Comment by borgand** [comment]
As the main issue is due to misconfiguration on my part, probably the `with_versioning` is too. Better to close this issue and if I encounter it in any simpler setup, I'll dig deeper then.
