### ISSUE TITLE
uninitialized constant ActiveRecord (NameError) with Ruby 2.1.5, Rails 4.2.0

### ISSUE THREAD

**Issue by mr64bit** [airblade/paper_trail#533]
I'm getting an ``uninitialized constant ActiveRecord`` error when trying to load my Rails program, with Papertrail in my Gemfile. If I set ``require: false`` in my Gemfile, I can require it manually with no errors in the rails console, and both `ActiveRecord` and `PaperTrail` are valid.
I'm using Ruby 2.1.5, Rails 4.2.0. I've tried disabling every gem except for Rails, with no success. My current Gemfile is:
```ruby
source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'web-console', '~> 2.0'
  gem 'pry'
  gem 'pry-rails'
  gem 'rerun'
end

gem 'curb'
gem 'steam-condenser', git: 'https://github.com/koraktor/steam-condenser-ruby.git'
gem 'net-ssh', require: 'net/ssh'
gem 'sidekiq'
gem 'sinatra', require: false
gem 'thin'
gem 'sidekiq-status'
gem 'aasm'
gem 'responders'
gem 'rocket_pants', git: 'https://github.com/Sutto/rocket_pants.git', branch: '2.0-rewrite'
gem 'passenger'
gem 'whenever'
gem 'paper_trail', '~> 4.0.0.rc'
```

Trace:
```
$ rails c --trace
/home/jamesl/.rvm/gems/ruby-2.1.5@serverbot/gems/paper_trail-4.0.0.rc1/lib/paper_trail.rb:103:in `active_record_protected_attributes?': uninitialized constant ActiveRecord (NameError)
        from /home/jamesl/.rvm/gems/ruby-2.1.5@serverbot/gems/paper_trail-4.0.0.rc1/lib/paper_trail.rb:139:in `<top (required)>'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
        from /home/jamesl/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
        from /home/jamesl/ruby/serverbot/config/boot.rb:5:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
```
Any help is much appreciated!

**Comment by mr64bit** [comment]
For reference (and anyone who is having the same problem), `gem 'paper_trail', '~> 4.0.0.rc', require: false` in your Gemfile and `require 'paper_trail'` in `config/application.rb` works fine, just an ugly workaround.

**Comment by batter** [comment]
Hmm... I'll setup a dummy app and look into this. This seems like an odd error and the stacktrace doesn't really reveal anything of substance. ActiveRecord is a dependency for the gem which I assumed meant Rubygems ensures it is loaded before it starts loading in the PaperTrail Library.

**Comment by batter** [comment]
@mr64bit - For what it's worth I setup a dummy app and was unable to reproduce this with `4.0.0.rc1`. Is this the only version of PaperTrail you are able to reproduce these issues with? Any chance you can supply a dummy app with this error present?

If that's not easy, can you also supply your `config/application.rb`?  `ActiveRecord` should get loaded before the call to `Bundler.require` on that file, either via `require 'rails/all'` or `require 'active_record/railtie'`

**Comment by batter** [comment]
Also can you share your `config/boot.rb`?

**Comment by mr64bit** [comment]
Found the problem. Had an extra `Bundler.require` in my boot.rb. Odd, cause it's never caused any problems in the past.
Thanks for the help!

**Comment by batter** [comment]
Great, I figured it had to be some issue like that, glad I could be of service :smile:
