### ISSUE TITLE
has_many reification slow with large dataset 

### ISSUE THREAD

**Issue by mwalsher** [airblade/paper_trail#536]
It looks like calling `reify(has_many: true)` produces several one of these queries for each has_many association:

```
SELECT `versions`.* FROM `versions` WHERE (id IN (SELECT MIN(version_id) FROM `version_associations` INNER JOIN `versions` ON `versions`.`id` = `version_associations`.`version_id` WHERE (foreign_key_name = 'source_id') AND (foreign_key_id = 1) AND (versions.item_type = 'RelatedItem') AND (created_at >= '2015-05-17 16:47:51' OR transaction_id = 927355) GROUP BY item_id))
```

Each of these is taking about ~3 seconds to run with about 1.2 million rows in the versions table.

The EXPLAIN generates:

```
1	PRIMARY	versions	ALL	NULL	NULL	NULL	NULL	1122244	Using where
2	SUBQUERY	version_associations	ref	index_version_associations_on_version_id,index_version_associations_on_foreign_key	index_version_associations_on_foreign_key	262	const,const	1	Using index condition; Using where; Using temporary; Using filesort
2	SUBQUERY	versions	eq_ref	PRIMARY,index_versions_on_item_type_and_item_id,index_versions_on_transaction_id,index_test	PRIMARY	4	app_development.version_associations.version_id	1	Using where
```

Is there a more efficient way you could write that query? I tried playing with the indexes but to no avail...

**Comment by jaredbeck** [comment]
Hi Mike.  Thanks for the bug report.

For my own reference, here's the query you provided, but formatted:

```sql
SELECT `versions`.*
FROM `versions`
WHERE 
(
  id IN
  (
    SELECT MIN(version_id)
    FROM `version_associations`
    INNER JOIN `versions` 
      ON `versions`.`id` = `version_associations`.`version_id`
    WHERE (foreign_key_name = 'source_id')
      AND (foreign_key_id = 1)
      AND (versions.item_type = 'RelatedItem')
      AND 
      (
        created_at >= '2015-05-17 16:47:51'
        OR transaction_id = 927355
      )
    GROUP BY item_id
  )
)
```

I'll see if I can populate 1.2 million rows in a test database and see if I get the same ~3 second query times.

As a side note, there is a configuration option to limit the number of version records you keep, `PaperTrail.config.version_limit`.  Perhaps something you could use?  Obviously not appropriate for every use case.

**Comment by jaredbeck** [comment]
I'm seeing a trend in query times vs. number of version records that seems similar to the 3s / 1.2M records you saw.

parent records | child records | version records | query time (ms)
--------------- | ------------- | ------------ | ----------
200 | 1982 | 2374 | 2
400 | 3326 | 35062 | 2
500 | 3811 | 121054 | 62
600 | 4257 | 200650 | 323

However, once the database cache and OS file cache is warm, I'm seeing numbers drop back in the the single-digit milliseconds.  Are you seeing the same re: warm cache / cold cache?

**Comment by jaredbeck** [comment]
> Are you seeing the same re: warm cache / cold cache?

Another question for you, Mike: can you please confirm that you have all of the following indexes:

```
add_index :versions, [:item_type, :item_id]
add_index :version_associations, [:version_id]
add_index :version_associations, [:foreign_key_name, :foreign_key_id], 
  :name => 'index_version_associations_on_foreign_key'
add_index :versions, [:transaction_id]
```

**Comment by mwalsher** [comment]
Hey Jared,

Thanks for getting back to me. My answers below:

1. MySQL
2. No – it is a persistent issue unfortunately
3. Looks like I'm missing the following index (and columns for that matter):

`add_index :version_associations, [:foreign_key_name, :foreign_key_id], 
  :name => 'index_version_associations_on_foreign_key'`

I'm currently running 4.0.0.rc1. Were those columns added after that release? I'll try updating and adding those columns/index to see if it helps.

Cheers

**Comment by mwalsher** [comment]
My mistake – I was looking at the wrong table. I needs coffee.

I do have the `index_version_associations_on_foreign_key` index on versions_associations as well.

**Comment by jaredbeck** [comment]
>> Are you seeing the same re: warm cache / cold cache?
>>
> No – it is a persistent issue unfortunately
>

What does that mean?  You run the same exact query over and over and it takes 3s every time?

**Comment by jaredbeck** [comment]
Mike, I can't reproduce this issue in Postgres. With 280,000 version records I'm getting single-millisecond query times once the db cache is warm.  What's our next step here?  Do you know of an easy way to generate lots of version records quickly for testing purposes?  Do you want to privately send me a dump of your database?

If we were to continue, I would also need an answer to my question re: warm cache / cold cache behavior.  You run the same exact query over and over and it takes 3s every time?

**Comment by jaredbeck** [comment]
> As a side note, there is a configuration option to limit the number of version records you keep, PaperTrail.config.version_limit. Perhaps something you could use? Obviously not appropriate for every use case.

Also, there's a [`Cleaner` module][1] that might help you do a one-time clean up.

[1]: https://github.com/airblade/paper_trail/blob/v4.0.0/lib/paper_trail/cleaner.rb

**Comment by jaredbeck** [comment]
> Each of these is taking about ~3 seconds to run with about 1.2 million rows in the versions table.

I generated more records, still not able to reproduce this in postgres.

parent records | child records | version records | query time, cold cache (ms) | warm cache
--------------- | ------------- | ------------ | ---------- | ---------- |
2,782 | 100,914 | 1,902,014 | 580 | 90

I'm running Postgres 9.4 on a 3.06 GHz i3 with 12 GB RAM.  I think my warm cache times probably indicate that I'm able to load the whole versions table in memory.  What are the specs on your MySQL server?

**Comment by jaredbeck** [comment]
I'm going to close this, primarily because I haven't heard from you in a month, and secondarily because it doesn't seem to be a problem in postgres, with adequate system resources.

**Comment by batter** [comment]
Thanks for the investigation and detailed analysis @jaredbeck
