### ISSUE TITLE
'where_object_changes' includes item_id in search

### ISSUE THREAD

**Issue by Konair0s** [airblade/paper_trail#543]
I have a model (User) with id 2466.

`PaperTrail::Version.where_object_changes(user_id: 2466)` returns versions where object id was changed to 2466 (correctly) AND also returns an item with id 2466 (2466).

`#<ActiveRecord::Relation [#<PaperTrail::Version id: 11237, item_type: "Attachment", item_id: 2466, event: "create", whodunnit: nil, object: nil, created_at: "2015-05-31 06:43:50", object_changes: "---\nfile_file_name:\n- \n- open-uri20150531-3-x34rte...", transaction_id: 11237>,`

**Comment by batter** [comment]
Looks like your code example got cutoff. Can you complete it please?

**Comment by batter** [comment]
Closing unless you can provide further information. Feel free to ping / reopen this if you are still having difficulty @Konair0s
