### ISSUE TITLE
uninitialized constant error when polymorphic association used in meta

### ISSUE THREAD

**Issue by atstockland** [airblade/paper_trail#544]
If I use polymorphic association in the meta hash, I get uninitialized constant error.  PaperTrail seems to be looking for a model with the poly name, not the polys _type column name.

For example I have a model called class LessonGradeItem, with belongs_to :lesson, polymorphic: true.  I need to added which school the version record belongs to, so I use metadata.

has_paper_trail meta: { school_id: Proc.new { | lesson_grade_item | lesson_grade_item.lesson.course.school_id } }

results in uninitialized constant LessonGradeItem::Lesson

I don't have any specs that reveal anything beyond the error above.  If I removed has_paper_trail, or remove meta...the record saves.

UPDATE
actually just using has_paper_trail with no options produces the same error.  This makes me think my poly association might not be correct, but .... both sides of the association are correct (and functioning outside of paper_trail).

**Comment by batter** [comment]
When you ran the install generator, did you run it with the `--with-associations` flag?

`rails generate paper_trail:install --with-associations`

**Comment by jaredbeck** [comment]
Closing issue. Please provide the requested information and we'll be happy to reopen it.

**Comment by atstockland** [comment]
Really sorry for the late response.  I believe my issue was having has_paper_trail and also has_many :versions.  I have a meta column for company_id and I have a view for listing recent versions for a given company.  I have opted to not use has_paper_trail in the company model so I can use has_many :versions in the 'activity' view.  I do have the associations table.  After fixing it so the model does not include both has_paper_trail and has_many :versions...all is well.  Thanks!
