### ISSUE TITLE
Versions being updated with item_id nil

### ISSUE THREAD

**Issue by proletarian** [airblade/paper_trail#547]
We are seeing situations where Papertrail is updating its own records but setting item_id to null. See below that the item type should be User and the item_id should be 807, but the SQL operation is an update with item_id null, thus violating the non-null constraint.
_____
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "item_id" violates not-null constraint
DETAIL:  Failing row contains (223, User, null, update, null, ---
id: 807
email: abc@xyz.com
encrypted_passwor..., 2015-06-10 18:50:06.474107, ---
last_sign_in_at:
- 2015-06-10 17:53:05.908893000 Z
- &1 2015..., 223).
: UPDATE "versions" SET "item_id" = NULL WHERE "versions"."id" IN (SELECT "versions"."id" FROM "versions"  WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 AND "versions"."id" IN (223, 229)  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC)
_____
Papertrail 4.0.0 rc
Rails 4.1.8

**Comment by batter** [comment]
What (Ruby) methods are you calling when this is occurring?  Are you making a call like `reify.save` or something?

Maybe #422 could be helpful?  Also are you using Single Table Inheritance in one of your models?

**Comment by proletarian** [comment]
In one case it was just removing records in a model that had a has_many association to the User.
In another case, one of our colleagues just tried updating a user's password. These are all done with the rails_admin gem's interface. 
We had to take out paper trail temporarily so we don't have much more info yet. We don't have any :versions associations like #422 and we don't have STI.

**Comment by jaredbeck** [comment]
Thanks for the bug report! Can you reproduce this issue in a new rails app with a clean install of paper_trail 4.0.0.rc1?

**Comment by jaredbeck** [comment]
Closing issue. If anyone can provide steps to reproduce this issue, we'll be happy to reopen it.

**Comment by jongbeau** [comment]
I experienced this issue, and it happens when working with :uuid type item_ids.  Most of our models use a :uuid for the id primary key. However, we have a couple tables that use a normal :integer id.  These models that use the integer id throw the `null value in column "item_id"` when trying to save. Is there a way to add a conversion method so we can convert the ids to uuids before saving to the versions table?

**Comment by batter** [comment]
I would recommend using 2 different version tables, one for objects with integer ids, and one for tables that have uuids as their primary keys

**Comment by debreczeni** [comment]
We have the same issue in development, and a definite difference from production is that the versions table is empty. Will look into this further as it is really annoying to have to remove the has_paper_trail lines from all of our models in development.

**Comment by chaostheory** [comment]
I experienced the same problem involving UUIDs. In my case, the issue was my fault. When creating a table in a migration, I forgot to specify that the id would be a uuid e.g. table_name, id: :uuid do |t|
