### ISSUE TITLE
paper_trail makes devise_token_auth omniauth connection crash

### ISSUE THREAD

**Issue by casertap** [airblade/paper_trail#548]
![capture d ecran 2015-06-17 a 17 40 29](https://cloud.githubusercontent.com/assets/284394/8211668/0f2df460-1518-11e5-8f5c-b4686cc23259.png)

When I simply try to login with facebook using devise_token_auth, paper_trail get in the way and make the connection crash.
Just removing the paper_trail gem from the gemfile solve the problem.
The more surprising here is that my User in NOT has_paper_trail.
Take a look at this issue I opened in devise_token_auth: https://github.com/lynndylanhurley/devise_token_auth/issues/268

**Comment by casertap** [comment]
It is at the frame -3 that paper_trail try to call current_user but the current_user is not event created.

![capture d ecran 2015-06-17 a 17 51 35](https://cloud.githubusercontent.com/assets/284394/8212026/b91e4ec4-1519-11e5-8733-ce259271585c.png)

**Comment by jaredbeck** [comment]
Can you reproduce this error in a new application, with a clean install of paper_trail and devise_token_auth?

**Comment by batter** [comment]
@casertap - you can always override the `user_for_paper_trail` method in your `ApplicationController`, as [demonstrated in the README](http://numeraljs.com/). That should be sufficient to allow you to implement any behavior you need or desire to get your app working with devise_token_auth.

**Comment by casertap** [comment]
@batter Thank you, I am gonna try that
@jaredbeck I should be very easy to reproduce, just dl the the ng-token-auth with the test app and run it using: https://github.com/lynndylanhurley/ng-token-auth#running-the-dev-server
dl the back end demo app: https://github.com/lynndylanhurley/devise_token_auth_demo 
try if everything works without paper_trail and then, add the paper_trail gem to the app and try to login using omniauth (Facebook is the one I had a problem with)

**Comment by jaredbeck** [comment]
>> .. override the user_for_paper_trail method in your ApplicationController ..
> Thank you, I am gonna try that

Did that work?

**Comment by jaredbeck** [comment]
Closing answered question after one week of inactivity.  Please let us know if you get around to trying Ben's suggestion.
