### ISSUE TITLE
Switch the default serializer to JSON?

### ISSUE THREAD

**Issue by jaredbeck** [airblade/paper_trail#555]
Ben, this is just a placeholder for a future discussion, starting where we left off in https://github.com/airblade/paper_trail/pull/551

> I will say that I have been wondering for a while whether it makes sense to switch the default serializer to `PaperTrail::Serializers::JSON` (instead of `PaperTrail::Serializers::YAML`), because JSON syntax is more consistent in it's parsing (not as much of an issue anymore, but when it was unclear whether you'd get `syck` or `psych` depending on which Ruby version you were using for a while, it did cause some compatibility issues), and also dumps into shorter and more concise syntax than YAML (it's also faster as far as I know).  This would probably prevent some of these column limit size issues that people like @brodock were running up against. That being said, it would also be a breaking change for anyone who didn't read the documentation and realize they needed to manually swap in the old YAML serializer if they have legacy data (or update all their old data to JSON... perhaps we could provide a script / mechanism).
> 
> There is some appropriate / notable discussion about the pros / cons of JSON vs YAML in #194 & a bit of commentary on #504. There was also a user submitted script for updating legacy YAML data to JSON that we might be able to leverage in #388..  Since it's a non backwards compatible change, if we do decide to go this route, it would probably need to be part of a major version release.

Let's pick up this discussion again in a few months, after we get 4.0 out the door.

**Comment by seanlinsley** [comment]
This is how I'd imagine you could provide backwards compatibility.
```ruby

def serializer
  @serializer ||= determine_serializer
end

def determine_serializer
  record = PaperTrail::Version.where.not(object: [nil, '', '{}']).first
  return :json unless record
  object = record.attributes_before_type_cast['object']

  begin
    JSON.parse object
    return :json
  rescue JSON::ParserError
  end

  begin
    YAML.load object
    return :yaml
  rescue YAML::SyntaxError
  end

  fail <<-ERROR.strip_heredoc
    Could not determine whether your existing version history was encoded in JSON or YAML.
    Please check the data in this record with:
    `PaperTrail::Version.find(#{record.id}).attributes_before_type_cast['object']`
  ERROR
end
```

If later on you wanted to force people to specify YAML in their config file, you could change this part:
```ruby
  begin
    YAML.load object
    fail "paper_trail 5.0 requires that you specify YAML as your serializer (JSON is now the default)"
  rescue YAML::SyntaxError
  end
```

**Comment by jaredbeck** [comment]
That's a neat idea, Sean.  I hadn't thought of detecting the current format.

Another idea, if we do want to change the default serializer, which hasn't been decided, would be to add a warning in 4.1, telling people that it's going to change in 5.0, and asking them to call `PaperTrail.serializer=` explicitly if they want to keep YAML.  It's a bit more work for people, but wouldn't introduce any code that we'd have to maintain.

**Comment by adrianoresende** [comment]
How i switch the default serializer inside project?
Sorry, I'm new to understand that =P

**Comment by jaredbeck** [comment]
> How i switch the default serializer inside project?

See https://github.com/airblade/paper_trail#using-a-custom-serializer

**Comment by jaredbeck** [comment]
> Another idea, if we do want to change the default serializer, which hasn't been decided, would be to add a warning in [one version], telling people that it's going to change in [the next version]

Here's one possible implementation of such a warning: https://github.com/airblade/paper_trail/pull/774

Regarding the difference in size, btw, [I'm seeing about 3% savings using JSON][1], so nothing really exciting there. Assuming that 3% figure is correct, then if size were the only reason, I'd say this isn't worth bothering people with a breaking change. I'll have to refresh my memory on the other pros and cons ..

[1]: https://gist.github.com/jaredbeck/ebfb3a2b579a5ed61ebf80edcdbb3e76

**Comment by brodock** [comment]
By going the JSON route you can benefit from `json` and `jsonb` column types on PostgreSQL:
http://www.postgresql.org/docs/9.4/static/datatype-json.html (jsonb has better performance and is available from 9.4+).

This also enables queries to be made against stored data

**Comment by seanlinsley** [comment]
My major reason to use JSON is for the `jsonb` data type in Postgres, which allows you to query the JSON payload (and apply indexes to it).

> Another idea, if we do want to change the default serializer, which hasn't been decided, would be to add a warning in [one version], telling people that it's going to change in [the next version]

As long as we still raise an error with explainer text in the major version bump, that sounds fine.
```ruby
  begin
    YAML.load object
    fail "paper_trail 5.0 requires that you specify YAML as your serializer (JSON is now the default)"
  rescue YAML::SyntaxError
  end
```

**Comment by seanlinsley** [comment]
The SQL to query `json` / `jsonb` is kinda gnarly, so if we switched to JSON as the default I'd like to see Paper Trail provide methods to query `object` and `object_changes`. For example:

```ruby
User.versions.attribute_changed :name
User.versions.attribute_changed :name, from: nil, to: 'Nick'

**Comment by jaredbeck** [comment]
There seems to be some confusion here between JSON in a text column, and json/b columns. Let me try to clarify. PT supports three formats:

1. PT responsible for serializing with YAML, saving in text column
1. PT responsible for serializing with JSON, saving in text column
1. AR responsible for serializing with JSON, saving in json/b column

In other words, if you use a postgres json/b column, your chosen `PaperTrail.serializer` will be ignored and AR will be responsible for serialization.

**Comment by priyaqfor** [comment]
Can we convert serializing with JSON only for particular models, irrespective of changing it in config. In other words, i need YAML for some models and JSON for some models. How could i achieve it?

**Comment by jaredbeck** [comment]
> Can we convert serializing with JSON only for particular models, irrespective of changing it in config. In other words, i need YAML for some models and JSON for some models. How could i achieve it? FYI, am using paper_trail-1.6.5.

Hi @priyaqfor Your question is unrelated to this issue, and does not have a simple answer. Please ask usage questions on S.O. http://stackoverflow.com/questions/tagged/paper-trail-gem

**Comment by jaredbeck** [comment]
> Regarding the difference in size, btw, I'm seeing about 3% savings using JSON, so nothing really exciting there. Assuming that 3% figure is correct, then if size were the only reason, I'd say this isn't worth bothering people with a breaking change.

Closing; Given that a 3% savings on disk is the only benefit, I don't think this is worth a breaking change.

**Comment by seanlinsley** [comment]
The benefit of switching to JSON (and really JSON) is that it allows you to query against it. That's specifically why we use it. It can be very useful for accomplishing real-world business needs.

**Comment by jaredbeck** [comment]
> The benefit of switching to JSON (and really JSONB) is that it allows you to query against it. 

I agree. Unfortunately, the PT default cannot be JSONB because we support MySQL and sqlite, and JSONB is Postgres-only. :(

**Comment by seanlinsley** [comment]
Right, but having JSON as the default is a good stepping stone. When your existing data is stored as a JSON string, it's very easy to start using the JSONB data type in Postgres.

**Comment by seanlinsley** [comment]
Other than the migration pain for existing YAML users, there's no significant downside to using JSON instead of YAML. Even for those not using Postgres, JSON could be viewed as preferable because it's much more easily human-readable.

**Comment by seanlinsley** [comment]
In the interest of not upsetting the apple cart, we could simultaneously make it easy / automatic for existing YAML users to continue using paper trail without any changes, while also making JSON the default serialization, thus improving the new user experience & making conversion to Postgres & JSONB very simple.

**Comment by seanlinsley** [comment]
If Paper Trail also had optional query methods, it would essentially be a nice value-add to switch to Postgres and use JSONB. "What to create reports based on your change history?"

**Comment by jaredbeck** [comment]
> .. having JSON as the default is a good stepping stone. When your existing data is stored as a JSON string, it's very easy to start using the JSONB data type in Postgres.

That's a good point.

> Other than the migration pain for existing YAML users, there's no significant downside to using JSON instead of YAML.

I agree, and we would never make people migrate from YAML. PT would continue to support YAML.

> .. make it easy / automatic for existing YAML users to continue using paper trail without any changes, while also making JSON the default ..

Right, we would only change the default for new PT installations.

> .. add a warning in [next minor version], telling people that it's going to change in [next major version], and asking them to call PaperTrail.serializer= explicitly if they want to keep YAML. It's a bit more work for people, but wouldn't introduce any code that we'd have to maintain.

This is still my preferred implementation. Are you still thinking about format detection? I'm concerned that would be complicated. We've had trouble before trying to use the database connection during app boot.

**Comment by batter** [comment]
It's a complicated issue. I don't love the idea of requiring a serializer to specified since that adds complexity in setup.

> Right, we would only change the default for new PT installations.

This is also complex as you mentioned. Maybe you could do something during the initial read / write, or even during initialization of the gem where it looks to see what format existing records are in (if there are any) and duplicates that, otherwise uses JSON by default? I don't think theres a perfect solution here.

**Comment by jaredbeck** [comment]
Thanks for the feedback everyone. Given that the limited benefits don't justify a major breaking change, and given our concerns about the complexity of non-breaking solutions, I think we can close this for now.
