### ISSUE TITLE
Storing versions in JSON

### ISSUE THREAD

**Issue by dvisockas** [airblade/paper_trail#560]
I would like to use postgres JSON data type in PaperTrail::Version's object attribute so I could query however I want.

What do you think about adding a new option bundle exec rails generate paper_trail:install, so it would create it with JSON instead of text?

**Comment by batter** [comment]
Seems reasonable, however, it's pretty minimal work to just generate the default migration and then adjust the file to switch those columns to use `JSON` instead of `text`

**Comment by jaredbeck** [comment]
I agree with Ben.  It's not something I'd like to spend my time on, but I'd be happy to review a PR.  I'll close this issue.  Please feel free to open a PR.
