### ISSUE TITLE
Unable to open `PaperTrail::Version`

### ISSUE THREAD

**Issue by varunlalan** [airblade/paper_trail#562]
I wanted to add custom columns to `versions` table, thus I am trying to open `PaperTrail::Version` class. With following code, it doesn't even saves the versions.

```
# app/models/paper_trail/version.rb
module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern

    before_create :check_for_whodunnit, :track_changes

    private
      def check_for_whodunnit
        self.whodunnit.present?
      end

      def track_changes
        # something..
      end
  end
end
```
```
# config/initializers/paper_trail.rb
PaperTrail::Rails::Engine.eager_load!
```

I am on Rails `4.2.2` and ruby `2.2.2`. Gem version is `4.0.0.rc1`.

# UPDATE:
Modified code as:
```
require 'paper_trail/version'

class Version < PaperTrail::Version
  include PaperTrail::VersionConcern

  before_create :check_for_whodunnit, :track_changes

  private
    def check_for_whodunnit
      self.whodunnit.present?
    end

    def track_changes
      debugger
      1
    end
end
```

Now able to create but callbacks are being skipped. Any ideas?

**Comment by jaredbeck** [comment]
Thanks for the bug report.  We're still trying to figure out the best way for people to reopen or inherit from `PaperTrail::Version`.  How are you using the above class?  If I copied it into a new rails app, what steps could I take in the rails console to reproduce the issue?  Thanks.

**Comment by varunlalan** [comment]
Thanks for the reply @jaredbeck. To reproduce, create a model say: `Person`:

```
# app/models/person.rb
class Person < ActiveRecord::Base
    has_paper_trail
end
```

Added:
```
# app/models/version.rb
require 'paper_trail/version'

class Version < PaperTrail::Version
  include PaperTrail::VersionConcern

  before_create :check_for_whodunnit, :track_changes

  private
    def check_for_whodunnit
      self.whodunnit.present?
    end

    def track_changes
      debugger
      1
    end
end
```

Nothing to add in `initializers`.

Then, on rails console, did: `Person.create(name: "Hello")`.

I should expect control to stop at `debugger` added to `track_changes` method. But it isn't happening.

**Comment by varunlalan** [comment]
Did one silly mistake. Working now. Opened class in `initalizer`. 

Closing this issue.

**Comment by jaredbeck** [comment]
> Did one silly mistake. Working now. Opened class in initalizer.  Closing this issue.

Glad you figured it out!  You were re-opening the class in both the initializer and in app/models, and deleting the initializer fixed the problem?

**Comment by varunlalan** [comment]
Yes. Also, i had to open the class inside `paper_clip` folder in app/models to make it work. 

I guess this is the best way we can reopen `Version` class.
