### ISSUE TITLE
changest method is giving me all attributes even which are not changed

### ISSUE THREAD

**Issue by shoaib-techverx** [airblade/paper_trail#564]
Hi i am using paper trail with rails 4 my update code is as below
@cms_page.update(cms_page_params) in the view <%=v.changeset%> give me all atrributes even which are not changed is there any way to show only changed attributes?

**Comment by jaredbeck** [comment]
Do you have an `object_changes` column in your `versions` table?

> If you add an object_changes text column to your versions table, either at installation time with the rails generate paper_trail:install --with-changes option or manually, PaperTrail will store the changes diff (excluding any attributes PaperTrail is ignoring) in each update version. You can use the version.changeset method to retrieve it.
> https://github.com/airblade/paper_trail#diffing-versions

**Comment by jaredbeck** [comment]
Closing issue: need more information.  Please provide the requested information and we'll be happy to reopen the issue, thanks!

**Comment by momolog** [comment]
We are experiencing the same issue, also on rails 4. 
We do have a column `object_changes` in our `versions` table.

An example of a value in that column would be e.g.
```
---
estimated_delivery_date:
- 2020-12-16 23:59:59.999999000 Z
- 2020-12-16 23:59:59.999999999 Z
technician_id:
-
- 3
```

As you can see, the value of `technician_id` did change, the value of `estimated_delivery_date` did not.
It's still part of the changeset.

**Comment by momolog** [comment]
Oops, now that I pasted it, I see that the value **did** change. It's just that we do not show the sub second part in the frontend.
