### ISSUE TITLE
paper Trail for has many assoiations

### ISSUE THREAD

**Issue by techverx** [airblade/paper_trail#568]
Hi am using paper trail in mine product model and product has many prices. i want to all changes in product inclueding price changes how can i show in one go my code is like this.
in controller

```ruby
def products_versions
  @products=Spree::Product.all
end
and in view
 <% @products.each do |p|%>
  <% p.versions.each do |v| %>
    <tr id="" data-hook="admin_products_index_rows" class="odd">
      <td class="align-center"><%=v.created_at.to_date rescue ''%></td>
      <td class="align-center"><%=v.item.name rescue ''%></td>
      <td class=""><%=v.object_changes%></td>
      <td class="align-center"><%= v.event rescue ''%></td>
      <td class="align-center"><%= v.whodunnit rescue ''%></td>
   </tr>
  <% end %>
<%end%>
```

object changes or changest show only current object changes not  of associated record.
is there any way to show childern changes like price in mine case in this view?

**Comment by jaredbeck** [comment]
> object changes or changest show only current object changes not of associated record.
> is there any way to show childern changes like price in mine case in this view?

Yes.  I believe the readme covers this.

https://github.com/airblade/paper_trail#associations

You could, for example, use `reify(has_many: true)` on each product version.

**Comment by jaredbeck** [comment]
I haven't heard back from you, so I'm going to close this.  Please let me know if you still think there's an issue and we'll reopen it, thanks.
