### ISSUE TITLE
Ignoring and skipping attributes not working again?

### ISSUE THREAD

**Issue by TechFounder** [airblade/paper_trail#569]
Hi, I saw that this was an issue in the past.  In testing ignore and skips, it doesn't pass. I have a couple of simple skip and ignore fields .

```
class Case < Base
  has_paper_trail skip: [
                        :last_case_comment_at,
                        ],
                ignore: [
                        :created_at,
                        ]
```
And a simple test to see if they are indeed skipped and ignored.
```
    it 'should not track changes to skipped attributes' do
      count = @case.versions.length

      @case.update_attributes!(last_case_comment_at: Time.now)
      expect(@case.versions.length).to eql count
    end

    it 'should not track changes to ignored attributes' do
      count = @case.versions.length

      @case.update_attributes!(created_at: Time.now)
      expect(@case.versions.length).to eql count
    end
```
But for some reason the skips and ignores are being ignored.
```
 1) Case versioning should not track changes to skipped attributes
     Failure/Error: expect(@case.versions.length).to eql count
       
       expected: 1
            got: 2
       
       (compared using eql?)

 2) Case versioning should not track changes to ignored attributes
     Failure/Error: expect(@case.versions.length).to eql count
       
       expected: 1
            got: 2
       
       (compared using eql?)
```
I changed the ```count``` in my example to ```@case.versions.last.changeset``` to try to debug.
```
   it 'should not track changes to skipped attributes' do
      count = @case.versions.length

      @case.update_attributes!(last_case_comment_at: Time.now)
      expect(@case.versions.length).to eql @case.versions.last.changeset
   end
```
and saw that it was indeed creating another version.
```
  1) Case versioning should not track changes to skipped attributes
     Failure/Error: expect(@case.versions.length).to eql @case.versions.last.changeset
       
       expected: {"gender"=>["Female", "Female"], "birthdate"=>["1946-03-09", "1946-03-09"], "first_name"=>["Nolan", "Nolan"], "middle_name"=>["Jensen", "Jensen"], "last_name"=>["Walker", "Walker"]}
            got: 2
       
       (compared using eql?)
```
What gives?

**Comment by jaredbeck** [comment]
Where is `@case` defined in your test?  Is it in a `before` block?  Can you include that part of the test, please?

**Comment by TechFounder** [comment]
Sure thing. Here it is.
```
    before do
       PaperTrail.enabled = true
       @case = FactoryGirl.create(:case)
    end
```

**Comment by batter** [comment]
What does the Factory definition look like?

**Comment by TechFounder** [comment]
Hmm, now looking at the definition and how I've assigned a trait to the factory, did that dup the fields? Please take a look at the previous before action as I put back the trait that I thought had no baring on this? Or does it?

```
FactoryGirl.define do
  factory :case do
    specialty
    pcp                       { FactoryGirl.create(:user) }
    gender            { ['Male', 'Female', 'Other'].sample }
    birthdate         { Time.at((100.years.ago.to_f - Time.now.to_f)*rand + Time.now.to_f).to_date.to_s }
    first_name        { Faker::Name.first_name }
    middle_name       { Faker::Name.first_name }
    last_name         { Faker::Name.last_name }

  trait :unassigned do
      state 'unassigned'
      specialist              { FactoryGirl.create(:user, :specialist) }
      specialty
end
```

**Comment by jaredbeck** [comment]
I think have a fix for this, will be pushing a PR shortly.

**Comment by TechFounder** [comment]
Cool, thanks! I was beginning to think I am crazy.

**Comment by jaredbeck** [comment]
OK, I think https://github.com/airblade/paper_trail/pull/570 fixes at least one of your issues :)

**Comment by TechFounder** [comment]
Thanks a bunch!

**Comment by jaredbeck** [comment]
Through the awesomeness that is Bundler, you can try out the branch from #570 like so:

```ruby
gem 'paper_trail', github: 'airblade/paper_trail', branch: 'issue_569_notable_updated_at'
```

Let me know how that goes for you.

**Comment by TechFounder** [comment]
Ok, let me give that a try now...

**Comment by TechFounder** [comment]
Ok, that didn't fix it but If were to remove the trait in my factory of case, the test passes. So if I had this:
```
before do
       PaperTrail.enabled = true
       @case = FactoryGirl.create(:case)
end
```
It passes. I wonder why adding a trait would cause it to do that?

**Comment by TechFounder** [comment]
I'll take another look at this in the morning. Thanks.

**Comment by TechFounder** [comment]
You know what? Since removing the trait makes the test pass, I'm going to just chalk it up to a problem on my end. I'll close this out, thanks for your help!

**Comment by jaredbeck** [comment]
Great.  Thanks for the bug report!

**Comment by TechFounder** [comment]
One question, should I change my gemfile back to ```gem 'paper_trail', '~> 4.0.0.rc'```? or wait until that branch is merged? Not sure what I should do here since I'm not sure if your fix fixed my problem or just removing the trait did?

**Comment by jaredbeck** [comment]
That's kind of a complicated question.  For example, you should only use released gems in production, ideally.  For development, use what works, I guess.  ¯\_(ツ)_/¯

**Comment by jaredbeck** [comment]
Jimmy, There's a `v4.0.0.rc2` you can use now, which contains https://github.com/airblade/paper_trail/pull/570

**Comment by TechFounder** [comment]
Jared, thanks very much!
