### ISSUE TITLE
Load the correct instance version from some model in a relationship

### ISSUE THREAD

**Issue by tiagozc** [airblade/paper_trail#573]
Hi

First, this is not a bug, is a question that i have not being able to find the answer through documentation and web search.
 
I would like to know if working with associations is possible to auto load a reference of a version instance specific of some model, for example, imagine i have Messages and Contacts models.

So, an instance of Contact has id: 2, number: 12345 and name: "Jake", and that instance was referenced in a Message with id 1.
  
After 1 month, this same Contact for any reason have its name changed to John.

After 2 months, when i get Message id 1, and get the Contact associated, i want to know that when this Message was saved the name for this contact was Jake, not John (current), something like automatically load the correct instance version in a relationship.

I would like to know if paper_trail could do this automatically for me, and if not, which is the best approach for deal with? Storing the id from version's table as a foreign key in Message? 

Thanks

**Comment by tiagozc** [comment]
Well, after some tests and read a lot more, i realized that paper_trail was not designed for that, at least is what appear to be, because there is no current version.

**Comment by batter** [comment]
> I would like to know if paper_trail could do this automatically for me, and if not, which is the best approach for deal with? Storing the id from version's table as a foreign key in Message?

That sounds like it would likely be the best approach.  You should also look at the [README section regarding storing metadata](https://github.com/airblade/paper_trail#storing-metadata), which may be helpful when retrieving specific pieces of information (like `name` in this case) which you may be retrieving repeatedly.

**Comment by tiagozc** [comment]
I decided save the index value, not the id from version's table, and if equals 0 just use the live one, if not load the correspondent index.

**Comment by batter** [comment]
You can also call `.live?` on a model instance when it is versioned to determine whether it is the `live` instance (the one currently in the database) or not
