### ISSUE TITLE
Rails 5 Deprecation Warning

### ISSUE THREAD

**Issue by jbcden** [airblade/paper_trail#581]
Hello, I am running PaperTrail 3.0.8 and have gotten the deprecation message to disappear just by adding the require to the spec_helper as per [this](https://github.com/airblade/paper_trail/issues/416). I am wondering if I still need to run the generator and migrations as they suggested or not. I am running rails 4.2.2.

**Comment by batter** [comment]
Please upgrade to PaperTrail 4.0 and the deprecation warnings will disappear.  See [this section of the README for more info](https://github.com/airblade/paper_trail#serializedattributes-support).
