### ISSUE TITLE
Association failing | has many through has_one 

### ISSUE THREAD

**Issue by erdostom** [airblade/paper_trail#585]
My setup is like this:

Doctor --(has_one)--> Practice --(has_many)--> Addresses

I get an error when I try to `doctor.versions.last.reify(has_one: true, has_many: true)`

**Comment by erdostom** [comment]
Guessing this is dupe of #498

**Comment by jaredbeck** [comment]
> I get an error

What error?

Are you able to reproduce this issue in a brand new rails app with the latest version of paper_trail?

**Comment by jaredbeck** [comment]
Closing.  Please provide the requested information and we'll be happy to reopen this issue.
