### ISSUE TITLE
Adding a summary of changeset for each version

### ISSUE THREAD

**Issue by campgurus** [airblade/paper_trail#591]
This gem is working perfectly.  In our app we have an Articles table where each Article has versions that get created whenever @article is updated.  We use a history view to display changeset, but for average users, it is often difficult to see what exactly has changed.

Here is my potential solution, allow editors to manually enter a text_field :summary such as "added a name" in a separate model or as a column in the Versions table.  Then in the history view, show the manually entered text fields for a mor user friendly view.

Before I start adding columns or methods to the Versions model, is there a way that solves this problem within the gem already?

**Comment by batter** [comment]
There sure is, take a look at the [metadata column portion of the README](https://github.com/airblade/paper_trail#storing-metadata).  It's designed for just this sort of custom column storage usage.

**Comment by campgurus** [comment]
Thanks!
