### ISSUE TITLE
request: provide a script for migrating :text column types to :json column types for postgres

### ISSUE THREAD

**Issue by izelnakri** [airblade/paper_trail#600]
I cant simply change the column type since :text column has serialized object. Could we have a papertrail command perhaps to create a rails migration script with custom SQL + deserialization?

**Comment by jaredbeck** [comment]
So you have a `text` column now, and you'd like to have a `json` column instead?

Instead of a script, could you add the new json column, update it from the text column, and then drop the text column?

```sql
alter table bananas add column data_json json;
update bananas set data_json = data_text::json;
alter table bananas drop column data_text;
alter table bananas rename column data_json to data;
```

You will get an error if any values in `data_text` are invalid json, but a script wouldn't be able to deal with those either.

I think this is a good solution, so I'm going to close this issue.  Please let me know if it doesn't work for you.

**Comment by jaredbeck** [comment]
Actually, an intermediate column is not required. This can be done in a single command with a `using` clause.

```sql
alter table versions alter column object type json using object::json;
```

**Comment by jaredbeck** [comment]
I've added a note about this to the readme: https://github.com/airblade/paper_trail/commit/a1108a66d3593c275be25774458f9e1bf115756d

**Comment by izelnakri** [comment]
My text column data is YAML serialized (default behavior or paper_trail) thus Im not sure if that SQL would work. What do you think? Could you reopen this ticket ?

**Comment by jaredbeck** [comment]
> My text column data is YAML ..

Well, you're definitely going to need a script then.  :)  If you want to write one, I think we'd be happy to include it in PaperTrail.

**Comment by batter** [comment]
If you have legacy data that is already serialized in the `YAML` format, then you can take a look at [this comment](https://github.com/airblade/paper_trail/issues/388#issuecomment-47767562) on #388 for some insight as to how to convert that data to `JSON` format.

**Comment by jaredbeck** [comment]
>> My text column data is YAML ..
> 
> Well, you're definitely going to need a script then. :) If you want to write one, I think we'd be happy to include it in PaperTrail.

As there has not been any activity on this in a month, I'm going to close the issue.  If someone wants to write such a script, please open a PR, thanks!
