### ISSUE TITLE
Looking for advice: typecasting a ruby range to and from a string

### ISSUE THREAD

**Issue by johnnymo87** [airblade/paper_trail#601]
Hi!

I have a question that might be more appropriate for rails/rails, but I'll ask it here first because it came up while using this (awesome) gem.

I've got a model with paper trail, and I'm adding a `daterange` column to the model (see: [range types](http://edgeguides.rubyonrails.org/active_record_postgresql.html#range-types)). Things go wrong when reifying versions of the model because the json snapshots the range as `2014-01-01...2015-01-01`, and rails blows up when trying to typecast this back to a range. After digging into the source code a little, I see that rails' postgres adapter expects the range string to be `[2014-01-01,2015-01-01)`. 

My question is ... is there a cleaner way to handle this than monkey-patching things? Here's what I monkey-patched:

In `app/lib/range.rb`:
```
# Monkey-patch some active_support monkey-patches of ruby's Range class
#
# I'm doing this so that when casting the range to a string, it comes out as a
# string that rails' postgresql adapter knows how to parse back into a range.
#
# E.g. Date.new(2014, 1, 1)...Date.new(2015, 1, 1) -> '[2014-01-01,2015-01-01)'
#      rather than
#      Date.new(2014, 1, 1)...Date.new(2015, 1, 1) -> '2014-01-01...2015-01-01'
#
# The rails code responsible for parsing this string back into a range resides
# in lib/active_record/connection_adapters/postgresql/oid.rb


# lib/active_support/core_ext/range/conversions.rb
Range::RANGE_FORMATS[:postgresql] = ->(start, stop, exclude_end) do
  upper_bound = exclude_end ? ')' : ']'
  "[#{start.to_s(:db)},#{stop.to_s(:db)}#{upper_bound}"
end

# lib/active_support/core_ext/object/json.rb
class Range
  def to_formatted_s(format = :default)
    if formatter = RANGE_FORMATS[format]
      if format == :postgresql
        formatter.call(first, last, exclude_end?)
      else
        formatter.call(first, last)
      end
    else
      to_default_s
    end
  end

  def as_json(options = nil)
    to_formatted_s(:postgresql)
  end
end
```
In `spec/lib/range_spec.rb`:
```
require 'spec_helper'

describe Range do
  describe '#as_json' do
    context 'upper bound included' do
      it 'delimts the upper bound with a ]' do
        expect(
          (Date.new(2014, 1, 1)..Date.new(2015, 1, 1)).as_json
        ).to eq '[2014-01-01,2015-01-01]'
      end
    end

    context 'upper bound excluded' do
      it 'delimts the upper bound with a )' do
        expect(
          (Date.new(2014, 1, 1)...Date.new(2015, 1, 1)).as_json
        ).to eq '[2014-01-01,2015-01-01)'
      end
    end
  end
end
```
And in `config/initializers/range_formats.rb`:
```
load File.join(Rails.root, 'app/lib/range.rb')
```

**Comment by jaredbeck** [comment]
So, if I understand, ActiveSupport and ActiveRecord can't agree on how to serialize a date range?  I think you're right, this should be a bug report on rails.  PaperTrail simply uses `ActiveSupport::JSON.encode`, though it does allow you to use a custom serializer (https://github.com/airblade/paper_trail#using-a-custom-serializer).  Maybe writing a custom serializer would be better than patching ActiveSupport?
