### ISSUE TITLE
Running the generator with `--with-changes` isn't creating `object_changes` column

### ISSUE THREAD

**Issue by lucascaton** [airblade/paper_trail#602]
Doc reference: https://github.com/airblade/paper_trail#diffing-versions

**Comment by batter** [comment]
Please provide some additional information about your environment, activerecord version, etc.

**Comment by lucascaton** [comment]
Weird, it worked now. Probably was my mistake, sorry about that.

Just to futher reference if ever needed, my current versions are:
* Ruby: 2.2.2
* Rails: 4.2.4

I'm closing this issue, thanks anyway.

**Comment by batter** [comment]
:+1:
