### ISSUE TITLE
user_for_paper_trail method defined different controller not working

### ISSUE THREAD

**Issue by shail** [airblade/paper_trail#603]
```
  class DemandControlsController < Shared::BaseController
     def user_for_paper_trail
       current_user.try(:username)
     end
  end
```

I'm trying to define the `user_for_paper_trail` method directly in this DemandControls controller; I've also tried to define it in `Shared::BaseController` but the `whodunnit` column in my versions table keeps showing up as `NULL`. Does it specifically have to be defined as a method in the `ApplicationController` class?

**Comment by shail** [comment]
So `Shared::BaseController` inherits from `::ActiveController::Metal` rather then `ActiveController:Base`. Is there a particular module that `PaperTrail` relies on that I can include rather than having to include a bunch of unneeded modules?

**Comment by jaredbeck** [comment]
> So `Shared::BaseController` inherits from `::ActiveController::Metal` rather then `ActiveController:Base`. Is there a particular module that `PaperTrail` relies on that I can include rather than having to include a bunch of unneeded modules?

Maybe you can include `::AbstractController::Callbacks`?  I'm not sure, but maybe `::ActionController::Metal` does not support callbacks.  PaperTrail's `user_for_paper_trail` depends on callbacks.
