### ISSUE TITLE
`set_paper_trail_whodunnit` runs before `current_user` is set

### ISSUE THREAD

**Issue by mrryanjohnston** [airblade/paper_trail#604]
I'm using devise-token_authenticatable to authenticate users. I have a `before_action` in the ApplicationController that runs `sign_in`. This authenticates our user, setting the current_user variable in the controller. paper_trail's `set_paper_trail_whodunnit` method seems to be run before this before_action gets run, causing the whodunnit column to be blank in our versions table. What are my options to work around this issue?

**Edit**
I worked around this issue by adding the following lines after my before_action:
```ruby
before_action :set_paper_trail_enabled_for_controller
before_action :set_paper_trail_whodunnit, :set_paper_trail_controller_info
```
Now I just wonder if this is something I can configure such that my authentication will be called before these methods by default.

**Comment by batter** [comment]
There is a PR open for trying to address this very issue: #556.  This has been a longstanding concern, so if you want to help contribute / review that PR that would be beneficial to all.

**Comment by mrryanjohnston** [comment]
Ah, thanks for the heads up. I'm not a paper_trail expert, but the changes in the pr look like they'll get the job done.

**Comment by jaredbeck** [comment]
Fixed in `master` via https://github.com/airblade/paper_trail/pull/556, scheduled for release 5.0.
