### ISSUE TITLE
info_for_paper_trail not set when logging in

### ISSUE THREAD

**Issue by tristanoneil** [airblade/paper_trail#609]
Using the latest version of PaperTrail it seems that when logging in using Devise the attributes set on the version using `info_for_paper_trail` are all nil. A new version of `User` is created as expected but the additional attribute I'm setting using `info_for_paper_trail` just doesn't get set. If I override [this method](https://github.com/airblade/paper_trail/blob/master/lib/paper_trail.rb#L90) and return a static hash it works so it makes me think something is awry with `RequestStore`. `info_for_paper_trail` works for all other things just not when a new version is created resulting from logging in.

**Comment by batter** [comment]
`info_for_paper_trail` or `user_for_paper_trail`?  What attributes are you attempting to set? Is it necessary for the user to be signed in for those attributes to be accessible? If so, you're likely suffering from the same issue that is documented in #604?

**Comment by tristanoneil** [comment]
@batter `info_for_paper_trail` our exact implementation looks like:

```ruby
def info_for_paper_trail
  { ip_address: request.remote_ip }
end
```

**Comment by batter** [comment]
Are you sure that `PaperTrail.enabled_for_controller?` is returning `true` in the spot where you are making the update to the model that is causing version generation in this context?

Also, what version of PaperTrail are you using?  And is this happening when you manually trigger this, or inside your test suite?

**Comment by tristanoneil** [comment]
@batter Yes `PaperTrail.enabled_for_controller?` returns true. It happens both in our test suite and manually from the app as well. If it gives you more context this is the spec that fails.

```ruby
scenario "A user logs in" do
  with_versioning do
     user = create :user

    When "A registered user signs in" do
      member_sign_in_as user # logs in the user in w/ capybara
    end

    Then "a papertrail version is recorded for the user with an ip address" do
      expect(user.versions).not_to be_empty
      expect(user.versions.last.ip_address).to eq("127.0.0.1")
    end
  end
end
```

So our application is currently using 3.0.6 and the above spec passes but when upgrading to 4.0.0 `user.versions.last.ip_address` returns nil. Again this only happens in the case where a new version is created because a user logs in `info_for_paper_trail` sets `Version#ip_address` correctly in all other cases. A new version _is_ created when the user signs in as Devise sets various attributes on the user, just `ip_address` is is set to `nil` for some reason.

**Comment by batter** [comment]
With PaperTrail version 3.x, the RSpec (and Cucumber) test helper was enabled by default. with version 4.x it is no longer enabled by default, so if you want to use context blocks like `with_versioning` or metadata specifiers in your specs like `:versioning => true`, then you will need to manually require them into your test helper. You can [read about how to do this on the README section about RSpec](https://github.com/airblade/paper_trail#rspec). Forgive me if you're already aware of this, but this jumps out to me as the most obvious difference that could be causing different behavior between the 2 versions during upgrading.

**Comment by tristanoneil** [comment]
@batter Yep we're requiring `'paper_trail/frameworks/rspec'` in our spec helper, the spec in question is still failing though :confused:

**Comment by jaredbeck** [comment]
Are you sure that your `info_for_paper_trail` method is called?

**Comment by tristanoneil** [comment]
@jaredbeck Yes so I added a puts statement to `info_for_paper_trail` and ran the spec I shared above with `focus: true` and it resulted in the following.

![screen shot 2015-09-15 at 12 16 09 pm](https://cloud.githubusercontent.com/assets/316507/9882632/af12ce2a-5ba3-11e5-8c33-19bde8c1c944.png)

This is what `info_for_paper_trail` looked like when I ran the spec.

```
def info_for_paper_trail
  pr request.remote_ip
  { ip_address: request.remote_ip }
end
```

**Comment by tristanoneil** [comment]
I tried using the master version of PaperTrail and the above spec now passes so maybe this will be a non-issue in future releases. ¯\_(ツ)_/¯ for now I think we're just going to point at the latest master commit.

**Comment by jaredbeck** [comment]
I'm glad you found a workaround. I will tentatively close this issue. If you figure out how to reproduce the issue in a new rails app using a released version of the gem, or better yet can provide a failing test case, please let us know and I'll be happy to reopen this issue.
