### ISSUE TITLE
How i use method of model (item) in object of version?

### ISSUE THREAD

**Issue by adrianoresende** [airblade/paper_trail#624]
When i show version with same HTML model#show, i need convert object to ActiveRecord to work method?

I not know whats is best way for use method in object of version.

I try `Model.new(YAML.load @version.object)` but i have erro with mass-assign.

Some one help me?

**Comment by batter** [comment]
If you have access to the version object why not just call `@version.reify`?

**Comment by adrianoresende** [comment]
Thanks! =)
