### ISSUE TITLE
README instructions on installation should include --with-changes at top

### ISSUE THREAD

**Issue by richaagarwal** [airblade/paper_trail#634]
For paper_trail to work as intended, you need to have a column `with_changes` in your Versions table. Currently, this information is provided in the diffing_versions section (https://github.com/airblade/paper_trail#diffing-versions) but not up top when someone is installing the gem for the first time (https://github.com/airblade/paper_trail#installation).  It'd be helpful to newcomers if this information was presented sooner than later, since the default option doesn't seem to provide much value.

**Comment by jaredbeck** [comment]
> For paper_trail to work as intended, you need to have a column with_changes in your Versions table. 

The **column** is called `object_changes`. The **generator option** is `--with-changes`. PaperTrail is designed to work (and is faster) without the `object_changes` column.

> Currently, this information is provided in the diffing_versions section (https://github.com/airblade/paper_trail#diffing-versions) but not up top when someone is installing the gem for the first time (https://github.com/airblade/paper_trail#installation). It'd be helpful to newcomers if this information was presented sooner than later, since the default option doesn't seem to provide much value.

I want to keep the top of the readme simple, but I wouldn't mind adding a section of the readme about the generator, and linking to that section from the top.  Do you want to try writing such a section? The source for the generator and its specs can be found here:

- https://github.com/airblade/paper_trail/blob/master/lib/generators/paper_trail/install_generator.rb
- https://github.com/airblade/paper_trail/blob/master/spec/generators/install_generator_spec.rb

Thanks!

**Comment by ACPK** [comment]
+1

**Comment by jaredbeck** [comment]
Closed by a287d6e
