### ISSUE TITLE
[] and []= declaration causes PaperTrail to fail.

### ISSUE THREAD

**Issue by z80** [airblade/paper_trail#650]
Hello!

I've found that if I declare [] and []= operators in a model with "has_paper_trail" it fails to save versions with exactly the same symptoms as here https://github.com/airblade/paper_trail/issues/422.

But if I comment out [] and []= or rename them into something else, for example, param()/setParam() it works normally.

**Comment by jaredbeck** [comment]
> .. if I declare [] and []= operators in a model with "has_paper_trail" it fails to save versions ..

Those **methods** (`[]` and `[]=` are methods, not operators) are defined by ActiveRecord.  Unless you have a really good reason, you shouldn't be overwriting them.  Are you at least calling `super`?

**Comment by z80** [comment]
100% clear, thank you! Sorry for disturbing without real reason!

**Comment by jaredbeck** [comment]
No problem. I'm glad I could help!
