### ISSUE TITLE
Get object at a given version

### ISSUE THREAD

**Issue by arunthampi** [airblade/paper_trail#653]
I'm trying to get the contents of an object *at* a given version and so I'm using reify, but looks like `reify` gives the object *just before* the given version, so I'm doing this in the code:

```ruby
version = install.app.versions.find_by(ref: ref)
app = version.event == 'create' ? install.app : version.reify
app.code = version.changeset['code'].last
```
Is this the correct way or am I missing something?

Thanks in advance!

**Comment by batter** [comment]
`reify` restores the object with the attributes that are stored on a given version. You are correct that an object stores the state of an object prior to a change that occurs on the object that causes the version to be generated, [as stated in the README under Basic Usage instructions](https://github.com/airblade/paper_trail#basic-usage).

Perhaps you could either use call `app.versions.version_at(timestamp)`, or simply call `version.next` to grab the next version in the sequence (i.e. the version that corresponds to the change you are trying to fetch).

These past issues may be of help too: #425, #417, #385, #185

**Comment by arunthampi** [comment]
Got it thanks!

On Tuesday, November 24, 2015, Ben Atkins <notifications@github.com> wrote:

> reify restores the object with the attributes that are stored on a given
> version. You are correct that an object stores the state of an object prior
> to a change that occurs on the object that causes the version to be
> generated, as stated in the README under Basic Usage instructions
> <https://github.com/airblade/paper_trail#basic-usage>.
>
> Perhaps you could either use call app.versions.version_at(timestamp), or
> simply call version.next to grab the next version in the sequence (i.e.
> the version that corresponds to the change you are trying to fetch).
>
> These past issues may be of help too: #425
> <https://github.com/airblade/paper_trail/issues/425>, #417
> <https://github.com/airblade/paper_trail/issues/417>, #385
> <https://github.com/airblade/paper_trail/issues/385>, #185
> <https://github.com/airblade/paper_trail/issues/185>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airblade/paper_trail/issues/653#issuecomment-159381802>
> .
>


-- 
It's better to be a pirate than join the Navy - Steve Jobs
http://mclov.in | @iamclovin
