### ISSUE TITLE
Creating version_associations after installation

### ISSUE THREAD

**Issue by caccac** [airblade/paper_trail#654]
I'm using paper_trail without version_association table cause I didn't need it before. But now my versioning model has has_many association now, and I need to track this association.

On readme file there is no explanation how to create version_association table.

So how will I create the version_association table manually after installing paper_trail?

Thanks in advance for your answers.

**Comment by jaredbeck** [comment]
> [In the] readme file there is no explanation how to create version_association table.
> 

There is such an explanation in the section titled "Associations".

> .. create a version_associations table, either at installation time with the rails generate paper_trail:install --with-associations option or manually ..
>

**Comment by jaredbeck** [comment]
To clarify, it's ok to run the `paper_trail:install --with-associations` generator even if you've already run `paper_trail:install` in the past. You'll just get a warning saying that the `create_versions` migration file already exists.

```
 bin/rails g paper_trail:install --with-associations
ALERT: Migration already exists named 'create_versions'. Please check your migrations directory before re-running
      create  db/migrate/20151125162339_create_version_associations.rb
      create  db/migrate/20151125162340_add_transaction_id_column_to_versions.rb
```

**Comment by caccac** [comment]
Thanks @jaredbeck
