### ISSUE TITLE
v4.0.0 regression? Inside if proc, the updated_at is already updated 

### ISSUE THREAD

**Issue by gamov** [airblade/paper_trail#656]
Given:
```ruby
class ItemVariant < ActiveRecord::Base
  has_paper_trail :on => [:update, :destroy],
                  :class_name => 'ItemVariantVersion',
                  if: proc {|t| t.changed? && (t.updated_at < Time.current - 1.week)}
end

# then when
iv = ItemVariant.new
iv.save! # no version
iv.updated_at = 2.weeks.ago; iv.save!
iv.first_name = 'this should trigger versioning'
iv.save! # => should create version
```
Starting with version 4.0.0, new version is never created because attribute 'updated_at' in the if proc is **already** updated to now. Works fine under 3.0.8.

I'm not familiar enough with the codebase but it might be related to this pull request: https://github.com/airblade/paper_trail/pull/563

**Comment by jaredbeck** [comment]
This was a deliberate change in 4.0.0, specifically https://github.com/airblade/paper_trail/pull/375.

You can change your proc as follows:

```diff
- if: proc {|t| t.changed? && (t.updated_at < Time.current - 1.week)}
+ if: proc {|t| t.changed? && (t.updated_at_was < Time.current - 1.week)}
```

This breaking change in 4.0.0 is documented in https://github.com/airblade/paper_trail/blob/master/CHANGELOG.md as follows:

> #375 / #374 / #354 / #131 - Versions are now saved with an after_ callback, instead of a before_ callback. This ensures that the timestamp field for a version matches the corresponding timestamp in the model.

Thanks for opening the issue, I can see why you'd think it was a regression, but it was deliberate.

**Comment by gamov** [comment]
oic, thanks @jaredbeck! It makes sense now. I find it a bit counter-intuitive though, maybe it would be good to mention it in the doc, especially under 'Choosing When To Save New Versions'.

**Comment by jaredbeck** [comment]
> .. maybe it would be good to mention it in the doc, especially under 'Choosing When To Save New Versions'.

That would be helpful, thanks. Please submit a PR.
