### ISSUE TITLE
set_paper_trail_whodunnit included by default?

### ISSUE THREAD

**Issue by dgobaud** [airblade/paper_trail#659]
Documentation says "If your controller has a current_user method, PaperTrail provides a before_filter that will assign current_user.id to PaperTrail.whodunnit. You can add this before_filter to your ApplicationController." This implies the user must add the before_filter for it to be used however it seems to be on by default. I am also using rails_admin - it is possible it is setting it for me.

**Comment by dgobaud** [comment]
Looking through rails_admin code it does not seem to set set_paper_trail_whodunnit anywhere.

**Comment by jaredbeck** [comment]
Sounds like you're reading the documentation from the `master` branch. Are you actually using `master`?

The change you're referring to (https://github.com/airblade/paper_trail/pull/556) is scheduled to be released in PaperTrail 5.0.

Please tell me more about rails_admin. When we do release PT 5.0 (date TBD) do you anticipate this change causing trouble for rails_admin users?

**Comment by dgobaud** [comment]
Ah I see. No I'm using 4.0.0. So in 4.0.0 it is on by default correct? I think this will cause a problem for users updating to 5.0.0 if they don't realize the change because whodunnit will stop automatically working. I would mention the change prominently in upgrade notes but I still bet some people will be surprised bye the behavior when whodunnit just stops working.

**Comment by jaredbeck** [comment]
> I would mention the change prominently in upgrade notes ..

Thanks, yeah it's in the changelog.

> .. but I still bet some people will be surprised because they won't read the notes and whodunnit will stop working.

I was worried about that too, so I added a runtime warning: https://github.com/airblade/paper_trail/pull/556/files#diff-bf98f65b6f18a50eec434b83a3a140f7R75

Will rails_admin users be able to add the callback? Does rails_admin give you enough control over your controllers?

**Comment by dgobaud** [comment]
Yeah I don't think rails_admin will have any conflict with this. rails_admin doesn't seem to limit what you can do in the controllers - you just add a section to them for rails_admin.

**Comment by jaredbeck** [comment]
> Yeah I don't think rails_admin will have any conflict with this.

Great, thanks.
