### ISSUE TITLE
Whodunnit additional settings

### ISSUE THREAD

**Issue by groony** [airblade/paper_trail#669]
Can you add Whodunnit callback?
This will be very cool feature to get user record without monkey patching.

**Comment by jaredbeck** [comment]
Per the readme:

> If your controller has a current_user method, PaperTrail provides a before_filter that will assign > current_user.id to PaperTrail.whodunnit. You can add this before_filter to your ApplicationController.
>
>     class ApplicationController
>       before_filter :set_paper_trail_whodunnit
>     end
> 
> https://github.com/airblade/paper_trail#finding-out-who-was-responsible-for-a-change

Is this what you are asking about?

**Comment by groony** [comment]
My thoughts:

```ruby
class Blog
  has_paper_trail whodunnit: { attribute: :id, klass: User }
end

user = Blog.find(1).versions.first.whodunnit_record
```
And we get User record or nil

**Comment by jaredbeck** [comment]
It is common to save a user id in the `whodunnit` but not everyone does, so the method you propose would not work for everyone.  Also, the user may no longer exist.  Given, those concerns, I'm hesitant to add a feature like that to PT.  

However, you can implement this feature in your own app by using a [custom version class][1].

```ruby
class MyVersion < PaperTrail::Version
  def whodunnit_record
    User.find(whodunnit.to_i)
  end
end

class Post < ActiveRecord::Base
  has_paper_trail :class_name => 'MyVersion'
end
```

Hope that helps!

[1]: https://github.com/airblade/paper_trail#custom-version-classes
