### ISSUE TITLE
Rails 5: belongs_to_required_by_default prevents versioning of destroy events

### ISSUE THREAD

**Issue by owenr** [airblade/paper_trail#682]
When using the ActiveRecord configuration belongs_to_required_by_default (set to true for new Rails 5 projects), PaperTrail::Version tries to validate presence of the versioned item. Since versioning is done after destroy (by default), no matching item exists and the version creation silently fails.

See https://gist.github.com/owenr/60b34a2cdc13edf89412 for a test using the bug report template.

Proposed fix: explicitly make the item relationship optional.

**Comment by jaredbeck** [comment]
`paper_trail_on_destroy` already supports a `before_destroy` instead of the default `after_destroy`.  Can we just change the default?

```ruby
def paper_trail_on_destroy(recording_order = 'after')
def paper_trail_on_destroy(recording_order = 'before')
```

If there are no drawbacks to changing the default, I'd prefer to keep the `belongs_to :item` relationship required.

**Comment by owenr** [comment]
The only drawback is that a reified model cannot be interrogated to see if it was destroyed. The version event still records the action. Since callback order is undefined in the current release, switching to `:before` seems to be a sensible approach.

**Comment by jaredbeck** [comment]
> .. switching to :before seems to be a sensible approach.

Great! Our test suite now supports ActiveRecord 5 (support added by https://github.com/airblade/paper_trail/pull/684) but is not passing on AR 5 yet. Once our test suite is passing on AR 5, we can write a failing test for this issue.
