### ISSUE TITLE
whodunnit is not set on Rails 5

### ISSUE THREAD

**Issue by boblin** [airblade/paper_trail#694]
I've created test app for this ticket to test https://github.com/boblin/papertrail_rails5_test

It is basically `rails 5.0.0.beta1` app + latest `Devise` + lates `Papertrail`.

```
Started GET "/posts/1/edit" for 127.0.0.1 at 2016-01-15 12:14:51 +0100
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by PostsController#edit as HTML
  Parameters: {"id"=>"1"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Post Load (0.2ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Rendered posts/_form.html.erb (11.1ms)
  Rendered posts/edit.html.erb within layouts/application (12.6ms)
user_for_paper_trail is present, but whodunnit has not been set.
PaperTrail no longer adds the set_paper_trail_whodunnit
before_filter for you. Please add this before_filter to your
ApplicationController to continue recording whodunnit. See the
PaperTrail readme for an example.
Completed 200 OK in 193ms (Views: 156.1ms | ActiveRecord: 3.9ms)
```

```
2.2.3 :001 > Post.last.versions.last.whodunnit
D, [2016-01-15T12:17:01.172292 #17458] DEBUG -- :   Post Load (0.5ms)  SELECT  "posts".* FROM "posts" ORDER BY "posts"."id" DESC LIMIT $1  [["LIMIT", 1]]
D, [2016-01-15T12:17:01.197660 #17458] DEBUG -- :   PaperTrail::Version Load (0.3ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."created_at" DESC, "versions"."id" DESC LIMIT $3  [["item_id", 1], ["item_type", "Post"], ["LIMIT", 1]]
 => nil 
```

**Comment by jaredbeck** [comment]
I think you are supposed to see this warning. Devise defines a `current_user` which PaperTrail uses in `user_for_paper_trail`. That is why the warning says "user_for_paper_trail is present". Did you not expect to see this warning?

If you don't want to track "who done it", you can override `user_for_paper_trail` to return `nil`

```ruby
# application_controler.rb
def user_for_paper_trail
  nil
end
```

or you can add the `set_paper_trail_whodunnit` callback per the instructions in the readme.

I'm open to suggestions about how to make this change less confusing to others.

This change was made so that users could control the order of callbacks. See https://github.com/airblade/paper_trail/issues/301 for discussion.

**Comment by boblin** [comment]
I see. My mistake :-) Thank you for help :-)

**Comment by jaredbeck** [comment]
Do you have any suggestions about how to make this less confusing to others?

**Comment by boblin** [comment]
Because this feature is probably wanted for most of users, I would definitely add this mention at beginning of readme here: https://github.com/airblade/paper_trail#basic-usage like:
1. you need to add `has_paper_trail` to model 
2. you need to add before_filter `set_paper_trail_whodunnit`

**Comment by jaredbeck** [comment]
Docs updated (https://github.com/airblade/paper_trail/commit/b9f23d729f057c05139f2ccd29c31b1b750e9a60). Thanks for the suggestion!

**Comment by boblin** [comment]
Perfect :+1: :smile:
