### ISSUE TITLE
Model methods such as `live?` can cause name conflicts

### ISSUE THREAD

**Issue by blakewest** [airblade/paper_trail#703]
It appears Papertrail defines a method "live?" on **every** instance of every model(https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/has_paper_trail.rb#L184). This seems a bit over-the-line to me. 
It caused a really unexpected bug on our end, where we had a flag called "live" on our model (which I presume is not a terribly uncommon flag name). We then expected to be able to use the "free" rails method of "live?", which automatically returns a boolean for that attribute (and is general ruby convention for booleans). Instead, it always returned true, which was **very very confusing** until we realized it was getting defined by Papertrail. And granted, it's already a boolean, and we don't have to use the "?" version, but that's standard ruby convention, and the current behavior seems unacceptable. 
We ended up just doing `undef :live?` right after `has_paper_trail` in our model, and now it's ok, but that's crazy.

Now I realize you can't just go breaking your API, and removing or renaming `live?`, but perhaps you could add an option to rename this method to like... `paper_trail_live?` or `live_version?` or most anything else that's more specific, and less likely to crash. I'd also be cool with an option to just not define it at all. We never use it.

**Comment by batter** [comment]
> It appears Papertrail defines a method "live?" on every instance of every mode

It is, and [is clearly documented in the API Summary on the README](https://github.com/airblade/paper_trail#api-summary)

> It caused a really unexpected bug on our end, where we had a flag called "live" on our model

I'm sorry to hear that. Naming is hard, you are the first person to inquire about this particular method but many of the method names have been updated in the past due to complaints such as this. I don't think it's that common of a name since it hasn't seemed to cause name conflicts prior, but we could consider prepending `paper_trail` for every method name, although that also seems like overkill.  I suppose `live_version?` would be appropriate, we will consider renaming it for version 5.

**Comment by blakewest** [comment]
Thanks for the reply. Yeah I see that it's clearly documented. Just one of those things you don't really think about as a collision. I agree prepending `paper_trail` to everything is a bit long. Perhaps prepending `pt` could be a usable namespace?

Thanks for adding it to the V5 roadmap.

**Comment by jaredbeck** [comment]
There are other potential name conflicts, too. If I'm counting correctly, installing the `paper_trail` gem adds 36 instance methods and 10 class methods to all of your active record models.  Of those 46, 13 have a prefix, either "pt_" or "paper_trail_". I don't know what the best way to deal with this is.  Ideally, we'd add far fewer methods to people's models. If we're only adding a few methods to models, then I wouldn't mind prefixing all of them.

**Comment by jaredbeck** [comment]
> If I'm counting correctly, installing the paper_trail gem adds 36 instance methods and 10 class methods to all of your active record models.

I have an idea that could reduce this number from 46 to perhaps 2 or 3, and might not be all that complicated: https://github.com/airblade/paper_trail/pull/719

**Comment by jaredbeck** [comment]
Closed by https://github.com/airblade/paper_trail/pull/719, which is expected to be released as 5.2.0. This means that methods like `.live?` will be deprecated in 5.2 (in favor of `.paper_trail.live?` and they will probably be removed in 6.0.0.
