### ISSUE TITLE
rake aborted! ActiveRecord::StatementInvalid: Mysql2::Error: Table 'my_database_development.version_associations' doesn't exist:

### ISSUE THREAD

**Issue by andreydeineko** [airblade/paper_trail#707]
I have encountered the problem with papertrail gem. Ruby 2.3.0, rails 4.2.5, papertrail 4.0.2. 

When running 
```ruby
cap staging db:pull
```
I get 
```ruby
rake aborted! 
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'my_database_development.version_associations' doesn't exist: SHOW FULL FIELDS FROM `version_associations`
```
What strange is that I do not have the table:
```ruby
PaperTrail::VersionAssociation.table_exists?
#=> false
```
```ruby
# Gemfile.lock
paper_trail (4.0.2)  # had the same issue with 4.0.0
```
Anything I can do here?

Thanks!

**Comment by jaredbeck** [comment]
Can you reproduce this issue in a brand new rails app without capistrano?

**Comment by piratebroadcast** [comment]
Im getting a similar error in rails admin in a fresh rails 4 app with a handful of models - When I hit the 
/admin path, it blows up because versions_associations does not exist. However, versions_acssociations is listed in the left sidebar and I have a feeling it shouldnt be. See screenshots: 

http://i.imgur.com/OaVFPJp.png

error: http://i.imgur.com/rUlrb3b.png

Full error when loading /admin:

ActiveRecord::StatementInvalid in RailsAdmin::MainController#dashboard
PG::UndefinedTable: ERROR: relation "version_associations" does not exist LINE 5: WHERE a.attrelid = '"version_associations"'::... ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"version_associations"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum

**Comment by hlascelles** [comment]
Seeing a similar error, Rails 3.2, paper_trail 4.0.2. Doing a full `db:create db:migrate` from scratch.

```
NoMethodError: undefined method `version' for ActiveModel:Module
config/application.rb:7:in `<top (required)>'
```

Downgrading to paper_trail 4.0.0 solves the issue.

**Comment by batter** [comment]
@hlascelles - the error you are seeing does not look like the same issue as the others in this thread.  Can you open a new issue for it and provide a full stack trace?

**Comment by hlascelles** [comment]
@batter I do apologise...two gems were moving back and forth with each test. The real problem lies in an unintentional upgrade of `validates_timeliness` as described here: https://github.com/adzap/validates_timeliness/issues/134

Cheers!

**Comment by daveh-me** [comment]
With an existing paper_trail and rails_admin install I ended up `rails g paper_trail:install --with-associations` and migrating to create the table to work around this.

Using rails 4.2.5.1
Using paper_trail 4.1.0
Using rails_admin 0.8.1

**Comment by jaredbeck** [comment]
> Can you reproduce this issue in a brand new rails app without capistrano?

Has anyone been able to reproduce this in a brand new rails app without capistrano, rails_admin, validates_timeliness, or any other third party? Per our [contributing guide][1], please use our bug report template, thanks.

[1]: https://github.com/airblade/paper_trail/blob/master/CONTRIBUTING.md

**Comment by andreydeineko** [comment]
@jaredbeck I unfortunately yet did not have a moment to create a brand new app. Truly to say, I even do not know how would I reproduce this error, since `paper_trail` works perfectly fine all the time except for the situation, when I try to download the production database

**Comment by andreydeineko** [comment]
@jaredbeck when I put `binding.pry` into my rake task and check for
```ruby
defined?(::Rails) && ActiveRecord::VERSION::STRING >= '3.2'
```

it returns `true`, but saying 

```ruby
require 'paper_trail/frameworks/rails'
```

returns `false` all the time and errors persists (obviously).

But 

```ruby
 require 'paper_trail/frameworks/active_record'
```

returns `true`..

**Comment by jaredbeck** [comment]
> `defined?(::Rails) && ActiveRecord::VERSION::STRING >= '3.2'` .. returns `true` ..

OK, that rules out my theory.

Do you have any idea of how I can reproduce this issue? I don't have any ideas how to troubleshoot it further without steps to reproduce.  Thanks.

**Comment by scanferla** [comment]
Same thing happening here, while trying to access `rails_admin`.
Brand new app, with only User model (with Devise).

@daveh-me solution has fixed the issue for me!

**Comment by JoeSouthan** [comment]
Had the same problem (except not using Rails admin), @daveh-me's solution worked a treat :tada:

Rails 4.2.5.1
paper_trail (4.1.0)

**Comment by jaredbeck** [comment]
>> Has anyone been able to reproduce this in a brand new rails app without capistrano, rails_admin, validates_timeliness, or any other third party? 2016-02-15
>
> Do you have any idea of how I can reproduce this issue? I don't have any ideas how to troubleshoot it further without steps to reproduce. Thanks. 2016-02-17

If no one can reproduce this issue in a brand new rails app without any third parties, then we can't troubleshoot it further, sorry. Thanks for reporting.

**Comment by NielsKSchjoedt** [comment]
+1 I seem the same issue!

**Comment by jaredbeck** [comment]
Hi Niels. Thanks for the feedback. Can you provide a sample app with this `reload!` issue? Thanks!
