### ISSUE TITLE
Paper Trail whodunnit model required

### ISSUE THREAD

**Issue by coorasse** [airblade/paper_trail#710]
If I don't specify

`config.audit_with :paper_trail, 'User', 'PaperTrail::Version'`

history is not shown.

But I have no User model. I have no way to tell rails_admin that I have no whodunnit model to track.

**Comment by jaredbeck** [comment]
Have you reported this to the rails_admin crew?

Per our [contributing guide][1] if you think you've found a bug in PT, please use our [bug report template][2].

[1]: https://github.com/airblade/paper_trail/blob/master/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
