### ISSUE TITLE
model.previous_version returns typecast error in Rails 4.2.4 #v4.1.0 

### ISSUE THREAD

**Issue by milankubin** [airblade/paper_trail#721]
````
[6] pry(main)> Lead.last.previous_version
  Lead Load (1.9ms)  SELECT  "leads".* FROM "leads"  ORDER BY "leads"."id" DESC LIMIT 1
  
  PaperTrail::Version Load (0.8ms)  
SELECT  "versions".* 
FROM "versions" 
WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2  
ORDER BY "versions"."created_at" DESC, "versions"."id" DESC 
LIMIT 1  [["item_id", 35675], ["item_type", "Lead"]]

  Lead Load (0.8ms)  
SELECT  "leads".* 
FROM "leads" 
WHERE "leads"."id" = $1 
LIMIT 1  [["id", 35675]]

NoMethodError: undefined method `to_i' for false:FalseClass
from /usr/local/rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/type/integer.rb:17:in `type_cast_from_database'
[7] pry(main)>

**Comment by jaredbeck** [comment]
Just at a first glance, I don't see anything wrong with your SQL. 

Please try to reproduce this using our [bug report template](https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb).

**Comment by jaredbeck** [comment]
If you're not able to reproduce this using our [bug report template](https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb), can you please provide a full stack trace (`Rails.backtrace_cleaner.remove_silencers!`) and the schema of the relevant table? Thanks.

**Comment by jaredbeck** [comment]
Closed due to lack of activity. Please provide the requested information and we'll be happy to reopen the issue.
