### ISSUE TITLE
update_columns with paper_trail triggers after_save callback

### ISSUE THREAD

**Issue by samstickland** [airblade/paper_trail#736]
Hi,

If I enable paper_trail on a model, then the update_columns method triggers the after_save callback - which shouldn't happen (and doesn't happen without paper_trail).

Is this a bug? This is with paper_trail 4.1.0

**Comment by batter** [comment]
According to [`ActiveRecord`'s documents, `update_columns` skips callbacks](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_columns), so this shouldn't happen. If anything this would be a bug on ActiveRecord's part, not PaperTrail's

**Comment by samstickland** [comment]
I was using update_columns deliberately to skip the callbacks, but once I
added has_paper_trail to the model update_columns started firing the
callbacks.

I'm wondering if something like this got implemented
https://github.com/airblade/paper_trail/issues/456 for storing a
paper_trail version when update_columns is used and as a side effect it's
started firing callbacks?

I'm found a workaround for now (using skip_callbacks rather than
update_columns), and tbh, I'm trying to move to a future without callbacks
(explicitly launching actions in a service object instead).

S

2016-03-15 19:32 GMT+00:00 Ben Atkins <notifications@github.com>:

**Comment by jaredbeck** [comment]
Ben is right, `update_columns` skips callbacks. If you cannot reproduce this issue with ActiveRecord only, *and* can reproduce this issue using our [bug report template][1] please let us know. Thanks!

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by samstickland** [comment]
But if doesn't skip callbacks if the model has paper trail enabled!

Without Papertrail: update_columns skips callbacks
With Papertail: update_columns *does not* skip callbacks


If I get time I'll try to reproduce a small project to illustrate the issue.

2016-03-23 16:05 GMT+00:00 Jared Beck <notifications@github.com>:

**Comment by jaredbeck** [comment]
> If I get time I'll try to reproduce a small project to illustrate the issue.

That'd be great, thanks! Please use our [bug report template][1].

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
