### ISSUE TITLE
reify fails for attachment delete

### ISSUE THREAD

**Issue by anklos** [airblade/paper_trail#743]
I have a bid class:

```ruby
class Bid < ActiveRecord::Base
has_paper_trail

mount_uploader :agreement, AttachmentUploader
end
```

Steps to cause reify fail:

1. create a bid without file.
2. upload an agreement file to `bid`.
3. delete the agreement file.

Now I have 3 versions in paper trail for this bid.

```
bid.versions[0].reify -> nil
bid.versions[1].reify -> bid object
bid.versions[2].reify -> crashes. Error is: ArgumentError: undefined class/module AttachmentUploader::Uploader2159215840
```

**Comment by jaredbeck** [comment]
Well, that's no good! Thanks for the issue report, Shane. Please write a script that reproduces the problem using our [bug report template][1].

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by anklos** [comment]
I cannot reproduce this in the script, all tests passed in the code below. I will report in a separate one if I find the cause. Thanks!

https://gist.github.com/anklos/3f30d8c075acba69011ef664da6f09f2

**Comment by jaredbeck** [comment]
Thanks for trying, Shane.
