### ISSUE TITLE
bundle exec rake is failing for the first time but able to pass when I run it for the second time

### ISSUE THREAD

**Issue by cui-liqiang** [airblade/paper_trail#746]
The problem happens for Ruby 2.1, 2.3 on my local machine.

Reproduce steps:
1. export BUNDLE_GEMFILE=$PWD/gemfiles/ar5.gemfile
2. export DB=sqlite
3. bundle install
4. bundle exec rake

I got the following error for the first time. But the error disappears for the second time.

Error: test: a has_one association where the association is created between model versions and then the associated is updated between model versions when reified should see the associated as it was at the time. (AssociationsTest): ActiveRecord::ConfigurationError: Association named 'version_associations' was not found on PaperTrail::Version; perhaps you misspelled it?
activerecord (3.2.22.2) lib/active_record/associations/join_dependency.rb:112:in `build'
activerecord (3.2.22.2) lib/active_record/associations/join_dependency.rb:123:in`block in build'

Any clues?

**Comment by jaredbeck** [comment]
This is a known issue. Ben and I have just been living with it. Since it only happens once per contributor, it has been a low priority, but we'd still love to fix it.

**Comment by jaredbeck** [comment]
I'm removing the "Bug" label because this is not a bug in the library, just in tooling we volunteers use.

**Comment by jaredbeck** [comment]
I don't think this is an issue anymore, now that we've dropped support for rails 3 (PT 6.0.0, [#898][1]).

[1]: https://github.com/airblade/paper_trail/pull/898
