### ISSUE TITLE
Versions table required

### ISSUE THREAD

**Issue by Nakort** [airblade/paper_trail#751]
Hey guys,
Due to certain restrictions we decided to inherit from the PaperTrail::Version class and to store the versions in a different table, however, the gem is expecting the versions table to exist even if nothing is stored there.

I had to create an empty versions table to move forward.

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  ruby "2.2.1"
  source "https://rubygems.org"
  gem "activerecord", "4.2.0"
  gem "minitest", "5.8.3"
  gem "paper_trail", "4.0.0", require: false
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end
  create_table :user_versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.integer :transaction_id
    t.datetime :created_at
  end
end

# We must wait to require `paper_trail.rb` until after the
# `version_associations` table exists or else PT won't track associations.
require "paper_trail"

class UserVersion < PaperTrail::Version
	self.table_name = "user_versions"
end

class User < ActiveRecord::Base
	has_paper_trail class_name: 'UserVersion'
end

class BugTest < ActiveSupport::TestCase
  def test_1
    assert_difference(-> { UserVersion.count }, +1) {
      User.create(first_name: "Jane")
    }
  end
end
```

**Comment by jaredbeck** [comment]
Hi Nakort, thanks for the issue report, and thanks for using our bug report template!

[Per the documentation][1], 

> If you only use custom version classes and don't have a `versions` table, you
> must let ActiveRecord know that the `PaperTrail::Version` class is an
> `abstract_class`.
>
> ```ruby
> # app/models/paper_trail/version.rb
> module PaperTrail
>   class Version < ActiveRecord::Base
>     include PaperTrail::VersionConcern
>     self.abstract_class = true
>   end
> end
> ```

If you have any thoughts on how to make this more obvious in the documentation, please submit a PR.

Happy (paper) trails!

[1]: https://github.com/airblade/paper_trail/#custom-version-classes
