### ISSUE TITLE
Unexpected behavior when overriding `versions` method

### ISSUE THREAD

**Issue by devonestes** [airblade/paper_trail#788]
This isn't a bug, per se, but it's very confusing behavior that we noticed. We were able to fix it, but it might be something that is worth addressing, so I wanted to bring it up.

We are dealing with migrating some code over in a legacy codebase, and we wanted to introduce a module namespace for a given model that we were versioning with PaperTrail. This means we had records in our `versions` table that looked like this:

```ruby
{
  item_id: 1,
  item_type: "Thing",
  event: create,
  object: #...omitted
}

{
  item_id: 1,
  item_type: "ModuleName::Thing",
  event: update,
  object: #...omitted
}
```

Since both records were referring to essentially the same object, we wanted to override the `versions` method to return both of those records, so we did this:

```ruby
def versions
  types = ['Thing', 'ModuleName::Thing']
  @versions ||= Version.where(item_id: id, item_type: types)
end
```

This change broke how versions were created, though. We were seeing records created with the following item types:

```ruby
{
  item_id: 1,
  item_type: "[\"Thing\", \"ModuleName::Thing\"]"
  object: #...omitted,
  event: update
}
```

We ended up solving our problem by changing the `versions` configuration option for the given model, but this was very unexpected behavior that might be avoided by a different implementation for how versions are created.

**Comment by jaredbeck** [comment]
> .. we wanted to override the versions method ..

Overriding the `versions` method is not supported. 

`versions` is an AR association created with `has_many`. Overriding it is likely to have unexpected side-effects.

> We ended up solving our problem by changing the versions configuration option ..

The `:versions` option allows you to change the name of the `has_many` association. I think this helped you because you were no longer overriding an AR association method.

> .. a different implementation for how versions are created.

`Version` records are created using the standard AR method `create!`. There's no magic, it's just a normal ActiveRecord association.

It's not clear to me what PaperTrail could do differently. Did you have any specific ideas? Or some improvement you'd like to make to the documentation?

**Comment by devonestes** [comment]
Well I can think of an implementation that would change this, but I'm not sure if it's something you'd want to do. I could imagine a versioned class with an API that looked something like this:

```ruby
class Thing < ActiveRecord::Base
  has_paper_trail

  def create_version(*args) #not sure that's what the method's called...
    base_versions.create!(*args)
  end

  def base_versions
    # current implementation of the `versions` method
  end

  alias_method :versions, :base_versions
end
```

And then the method that creates a new `Version` object would depend on the underlying `base_versions` method, which would allow the user to override the `versions` method if they wish. I'm not sure what side-effects this would have, but it's a (very rough) potential way to remove the coupling between retrieving versions and creating them.

However, I'm not sure this is the best way to go. It might be, but I'll leave that to you since I'm not intimately familiar with all the ins and outs of PaperTrail. If you think this isn't a good idea, then maybe some more explicit documentation could help so users know that overriding the `versions` method will have these side effects? We couldn't find anything in the docs or even on StackOverflow when we saw the bug we ran into, and we had to do a bit of source diving to find out why we were seeing this behavior. I'd be happy to write up something that made this more explicit in the docs and submit a PR if you like.

**Comment by jaredbeck** [comment]
Overriding the `versions` method is not supported, and I don't think we should encourage people to override AR associations. Instead of overriding the association, as in your example:

```
def versions
  types = ['Thing', 'ModuleName::Thing']
  @versions ||= Version.where(item_id: id, item_type: types)
end
```

.. I'd encourage you to give your custom query method a different name, like `all_the_thing_versions` :)

**Comment by jaredbeck** [comment]
Thanks for the suggestions. If you'd like to add some documentation clarifying how `versions` is just a normal AR association, I'd be happy to review a PR.
