### ISSUE TITLE
before_action vs before_filter

### ISSUE THREAD

**Issue by Celadon** [airblade/paper_trail#792]
Deep appreciation to volunteers who have made PaperTrail. Just updated gems for my Rails 4.2.6 app to PaperTrail V5. Received deprecation warning about setting "before_filter :set_paper_trail_whodunnit"

Is Rails the overwhelming market for PaperTrail? If so, my understanding is that in Rails 4, before_filter is deprecated to before_action. Blogs indicate upcoming Rails 5 may eliminate before_filter entirely.

Therefore, should PaperTrail deprecation warning and documentation use "before_action" rather than "before_filter"? I implemented "before_action :set_paper_trail_whodunnit" in my Rails 4.2.6 app. That eliminated the PaperTrail deprecation warning and all of my app tests pass.

Raymond

**Comment by jaredbeck** [comment]
Hi Raymond. We still support rails 3, so maybe that's why the deprecation warning tells you to use `before_filter`. I suspect very few people still use rails 3 though, so if you want to submit a PR that changes the warning, that would be fine.
