### ISSUE TITLE
Really weird behavior when using rails-observers? (Rails 5 beta 4)

### ISSUE THREAD

**Issue by cannikin** [airblade/paper_trail#795]
Sorry this isn't using the template! Let me know if this looks like a real thing and I'll add one.

I'm running Rails 5.0.0.beta4 with paper_trail (latest master) and the rails-observers gem (latest master).

```ruby
class User < ApplicationRecord
  has_one :profile
  # other relationships here...
  has_paper_trail
end

class Profile < ApplicationRecord
  belongs_to :user
  # other relationships here...
  has_paper_trail
end
```

I've got observers for both:

```ruby
class UserObserver < ActiveRecord::Observer
  def after_create(user)
    user.create_preferences! unless user.preferences
  end
end

class ProfileObserver < ActiveRecord::Observer
  def after_create(profile)
    profile.create_social_accounts! unless profile.social_accounts
  end
end
```

The problem occurs when I create a Profile (`Profile.create! :username => 'foobar'`):

    NoMethodError: undefined method `preferences' for #<PaperTrail::Version:0x007fb5b3a2cea0>

Preferences? That has nothing to do with Profile, just User...if I put a `binding.pry` into `UserObserver#after_create` right before the `user.create_preferences!` call, here's what it tells me that user is:

```ruby
#<PaperTrail::Version:0x007fb5b3a2cea0
 id: 107,
 item_type: "Profile",
 item_id: 40,
 event: "create",
 whodunnit: nil,
 object: nil,
 created_at: Fri, 06 May 2016 22:37:31 UTC +00:00,
 object_changes: "---\nid:\n- \n- 40\nusername:\n- \n- foobar\n">
```

Why is the User observer being invoked at all (profiles can be created without an attached user), and why are PaperTrail::Versions being passed to my model observers at all?

I've had both observers and PaperTrail on other apps and don't recall anything like this happening before...

**Comment by jaredbeck** [comment]
Hi Rob, thanks for the issue report. Can you reproduce this issue in a new rails app without the rails-observers gem?

**Comment by cannikin** [comment]
@jaredbeck Well, I only noticed the problem because it was invoking the Rails observer with the wrong object. If I don't have the observers then I wouldn't see any problem at all! :) Anything else I can do to help diagnose?

**Comment by jaredbeck** [comment]
Thanks Rob. I'll label this as a third-party issue. 

The `rails-observers` gem hasn't been updated since 2013, and does not support rails 5, for what that's worth.

Let me know if you can reproduce this issue using our [bug report template][1] and I'll help if I can.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by jaredbeck** [comment]
> Let me know if you can reproduce this issue using our [bug report template][1] and I'll help if I can.

To clarify, even if you can only reproduce this with `rails-observers`, I still want to help if I can.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by jaredbeck** [comment]
Hi Rob, have you been able to reproduce this using our bug report template? Do you want me to keep the issue open a little longer?

**Comment by cannikin** [comment]
@jaredbeck Sorry, I haven't had a chance...it the meantime I've just been using plain ol' lifecycle callbacks right in the models. I was hoping that side effect stuff could go into observers but it seems like there's just too many moving parts with all the Rails 5 changes...<sigh>

Maybe close for now and then when I have a chance I'll reopen with the bug template?
