### ISSUE TITLE
Bug with enum / enums

### ISSUE THREAD

**Issue by WaKeMaTTa** [airblade/paper_trail#798]
Hi,
I have a bug with `enums` and `paper_trail`. I will explain the bug with a dummy example.

```ruby
# We have this model `models/post.rb`
class Post < ActiveRecord::Base
  has_paper_trail
  enum kind: { document: 0, newspaper: 1 }
end
```

```ruby
# We create a post
@post = Post.create(title: "Hello world", kind: :document)

# We update the post for set the enum `kind` to `newspaper`
@post.update_attribute(kind: :newspaper)

# We print the versions we have (only for more informatión)
@post.versions
# return: 
[

    [0] <PaperTrail::Version:0x00558ca746a800> {
                    :id => 3,
             :item_type => "Post",
               :item_id => 916,
                 :event => "create",
             :whodunnit => "684",
                :object => "---\nid: 916\nuser_id: 739\ntitle: 'Hello world'\nkind: \n...",
            :created_at => Mon, 09 May 2016 16:15:55 UTC +00:00,
        :transaction_id => 3
    },
    [1] <PaperTrail::Version:0x00558ca746a6c0> {
                    :id => 4,
             :item_type => "Post",
               :item_id => 916,
                 :event => "update",
             :whodunnit => "684",
                :object => "---\nid: 916\nuser_id: 739\ntitle: 'Hello world'\nkind: \n...",
            :created_at => Mon, 09 May 2016 16:16:15 UTC +00:00,
        :transaction_id => 4
    }
]

# We check previous version
@old_version = @post.previous_version
# return:
<Post:0x00558ca743fad8> {
                    :id => 916,
               :user_id => 739
                 :title => 'Hello world',
                  :kind => nil, # this needs to be "newspaper"
            :created_at => Mon, 09 May 2016 16:15:55 UTC +00:00,
            :updated_at => Mon, 09 May 2016 16:16:05 UTC +00:00
}
```

**Some extra info**

- Ruby 2.2.5
- Rails 4.2.6
- PostgreSQL 9.5.2
- gem PaperTrail 5.0.1 with **Associations** (`--with-associations`)

**Comment by jaredbeck** [comment]
Hi Mohamed, Sounds like you're on the right track! Thanks for the issue report.

Can you convert what you've got into a script, using our [bug report template][1]? Thanks!

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by WaKeMaTTa** [comment]
Here it is [bug report enum](https://gist.github.com/WaKeMaTTa/1f960f58f3a001c9ae78bedf539d87cc#file-bug_report_enum_and_paper_trail-rb)

**Comment by jaredbeck** [comment]
Thanks Mohamed! I will mark this as a confirmed bug.

According to the changelog, enum support was added in PT 3.0.3 by https://github.com/airblade/paper_trail/pull/383. Also, your test passes in PT 4.1.0, so this appears to be a regression between 4.1.0 and 5.0.1.

**Comment by barnone27** [comment]
This still appears to be an issue even in 5.1.1. Both update and destroy *events* still store the enum columns in the *object* data as `nil`.

**Comment by jaredbeck** [comment]
> This still appears to be an issue even in 5.1.1.

That is correct. I played around with a fix in https://github.com/airblade/paper_trail/pull/805 but wasn't happy with my implementation. If you have any suggestions of how to fix it, I'd welcome them.

**Comment by jaredbeck** [comment]
Have either of you (Mohamed, barnone27) had any luck fixing this? I don't use enums, so this is a low priority for me, but if either of you can take the lead on this, I'd be happy to help.

**Comment by key88sf** [comment]
Enums are very common now - I would hope this becomes a higher priority bug to fix if possible.

**Comment by jaredbeck** [comment]
> I would hope this becomes a higher priority bug to fix if possible.

Contributions are welcome, thanks!

**Comment by jaredbeck** [comment]
It's worth pointing out that this is not an issue with rails 5, only with rails 4.2.

**Comment by jaredbeck** [comment]
@WaKeMaTTa and @key88sf please try master and confirm that it fixes the issue, thanks!

**Comment by jaredbeck** [comment]
Released in 5.2.1. Please test, thanks!

**Comment by WaKeMaTTa** [comment]
It works perfectly. Good job. :tada:

**Comment by jaredbeck** [comment]
> It works perfectly. Good job. 🎉 

Thanks. That code (`CastedAttributeSerializer`) is sooo hard to understand 😭 I wish I understood it better so I could improve it instead of just adding band-aids. But, at least we have a few more tests around enums now. ("few" being the key word)
