### ISSUE TITLE
Don't call current_user when paper_trail is not enabled for the controller

### ISSUE THREAD

**Issue by Draiken** [airblade/paper_trail#817]
Hi there!

I've been adding paper trail to an app, and got surprised that after adding papertrail, some tests started failing even after adding the rspec helper

Turns out I had some tests stubbing `current_user` and I was surprised to see paper trail was attempting to call it even when disabled, since the method can trigger queries and other things.

Looking at this https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/frameworks/rails/controller.rb#L94 it's pretty easy to see the cause. I'd be happy to provide a PR with a simple guard on the `enabled_for_controller` call, if you guys think it's something worth changing.

IMO paper trail before actions should be a complete no-op when disabled.

**Comment by jaredbeck** [comment]
>  I'd be happy to provide a PR with a simple guard  ..

Hi Luiz, a guard clause would be fine, thanks!

**Comment by jaredbeck** [comment]
Luiz, are you still working on this? Want me to keep it open?

**Comment by Draiken** [comment]
Sorry I had a busy couple of weeks... completely forgot about it.
I'll send a PR in a few
