### ISSUE TITLE
Document use of integer type for whodunnit column

### ISSUE THREAD

**Issue by senotrusov** [airblade/paper_trail#822]
I want to propose to document the case with integer whodunnit column.

I looked through paper_trail code and I saw no barriers to just change the column. I found one of the closed issues here with someone describing the same approach.

I just want to have that case documented to be sure that such feature will still be supported in future releases.

Having integer user id, there are benefits of using integer type for whodunnit column, one of them is to be able to quickly join columns without type conversion.

Database-level foreign key constraints is also possible, although it might be the case only if one have a soft delete mechanism for records (e.g. boolean column to mark deleted records).

More important it's just a matter of unified and consistent approach to storing your data.

If authors paper_trail will agree on that feature I will gladly prepare changes is documentation and will send a pull request.

Thank you!

**Comment by jaredbeck** [comment]
Hi Stanislav, thanks for the suggestion. The decision to use `varchar` was made before my time but there are two reasons I can think of.

1. Some apps allow user records to be deleted, in which case the numeric id would become useless, so they prefer to save the user's name, email, or other identifier.
2. There are a few apps out there that use UUIDs to identify users.

**Comment by senotrusov** [comment]
Sure, those reasons are valid. That I propose is to make integer column optional and be sure to support that in the future.

Another option is to make two columns: one to store UUID or integer user id, and the second with the JSON collection of user attributes, such as email and first/last name. In that case all data will be more structured, in my opinion.

**Comment by jaredbeck** [comment]
You can already have an integer user id, or a collection of user attributes, or anything you want in the versions table. We call it [storing metadata][1].

[1]: https://github.com/airblade/paper_trail/#4c-storing-metadata

**Comment by senotrusov** [comment]
Thank you and sorry for disturbing.

**Comment by jaredbeck** [comment]
Thanks for the suggestions, Stanislav!
