### ISSUE TITLE
Rspec + reify(has_many: true)

### ISSUE THREAD

**Issue by lakesare** [airblade/paper_trail#823]
(PaperTrail 5.1.1)
I'm having troubles with 

      it '', versioning: true do
        guide.update!({ title: '1', steps_attributes: [ { description: 'a' }  ] })
        p guide.versions[2].reify(has_many: true).steps.map(&:description)
      end

In console same code predictably prints `['a']`, in rspec `[]`.
Same happens with:
- `require 'paper_trail/frameworks/rspec'` not used
- running it with `spring rspec`
- disabling DatabaseCleaner

It does work outside the `it` block in test environment.

**Comment by jaredbeck** [comment]
Hi Hel. Thanks for testing this experimental feature (associations). It might be this known issue: [Reification of associations is not compatible with transactional tests][1]

[1]: https://github.com/airblade/paper_trail/issues/542

**Comment by jaredbeck** [comment]
Based on your +1 I'll assume this issue is a duplicate and close it. Thanks for the feedbcak.
