### ISSUE TITLE
Show file in which the 'missing set_paper_trail_whodunnit' warning messages is shown

### ISSUE THREAD

**Issue by aried3r** [airblade/paper_trail#825]
I'm in the process of migrating paper_trail 4 to 5. I ran my specs and got two warnings:
>user_for_paper_trail is present, but whodunnit has not been set.
PaperTrail no longer adds the set_paper_trail_whodunnit callback for
you. To continue recording whodunnit, please add this before_action
callback to your ApplicationController . For more information,
please see https://git.io/vrTsk

However, since I have quite a few controllers and a couple hundred specs covering them, it was kind of tedious finding which controller caused this warnings. Is there a way to show the file which caused the warning? That would have been very helpful. :)

**Comment by aried3r** [comment]
PS: Is there a way for paper_trail to check if I set this `before_action`? Because I did (after finding the controllers) and noticed that they already call `set_paper_trail_whodunnit`.

**Comment by jaredbeck** [comment]
> However, since I have quite a few controllers and a couple hundred specs covering them, it was kind of tedious finding which controller caused this warnings. Is there a way to show the file which caused the warning?

No, but you're not the first person with this idea. Back in December, @stereobooster suggested the same thing in https://github.com/airblade/paper_trail/issues/645. I would welcome a PR that adds this feature, thanks!
