### ISSUE TITLE
Table `version_associations` not found.

### ISSUE THREAD

**Issue by craig-day** [airblade/paper_trail#828]
I've seen the issue a number of times and tried the various solutions. I still get the table doesn't exist error.

```
Mysql2::Error: Table 'my_db.version_associations' doesn't exist: SHOW FULL FIELDS FROM `version_associations` (ActiveRecord::StatementInvalid)
```

This is my initializer

```ruby
require "paper_trail"

PaperTrail.config.version_limit = nil
PaperTrail.config.track_associations = false

PaperTrail::Version.class_eval do
  self.table_name = 'MY_TABLE'
end
```

I was able to get around the issue by adding the following

```ruby
PaperTrail::VersionAssociation.class_eval do
  self.abstract_class = true
end
```

but I feel like setting `config.track_associations = false` should mean the table isn't required.  

I'm not able to reproduce this on my personal laptop, but when the app gets deployed it always fails without the abstract class.  Not sure what other details would be helpful, and I didn't use the report template because I can't reproduce this locally.  Any advice is much appreciated.

**Comment by jaredbeck** [comment]
Hi Craig, thanks for the bug report.

> .. I can't reproduce this locally.

That's going to make it tricky to help, but let's see ..

I'm guessing the query `SHOW FULL FIELDS FROM 'version_associations'` is the sort of thing AR does when it's starting up, trying to figure out the attributes of the `VersionAssociation` model. Setting `abstract_class = true` is like telling AR, "hey, this model has no attributes", so maybe that's why it helped you.

> .. I feel like setting config.track_associations = false should mean the table isn't required. 

Yes. 100%. That's how we want it to work.

So, what information do we need to reproduce this?

- What version are you using? PT, rails, ruby, mysql, etc..
- What is the application doing when the error occurs? Starting up? Running a rake task?

**Comment by craig-day** [comment]
Hi @jaredbeck thanks for the help. 

- Ruby: 2.3.0
- Rails: 4.2.5
- PaperTrail: 5.0.1
- mysql2: 0.3.21
- MySQL: Ver 14.14 Distrib 5.5.32, for Linux (x86_64) using readline 5.1
- Unicorn: 4.9.0

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.4 LTS
Release:	12.04
Codename:	precise
```

The application is trying to boot, specifically with unicorn and this is the (redacted) stack trace

```
unicorn.log-20160617.gz:I, [2016-06-16T19:10:03.335162 #15784]  INFO -- : executing ["/path/to/my/app/unicorn/helper.sh", "-c", "/path/to/my/app/config/unicorn.rb", "-E", "master", "-D", {17=>#<Kgio::TCPServer:fd 17>}] (in /path/to/my/app/releases/alpha)
unicorn.log-20160617.gz:I, [2016-06-16T19:10:04.066065 #15784]  INFO -- : inherited addr=0.0.0.0:4081 fd=17
unicorn.log-20160617.gz:I, [2016-06-16T19:10:04.066329 #15784]  INFO -- : Refreshing Gem list
unicorn.log-20160617.gz:E, [2016-06-16T19:10:09.237717 #15784] ERROR -- : Mysql2::Error: Table 'my_db.version_associations' doesn't exist: SHOW FULL FIELDS FROM `version_associations` (ActiveRecord::StatementInvalid)
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/active_record_host_pool-0.9.3/lib/active_record_host_pool/connection_adapter_mixin.rb:33:in `execute_with_switching'
... some private gems
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:312:in `execute_and_free'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:457:in `columns'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.1/lib/active_record/attributes.rb:93:in `columns'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/active_record_shards-3.6.4/lib/active_record_shards/connection_switcher.rb:226:in `columns_with_default_shard'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/active_record_shards-3.6.4/lib/active_record_shards/default_slave_patches.rb:52:in `block in columns_with_default_slave'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/active_record_shards-3.6.4/lib/active_record_shards/connection_switcher.rb:108:in `on_cx_switch_block'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/active_record_shards-3.6.4/lib/active_record_shards/default_slave_patches.rb:52:in `columns_with_default_slave'
... some private gems
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:523:in `spawn_missing_workers'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
unicorn.log-20160617.gz:/path/to/my/app/vendor/bundle/ruby/2.3.0/gems/unicorn-4.9.0/bin/unicorn_rails:209:in `<top (required)>'
unicorn.log-20160617.gz:/path/to/my/app/bin/unicorn_rails:16:in `load'
unicorn.log-20160617.gz:/path/to/my/app/bin/unicorn_rails:16:in `<main>'
unicorn.log-20160617.gz:E, [2016-06-16T19:10:09.251771 #29413] ERROR -- : reaped #<Process::Status: pid 15784 exit 1> exec()-ed
```

I've played around with some of the common rails config settings that seem to commonly impact boot things, but that didn't change anything.

```
config.cache_classes
config.eager_load
config.consider_all_requests_local
```

Locally it boots up using `thin` and not `unicorn` so maybe something going on there. My guess is something in the way that [unicorn preloads the app](https://devcenter.heroku.com/articles/rails-unicorn#preload-app).

Any help is greatly appreciated.

**Comment by craig-day** [comment]
I should clarify, I'm not using heroku or their config, but it seems that a similar configuration might be an issue.

**Comment by jaredbeck** [comment]
It looks like `active_record_shards` is looping over all models and calling `columns` on them. Is there any way for you to try removing `active_record_shards`, just for testing purposes? Or, can you turn on sharding locally?

**Comment by jaredbeck** [comment]
> It looks like active_record_shards is looping over all models and calling columns on them. Is there any way for you to try removing active_record_shards, just for testing purposes? Or, can you turn on sharding locally?

What news, Craig? Have you been able to reproduce this?

**Comment by craig-day** [comment]
@jaredbeck I'm working on reproducing it with a base rails app (seen [here](https://github.com/craig-day/funky_shards)), but haven't gotten very far yet.  I will be traveling the next few days so I won't get to work on it much.  Feel free to close this issue and I will reopen it if or when I can replicate it.

**Comment by jaredbeck** [comment]
OK. Like I said, I'm guessing if you turn on sharding locally, you'll be able to reproduce it.

**Comment by jakesorce** [comment]
I getting this issue as well.
