### ISSUE TITLE
Generate an initializer with track_associations=false

### ISSUE THREAD

**Issue by md5** [airblade/paper_trail#830]
As discussed in #567, the `paper_trail:install` generator should generate an initializer with `::PaperTrail.config.track_associations = false`, given the deprecation warning that was added in https://github.com/airblade/paper_trail/pull/785

**Comment by wiiiim** [comment]
Also, can this track_associations config option please be added to the documentation in the associations section?
I had to search quite a bit before I figured why it wasn't doing anything, after running the extra migrations.

**Comment by jaredbeck** [comment]
> .. the paper_trail:install generator should generate an initializer ...

Any progress on this, Mike? Have you figured out how to generate an initializer? Thanks!

> Also, can this track_associations config option please be added to the documentation in the associations section?

Great idea, Wim. Please submit a PR, thanks.

**Comment by md5** [comment]
@jaredbeck I know how to generate an initializer, I just haven't had time to look at this since it's not an itch I've had to scratch since we last discussed it.
