### ISSUE TITLE
Deprecation Warning self-generated?

### ISSUE THREAD

**Issue by jdashton** [airblade/paper_trail#836]
I'm getting a deprecation warning for `paper_trail_version_class`. This is with version 5.2.0 running on Ruby 2.3.1 and Rails 3.2.22.2. The string being flagged appears no where in my code. The error message points to my line that says simply
`has_paper_trail`

Here's the message:
`DEPRECATION WARNING: Use paper_trail.version_class instead of paper_trail_version_class. (called from <class:PayrollFile> at /Users/danielashton/proj/ai1/app/models/payroll_file.rb:47)`

When I search my libraries, the only occurrence of `paper_trail_version_class` is in the gem itself, in `model_config.rb` line 125. I wonder if this is causing the deprecation warning.

**Comment by jaredbeck** [comment]
Thanks Daniel!
