### ISSUE TITLE
Support for storing only incremental changes for json/jsonb columns

### ISSUE THREAD

**Issue by alisaifee** [airblade/paper_trail#837]
When I enable `paper_trail` on a model that has a `jsonb` column - making updates to that column results in the entire object being stored under `object_changes`. For example with a model called `Document` that only has one `jsonb` column `data`:

``` ruby
d = Document.new
d.data = {a: {b: 1}}
d.save!
d.data["a"]["b"] = 2
d.save!
d.data["a"]["c"] = 1
d.save!
d.versions.last[:object_changes]["data"]
[
    [0] {
        "a" => {
            "b" => 2
        }
    },
    [1] {
        "a" => {
            "b" => 2,
            "c" => 1
        }
    }
]
```

I'm curious if its possible (if desirable) to only store the deltas - as with very large json/jsonb blobs the storage can become very expensive and also the `object_changes` don't result in easy to identify **changes**

**Comment by jaredbeck** [comment]
> I'm curious if its possible (if desirable) to only store the deltas - as with very large json/jsonb blobs the storage can become very expensive and also the object_changes don't result in easy to identify changes

Great question, Ali.  It is not currently possible. The `object_changes` column is populated directly from `ActiveModel::Dirty#changes`, which we have no control over. Does `ActiveModel::Dirty` provide a way to get the deltas for a jsonb attribute?

**Comment by seanlinsley** [comment]
It would be good to have a Ruby method to diff the objects, but I don't think it makes sense to only store the diff in the database, as it would make restoring from the data more difficult, as well as querying it (in the case of JSONB).

**Comment by alisaifee** [comment]
The closest diffing implementation I've seen that suits the requirement is [hashdiff](https://github.com/liufengyun/hashdiff). Restoring the data would still be done by the `object` value but the deltas can still be stored in `object_changes` in the same way as attribute changes are stored.

**Comment by daniely** [comment]
I agree with @alisaifee, full data in `object` while deltas are in `object_changes`.

**Comment by jaredbeck** [comment]
Sean makes a good point about the difficulty of restoring from deltas. We'd have to get the entire history of that attribute and "replay" it in ruby, which would make reification expensive and complicated.  And what's the benefit? We save some disk space? Disk space is cheap :)

**Comment by daniely** [comment]
@jaredbeck I guess I wrongly assumed that you could reify based on the `object` and applying just the `object_changes`. But if I'm wrong about that I agree with all your points.

**Comment by alisaifee** [comment]
@jaredbeck yes, one of the benefits is indeed saving disk space (though you're right, it is cheap :P). Another benefit is to make displaying the actual changes easier (for instance if you are displaying the paper trail in a form or something.

**Comment by jaredbeck** [comment]
> one of the benefits is indeed saving disk space (though you're right, it is cheap :P). 

Yeah, I'm not really concerned about disk space, either. Or rather, it is not a pain point that I've felt. There are other ways to save space, like limiting how many versions you keep.

> Another benefit is to make displaying the actual changes easier (for instance if you are displaying the paper trail in a form or something.

That sounds worthwhile, though I'd rather improve the convenience methods that *read* these data, like `VersionConcern#changeset` rather than changing the way we `write` them.

**Comment by alisaifee** [comment]
You are right, I think the most important aspect is to be able to clearly communicate the actual changes. Would you be interested in a pull request / collaborating on modifying the convenience method?

**Comment by jaredbeck** [comment]
> Would you be interested in a pull request / collaborating on modifying the convenience method?

Yes, thank you. 

Can you help me review the test coverage first? Ideally, the tests should cover all of the major data types, including timestamps with and without zone, and enums. We've had some bugs lately with enums specifically, and we could probably use more test coverage. 

Then, I'd like to review the design, or at least how things are named. For example, there are two different processes that are both referred to as serialization. 

Sound like a good plan?

**Comment by dmitry** [comment]
FYI https://github.com/palkan/logidze stores only changes.

**Comment by jaredbeck** [comment]
Thanks for the feedback everyone. I'm going to close this. For the reasons given above, we will not be changing how we store data. 

> I'd rather improve the convenience methods that read these data (like VersionConcern#changeset) rather than changing the way we write them.

I'm still open to suggestions regarding methods like `changeset`. Please open new issues with concrete suggestions.

> FYI https://github.com/palkan/logidze stores only changes.

logidze sounds really cool, especially using triggers to write to the log. I wish I used postgres at work :(
