### ISSUE TITLE
Association named 'version_associations' was not found on PaperTrail::Version; perhaps you misspelled it?

### ISSUE THREAD

**Issue by jakesorce** [airblade/paper_trail#840]
@version = @company.versions.find(version)
@company = @version.reify(dup: true, has_one: true)

<img width="1440" alt="screen shot 2016-07-28 at 4 57 59 pm" src="https://cloud.githubusercontent.com/assets/801470/17232394/ffb115ea-54e4-11e6-9f6f-9d9863cbe7de.png">

**Comment by selvachezhian** [comment]
@jakesorce I too facing similar kind of issue, can you please help me how did you resolve this?

`ActiveRecord::ConfigurationError: Can't join 'PaperTrail::Version' to association named 'version_associations'; perhaps you misspelled it?`
