### ISSUE TITLE
Long running processes appear in logs due to paper_trail

### ISSUE THREAD

**Issue by waiting-for-dev** [airblade/paper_trail#842]
Hi,

we are using `paper_trail` in one of ours apps hosted in heroku. Inspecting logs, we see that from time to time `paper_trail` does some long running process which can last up to 12 seconds.

    duration: 11260.616 ms statement: COPY "public"."versions" ("id", "item_type", "item_id", "event", "whodunnit", "object", "created_at", "company_id") TO stdout; Context

Why is this process running? If the gem requires such long processes, maybe some kind of integration with background job libraries should be implemented.

Thanks

**Comment by jaredbeck** [comment]
PT does not have an export feature, AFAIK. This `COPY` query is almost certainly coming from your app, not from PT.

If you can reproduce this `COPY` query using our [bug report template][1], please let us know and we'll be happy to reopen this issue.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by waiting-for-dev** [comment]
Sorry, you are right. Those logs were created by heroku daily scheduled backup. I was confused because at first I assumed that backup logs would appear with `heroku` as source instead of `app`, as it is the case.

Sorry for the noise.

**Comment by jaredbeck** [comment]
No worries. Thanks for sharing what you found, it might help someone else.
