### ISSUE TITLE
Unitialized Constant Version for 3.0.6 in RSpec test

### ISSUE THREAD

**Issue by nartz** [airblade/paper_trail#845]
Papertrail: 3.0.6
Rails: 4.2
Rspec: rspec (3.3.0), rspec-core (3.3.2)

In the test environment in the context of an rspec describe block, I am trying to save a model "Post" that uses has_paper_trail :class_name => 'EntityVersion', I am getting `Uninitialized Constant: 'EntityVersion'` - i am assuming this is because i am not eager loading models in the test environment, and also that a 'Papertrail' model sublcasses Papertrail::Version:

```
class EntityVersion < PaperTrail::Version
  self.table_name = :entity_versions
end

```
 What is the right way to deal with this though without having to set eager_load = true for my test environment?

entity_version.rb is in `app/models/papertrail_versions/entity_version.rb`

and in application.rb i have added:
`config.autoload_paths += %W(#{Rails.root}/models/papertrail_versions)`

Thanks!

**Comment by jaredbeck** [comment]
PT 3.0.6 is almost two years old. Do you have this issue with the latest release? (currenly 5.2.0)

As a last resort, you could always use an explicit `require` or `require_dependency` in your `Post` model.

**Comment by nartz** [comment]
I think it was being autoloaded incorrectly (path was wrong) - thanks for your help.
