### ISSUE TITLE
Transaction ID not unique overall across models

### ISSUE THREAD

**Issue by bjm88** [airblade/paper_trail#865]
We love Papertrail, its been a great auditing library for us.  That being said, one painful issue has been transaction id seems to not be unique across different models. So if we know to know same transaction for creating a user and their address, if I join in DB by transaction id I get hits but the actual user_versions and address_version records are not right and not created on same day......

Is this expected?

**Comment by jaredbeck** [comment]
> We love Papertrail, its been a great auditing library for us. 

Awesome! Thanks Benjamin :heart:

> .. if I join in DB by transaction id I get hits but the actual user_versions and address_version records are not right and not created on same day ..

I don't understand, sorry. Please use our [bug report template][1].

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by jaredbeck** [comment]
Sorry, I'm not sure what your asking, so I'm going to close this. If this is a bug report, please use our [bug report template][1] and I'll be happy to reopen the issue, thanks!

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
