### ISSUE TITLE
Version is not created of new record of joined tables of has_and_belongs_to_many association

### ISSUE THREAD

**Issue by PirunSeng** [airblade/paper_trail#873]
Hi There,

Thanks for a powerful data auditing gem.
Currently, I'm getting a problem with the `has_and_belongs_to_many` association in which I expect a version to be created when a new record of the joined table is created, but it is not.
As I discover the issues, I found out that the HABTM is implemented and merged already, but they all mentioned about reification only. What I really want is a version to be created in which I can track the changeset.

I have the association as below:
```
Client has and belongs to many agencies.
Agency has and belongs to many clients.
```

When creating a new client in which I select a few agencies, I would expect to see a version which has info about the client with agencies selected. Unfortunately, there is no any info about the agencies, but the client.

I'm using the latest version of paper trail:
```
gem 'paper_trail',            '~> 5.2', '>= 5.2.2'
gem 'rails',                  '4.2.2'
```

Anything misunderstand with my description, please kindly ask for clarification.

Thanks,
Pirun

**Comment by jaredbeck** [comment]
Thanks for testing the experimental associations feature.

Per our [contributing guide][1] please use our [bug report template][2].

[1]: https://github.com/binarylogic/authlogic/blob/master/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by PirunSeng** [comment]
I'm not really sure whether it is a bug or non-existing feature, sorry.
However, I think it is most likely a bug since I found out that the implementation of reification of HABTM exists, yet I haven't tried with the reification.

Please find my bug report template below:

```
Gemfile:
source 'https://rubygems.org'
ruby '2.3.1'
gem 'rails', '4.2.2'
gem 'pg'
gem 'paper_trail',  '~> 5.2', '>= 5.2.2'
gem 'rspec-rails', '~> 3.4'
```
```
Tables:
create_table :clients do |t|
      t.string :first_name, default: ''
      t.string :last_name, default: ''
      t.string :gender, default: 'Male'
end
create_table :versions, versions_table_options do |t|
      t.string   :item_type, item_type_options
      t.integer  :item_id,   null: false
      t.string   :event,     null: false
      t.string   :whodunnit
      t.text     :object, limit: TEXT_BYTES
      t.datetime :created_at
end
add_index :versions, [:item_type, :item_id]
add_column :versions, :object_changes, :text, limit: TEXT_BYTES
add_column :versions, :transaction_id, :integer
add_index :versions, [:transaction_id]
    
create_table :version_associations do |t|
      t.integer  :version_id
      t.string   :foreign_key_name, null: false
      t.integer  :foreign_key_id
end
add_index :version_associations, [:version_id]
add_index :version_associations,
      [:foreign_key_name, :foreign_key_id],
      name: "index_version_associations_on_foreign_key"
```
```
PaperTrail initializer:
PaperTrail.config.track_associations = true
```
```
Models
class Client < ActiveRecord::Base
  has_and_belongs_to_many :agencies
  has_paper_trail
end

class Agency < ActiveRecord::Base
  has_and_belongs_to_many :clients
  has_paper_trail
end
```
```
Model Spec:
describe Client, 'paper trail' do
  let!(:agency){ create(:agency) }
  let!(:client){ create(:client, agency_ids: agency.id) }
  context 'create a version of joined table of habtm association' do
    it { expect{PaperTrail::Version.count}.to change{PaperTrail::Version.count}.from(1).to(2) }
  end
end
```

**Comment by jaredbeck** [comment]
Thanks for the additional information, Pirun.

Please use our [bug report template][1]. The whole bug report should be contained in a single file.

Also, I do not understand the assertion in your test.

```
expect{ PaperTrail::Version.count }.to( 
  change{ PaperTrail::Version.count }.from(1).to(2)
)
```

Why do you expect *counting* to change the count?

Thanks.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by PirunSeng** [comment]
Heh @jaredbeck,

I feel like we misunderstand each other. I don't know why my previous comment does not apply to the bug report template.

> The whole bug report should be contained in a single file.

Honestly, I do not understand this point.

On the other hand, my assertion is to expect the amount of version records to be increased by one. This means that when I create a new client record that has one agency, two versions should be created. One records info of new client record, and other one records info of new joined table record, in my case, client_id and agency_id.

**Comment by jaredbeck** [comment]
>> The whole bug report should be contained in a single file.

> Honestly, I do not understand this point.

Please submit a single file which contains the entire bug report. The goal is a self-contained script that I can run which demonstrates the bug. Start with our template and modify it so that it demonstrates the bug. Thanks.

**Comment by fabricioblz** [comment]
Hi @PirunSeng !

I had the same doubt as you, and i found out something.

Actually papertrail will not track changes that was made in the association table.

That's because the join table is not a real active model object. And papertail need a real active model to work.

Use a real model and ```has_many :through associations.``` 
You will need to create a model that represents the association between Client e Agency, and track this model with ```has_paper_trail.```

If you remove some ```agencies``` from a certain ```client``` for example. You will be able to track what happened because papertrail will record the event that occurred in your ```agency_client``` new model

I hope that i understood and helped a little bit.

Here is a link of a similar doubt: https://groups.google.com/forum/#!topic/phillyrb/hWCE4glxThw

**Comment by PirunSeng** [comment]
Hi @fabricioblz !

Thanks for your explanation.
However, it would be good if anyone can implement this thing for HABTM association.
