### ISSUE TITLE
When a parent class `has_paper_trail` then changing child attributes with `accepts_nested_attributes_for`, the parent record is not touched

### ISSUE THREAD

**Issue by cannikin** [airblade/paper_trail#874]
I don't see how I can be the first person to notice this, but I think I found something bad. :( Bug template is here: https://gist.github.com/cannikin/1b951a6689d21cfe7c335e4d08adee8f (see comment starting on line 77 for how to make the tests pass).

This has nothing to do with actually creating versions, that all behaves as expected. The problem is that it seems to be breaking default Rails behavior RE: touching a parent when the child changes via nested attributes.

You have a parent and a child, and the child is set to touch the parent when it (the child) changes. The parent accepts nested attributes for the child:

```ruby
class User
  has_many :posts
  accepts_nested_attributes_for :posts
  has_paper_trail
end

class Post
  belongs_to :user, :touch => true
end
```

Editing a post touches the user record as expected:

```ruby
user = User.first
user.posts.first.update(:title => "New Post Title")
```
```bash
  User Load (0.3ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Post Load (0.3ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."user_id" = ? ORDER BY "posts"."id" ASC LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
   (0.0ms)  begin transaction
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  SQL (0.3ms)  UPDATE "posts" SET "title" = ?, "updated_at" = ? WHERE "posts"."id" = ?  [["title", "New Post Title"], ["updated_at", 2016-10-06 19:00:21 UTC], ["id", 1]]
  SQL (0.1ms)  UPDATE "users" SET "updated_at" = '2016-10-06 19:00:21.342059' WHERE "users"."id" = ?  [["id", 1]]
   (0.4ms)  commit transaction
=> true
```

But making that same change via nested attributes does NOT touch the user:

```ruby
user = User.first
user.update(:posts_attributes => { '0' => { :id => user.posts.first.id, :title => 'Another Title' } })
```
```bash
  User Load (0.1ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
   (0.0ms)  begin transaction
  Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."user_id" = ? AND "posts"."id" = 1  [["user_id", 1]]
  User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  SQL (0.3ms)  UPDATE "posts" SET "title" = ?, "updated_at" = ? WHERE "posts"."id" = ?  [["title", "Another Title"], ["updated_at", 2016-10-06 19:01:35 UTC], ["id", 1]]
   (1.2ms)  commit transaction
=> true
```

As you'll see in the bug file you need to completely remove/comment the `has_paper_trail` class method call in order to get the original default behavior (and the tests to pass).

Let me know if there's anything else I can do to help!

**Comment by cannikin** [comment]
Okay, did some further investigation...this might actually be a Rails issue.

I found that if I commented out the `after_commit` and `after_rollback` calls in PaperTrail::ModelConfig#setup_transaction_callbacks` (https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/model_config.rb#L191-L193) then the parent is touched again.

I set up another bug file but this time didn't include `has_paper_trail` at all and simply created an empty `after_commit {}` hook in the model and sure enough, the nested attributes change is broken.

I'm closing this one and adding an issue over at rails/rails!

**Comment by jaredbeck** [comment]
> I set up another bug file but this time didn't include has_paper_trail at all and simply created an empty after_commit {} hook in the model and sure enough, the nested attributes change is broken. I'm closing this one and adding an issue over at rails/rails!

Nice troubleshooting, Rob! You can probably adapt your PT bug report script directly to the ActiveRecord bug report script, because PT's is based on AR's :)

**Comment by cannikin** [comment]
Yep, just did! Sorry for the scare. :) https://github.com/rails/rails/issues/26726
