### ISSUE TITLE
ArgumentError: Before process_action callback :warn_about_not_setting_whodunnit has not been defined

### ISSUE THREAD

**Issue by easybills-admin** [airblade/paper_trail#876]
Hi there.

When I run `Rails.application.eager_load!` in a Rails 5 app with `paper_trail`, it returns the following error:

`ArgumentError: Before process_action callback :warn_about_not_setting_whodunnit has not been defined`

---

* Ruby `2.3.1`
* Rails `5.0.0.1`
* PaperTrail `5.2.2`

**Comment by easybills-admin** [comment]
Looks like `warn_about_not_setting_whodunnit` isn't being recognized.

In **Rails 5**, `ActiveSupport::Callbacks#skip_callback` raises an `ArgumentError` if an unrecognized callback is removed / not present (https://github.com/rails/rails/pull/19029/files).

**Comment by easybills-admin** [comment]
Also, `::PaperTrail.whodunnit` isn't behaving as expected:

```ruby
user_for_paper_trail
# ➙ "test"

::PaperTrail.whodunnit
# ➙ nil
```

**Comment by jaredbeck** [comment]
Thanks for the bug report. Per our [contributing guide][1] please use our [bug report template][2].

[1]: https://github.com/binarylogic/authlogic/blob/master/CONTRIBUTING.md
[2]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by easybills-admin** [comment]
Thanks @jaredbeck. I can't seem to reproduce it anymore :/
My guess it was something cached by Spring. I might be wrong though, so if it happens again, I'll let you know.

Cheers!

**Comment by jaredbeck** [comment]
The `:warn_about_not_setting_whodunnit` callback will probably be removed in the next major version of PT anyway.
