### ISSUE TITLE
Warnings everywhere

### ISSUE THREAD

**Issue by NielsKSchjoedt** [airblade/paper_trail#885]
After upgrading paper trail to 5.2 I get warnings like this in all my controllers: https://github.com/airblade/paper_trail/blob/c37e48973d8006edf635c72d5c742ce2d76c2f25/doc/warning_about_not_setting_whodunnit.md

Of cause I can add the line as suggested in the application controller, but since not all my controller inherit from application controller, I have to do it in a lot of places. This really seems like a lot of bloat to have. I only use PaperTrail on two of my models, and only in some controllers behind an admin - is this really intended behaviour?

**Comment by jaredbeck** [comment]
Hi Niels. 

I can't tell you which of the three solutions given in the documentation is best for you. It depends whether you want to continue tracking whodunnit. You should probably choose the solution that preserves the existing behavior of your application. I think https://github.com/airblade/paper_trail/blob/master/doc/warning_about_not_setting_whodunnit.md covers this topic pretty well.

The warning will go away in the next major version of PT, if that's any consolation.

PS: If you'll excuse me for whining a bit, it's a little frustrating that this warning has helped so many people by making them aware of a breaking change, but no one has ever thanked me for it. :( It would be less work on my part to not warn people. `</whining>`

Good luck with the rest of the upgrade. Hope it all goes smoothly!

**Comment by batter** [comment]
@NielsKSchjoedt - if it really bothers you that much you're welcome to fork a tagged version and [remove the code calling warn](https://github.com/airblade/paper_trail/blob/v5.2.2/lib/paper_trail/frameworks/rails/controller.rb#L13).

**Comment by NielsKSchjoedt** [comment]
Thanks for the help :-)
