### ISSUE TITLE
Allow block modification

### ISSUE THREAD

**Issue by frankywahl** [airblade/paper_trail#890]
This is a suggestion, but at times (for example, background jobs, etc), I find it useful to change the trace of a change. 

The API does work by changing `PaperTrail.whodunnit=(new_user)`, but this can then be lost in the stack calls, not put back, etc. 

I'd like to suggest something like

```ruby
PaperTrail.blaming(`new_user`) do 
    # Something that marks changes as the new user
end
```

This would ensure that outside the scope of the block, thins come back to how they use to be. 

This can of couse be done differently: 

```ruby
begin
  old_person = PaperTrail.whodunnit
  PaperTrail.whodunnit = 'new_user'
  # Something that marks changes as the new user
ensure  # don't forget this part.
  PaperTrail.whodunnit = old_person 
end
```

but it's more prone to errors of a person forgetting to set it back, or not ensuring, wrapping it in a `begin` block. 

I've given a try at it [here](https://github.com/airblade/paper_trail/compare/master...OpenSourceProjects:block_as_modification?expand=1). I know the tests are probably not where they should be, but they prove the concept. 

Thoughts?

**Comment by jaredbeck** [comment]
Thanks Franky, but we already have this feature. See the documentation, [section 4.a. Finding Out Who Was Responsible For A Change][1]. Look for where it says "It is possible to define the whodunnit value for an operation inside a block".

[1]: https://github.com/airblade/paper_trail#4a-finding-out-who-was-responsible-for-a-change

**Comment by frankywahl** [comment]
No problem. 

I had seen that, but had a slightly different use-case for it. The block described is on a per-model base. But sometimes, one may have a script, or some other object that does a whole lot of work. `ManyActionsObject.run` for instance. Now, to handle `PaperTrail` in such an object, we have to check in the implementation of the object and change each instance of AR records to the block syntax. I was proposing putting the whole method invocation inside the block syntax, and not care about implementation. `PaperTrail.blaming(...) { ManyActionsObject.run }`

Anyhow, I understand why we would not change it. But maybe my explanation shows a use case. 

Thanks for the quick response.

**Comment by jaredbeck** [comment]
> The block described is on a per-model base.

Actually, `RecordTrail#whodunnit` works for more than one model. It calls `PaperTrail.whodunnit=`.

```ruby
# lib/paper_trail/record_trail.rb
def whodunnit(value)
  raise ArgumentError, "expected to receive a block" unless block_given?
  current_whodunnit = PaperTrail.whodunnit
  PaperTrail.whodunnit = value
  yield @record
ensure
  PaperTrail.whodunnit = current_whodunnit
end
```
