### ISSUE TITLE
MyModel.paper_trail.disable should take a block

### ISSUE THREAD

**Issue by wconrad** [airblade/paper_trail#916]
Today I did this:

    MyModel.paper_trail.disable
    ...
    MyModel.paper_trail.enable

What I really wanted to do was this:

    MyModel.paper_trail.disable do
      ...
    end

Would you accept a PR to allow #disable to take a block, such that #enable would be called implicitly when the block ended?

-----

Note: This issue started a conversation about what the API should be.  [What I am now proposing][1] is a little different than what I proposed above.

[1]: https://github.com/airblade/paper_trail/issues/916#issuecomment-269977666

**Comment by batter** [comment]
This functionality already exists via the `without_versioning` method. [See the README for usage instructions and examples](https://github.com/airblade/paper_trail#per-method).

**Comment by wconrad** [comment]
I think that #without_versioning is a poor substitute for allowing #disable to take a block, because:

* #without_versioning is called on an instance, but it acts upon the model (based on your comment, and me reading the code).  That's surprising.
* #without_versioning requires me to create an instance even if I don't need one yet.

Would you accept a PR for a README change to make it clear what #without_versioning affects the entire model and not just that instance?

**Comment by batter** [comment]
Sure, and we could even make a class level method which has the same behavior if you feel that it's useful.

**Comment by wconrad** [comment]
I do feel it would be useful.  Where would you like the class method to be?  I earlier proposed allowing `MyModel.paper_trail.disable` to take an optional block.  Do you prefer a different signature?

**Comment by batter** [comment]
I feel like it would be good to stay consistent with the 'without_versioning' method name. Perhaps the disable method can be modified so if it receives a block it passes it over to the without_versioning class method.

I will say that if the 'disable' method can receive a block then it raises the question as to whether the 'enable' method should be able to receive a block with the inverse behavior, right?

**Comment by jaredbeck** [comment]
> I feel like it would be good to stay consistent with the 'without_versioning' method name.

I agree. That method name will be familiar to people.

> I will say that if the 'disable' method can receive a block then it raises the question as to whether the 'enable' method should be able to receive a block with the inverse behavior, right?

I think, for that reason, that neither `enable` nor `disable` should accept blocks. Let's keep them simple, if we can.

In general, I think there are already too many ways to switch PT on and off!  See docs [section 2.d.](https://github.com/airblade/paper_trail#2d-turning-papertrail-off).

**Comment by wconrad** [comment]
There are two conflicting requirements being expressed here.  One is that the method used at the class level be the same name, `without_versioning`, as that used at the instance level.  The other is that the number of ways to disable PT does not grow.  I'm not sure where to go now.  If I knew what you wanted the API to end up looking like, I could offer an incremental step that moves PT in that direction.

If it were me, here's where I'd take PT's API for enable/disabling:

* At the instance level:

  * Get rid of `without_versioning` because of its surprising behavior (that it, it does not disable versioning for the instance alone, but instead for the model).  

* At the model level:

  * Keep the name `disable` because it means the same thing as `without_versioning` but is more succinct.

  * Add block semantics to `disable`.

  * Possibly add block semantics to `enable`.  I can see the use case for it, and it makes sense; the only reason I hesitate is because nobody's asked for it; so I'm thinking of YAGNI.

Whatever is done to move in this direction (or any other), I imagine it should be done gently--for example, a method that is removed or renamed gets deprecated such that the old usage continues to work until the appropriate time for releasing a breaking API change.

**Comment by darkhelmet** [comment]
I thought I'm comment in here as my problem feels very much related to this discussion.

I just want this for an API:

```ruby
PaperTrail.disable do
  # nothing is versioned, in this block of code only
end
```

I want to disable all versioning for everything in a block of code, but not have it affect anything outside the block, or any other threads, etc. My use case is doing imports with Sidekiq. There's a bunch of stuff we don't need to version, and it's just extra load on the database and ruby code to handle it, but the only way to disable things seem to be across the world in some way (the model, but across all threads). This doesn't work in a threaded environment like Sidekiq where I would be messing with other jobs that perhaps I DO I want to make versions.

**Comment by jaredbeck** [comment]
Wayne, I like most of your proposed API. In particular, I agree that `without_versioning` has surprising behavior. Can you clarify what you mean by "block semantics"? I may have misunderstood before. I thought you meant the return value of the block would determine whether disabling occurred, but now I'm not sure that's what you meant. Did you mean, rather, that disabling would last for the duration of the block? I'd be interested in the latter, but probably not the former.

Daniel, you're right that `PaperTrail.enabled` is per-process. This was a deliberate decision, please see https://github.com/airblade/paper_trail/issues/635, which led to  https://github.com/airblade/paper_trail/pull/723. Have you tried `MyModel.paper_trail.disable`, which is thread-local and backed by [request_store][1]?. That might be awkward though, depending on how many models you want to disable. I'm open to suggestions for a new per-thread API, but given that `PaperTrail.enabled` is per-process, I think the name `PaperTrail.disable` would be misleading (too similar).

[1]: https://github.com/steveklabnik/request_store

**Comment by wconrad** [comment]
> Did you mean, rather, that disabling would last for the duration of the block?

Yes

I didn't know that some of the on/off methods were all-threads, and others were just the current thread.  It would be nice if the API that makes the all-threads/just-this-thread semantics more obvious..

**Comment by vtt** [comment]
I second darkhelmet's suggestion.

PaperTrail.without_versioning do
  # nothing is versioned, in this block only
end

The above API is the only one required for any disabling block usage; the instance "without_versioning" or model "without_versioning" will no longer be needed and can be removed.

**Comment by jaredbeck** [comment]
Anyone working on this? Sounds like we have a plan, just need someone to implement it.

**Comment by wconrad** [comment]
I am not working on this.  I'm on another project now and busier than a one armed paper hanger.

**Comment by westonganger** [comment]
I think I may take a stab at this tomorrow.

**Comment by jaredbeck** [comment]
Anyone planning on suggesting new API for enabling/disabling PT, [please be aware of the new API that will be released in 9.0.0 for request variables](https://github.com/airblade/paper_trail/pull/1033). Here are some upcoming deprecation warnings:

> PaperTrail.enabled_for_controller= is deprecated, 
> use PaperTrail.request.enabled_for_controller=

> MyModel.paper_trail.disable is deprecated, use
> PaperTrail.request.disable_model(MyModel). 

This new API makes it clear that only the current request is affected, not all threads. Also, all other request-variables now go through the same `request` method, so this new API is more consistent.

Given the recent changes, this conversation is a bit stale (though still a good read; thanks to everyone who participated!), so if you have a proposal (that you're willing to implement from start to finish) please open a new issue.

**Comment by westonganger** [comment]
What about these arguments?

@wconrad  

> At the instance level, get rid of without_versioning because of its surprising behavior (that it, it does not disable versioning for the instance alone, but instead for the model).

To which @vtt replied:

Using this example API:

```ruby
PaperTrail.without_versioning do
  # nothing is versioned, in this block only
end
```

> The instance "without_versioning" or model "without_versioning" will no longer be needed and can be removed.


Doesnt this still hold true in v9.0.0?

**Comment by jaredbeck** [comment]
Here is the current implementation of `RecordTrail#without_versioning`, as of 87f097c05fa13194b523f6ceac22cd02e49951fe

```ruby
    # Executes the given method or block without creating a new version.
    def without_versioning(method = nil)
      paper_trail_was_enabled = PaperTrail.request.enabled_for_model?(@record.class)
      PaperTrail.request.disable_model(@record.class)
      if method
        if respond_to?(method)
          public_send(method)
        else
          @record.send(method)
        end
      else
        yield @record
      end
    ensure
      PaperTrail.request.enable_model(@record.class) if paper_trail_was_enabled
    end
```

You can see it uses `PaperTrail.request.disable_model` under the hood. However, as I write this `RecordTrail#without_versioning` has not been deprecated, because there is no convenient alternative yet.

Does that give you something to go on, Weston?

**Comment by westonganger** [comment]
Yes. Just was wondering if you were still open to the implementation of the stated idea, which it appears you are. I'll follow up with a PR once I have something.

**Comment by jaredbeck** [comment]
I just merged https://github.com/airblade/paper_trail/pull/1069 which finalizes some of the API for this. So, in PaperTrail 9 you will be able to do:

```ruby
PaperTrail.request(enabled: false) do
  # tamper with elections
end
```

This should satisfy most needs. In the rare case that someone needs to disable versioning for one model while keeping versioning enabled for other models, use:

```ruby
PaperTrail.request.disable_model(Banana)
# ...
PaperTrail.request.enable_model(Banana)
```

For this rare use case, there is no convenient way to pass a block.

The old API will continue to work in PT 9, but will produce voluminous deprecation warnings :)
