### ISSUE TITLE
Zip improvement

### ISSUE THREAD

**Issue by ryanfox1985** [airblade/paper_trail#923]
Hello,

to put you in context, I'm using `paper_trail` in my project and the model that is versioned has many fields and many records. I never perform a search in the table `versions`, so what do you think if `paper_trail` has an option to compress (zip) the field `object`?

Now versions.object field stores a YAML of raw object.

In this [example](http://stackoverflow.com/questions/11059429/zip-a-string-in-memory-ruby#answer-11059704) shows an string zip saving ~15% of space.

Regards.

**Comment by jaredbeck** [comment]
Hi Guillermo. Thanks for the interesting idea.

The best way to save disk space is using [version_limit][1]. You might also save space (and get faster queries) by using [jsonb][2].

If you still want to use zip compression, you can write a [custom serializer][3]. If you do, I encourage you to publish it as a gem and we'll be happy to list it in our readme. The correct name for such a gem would be `paper_trail-my_serializer`. Please note the dash.

[1]: https://github.com/airblade/paper_trail#2e-limiting-the-number-of-versions-created
[2]: https://github.com/airblade/paper_trail#postgresql-json-column-type-support
[3]: https://github.com/airblade/paper_trail#6b-custom-serializer
