### ISSUE TITLE
destroy event created even after before_destroy callback stop destroy process 

### ISSUE THREAD

**Issue by loicginoux** [airblade/paper_trail#931]
Hi,
I have a got a model like this 

```
class Article < ActiveRecord::Base
  
  before_destroy :validate_not_published

  def validate_not_published
    if self.published?
      self.errors[:base] << "errors.cannot_delete_published_article"
      return false
    end
    true
  end
end
```

And when the callback prevents the article to be destroyed, paper_trail still creates the versions with the even `destroy`. Is this as intended or is this a bug? I would expect to not have a new version created.

If this can speeds things up, here are the test I would expect to validate

```
context "when before_destroy prevents form destroying" do
  setup do
    @article.new(title: "test", published: true)
    @article.destroy
  end
  should "not create a new version" do
    assert_not_equal @alerticle.versions.last.event, :destroy
  end
end
```

Using:

```
ruby "2.3.1"
gem 'rails', '~> 5.0', '>= 5.0.0.1'
paper_trail (5.2.2)
```

**Comment by jaredbeck** [comment]
In rails 5, aren't you supposed to `throw :abort` instead of `return`ing false?

**Comment by loicginoux** [comment]
You are right, although my `return false` still works, but even replacing it by `throw :abort`, I have the same behaviour.

**Comment by jaredbeck** [comment]
Hi Loic, can you please try to reproduce the issue using our [bug report template][1]? Thanks.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by loicginoux** [comment]
Thank you I was looking to something similar in the readme. I actually forked the project and started adding a failing test but didn't manage to set up the DB. I'll try that.

**Comment by jaredbeck** [comment]
Oh good, I'm glad I mentioned it then :) the template makes setup sooo much easier.

**Comment by loicginoux** [comment]
OK thanks, This is not related to paper_trail directly but when using in the model both paper_trail and the gem paranoia (for soft deletion, I know it's redundant with paper_trail features...). 
The test was failing when adding paranoia and passing with just paper_trail in the model. I'll close the ticket. 
Thanks for your time and your bug report template.

**Comment by jeffcarbs** [comment]
@loicginoux - did you ever figure out how to get this working while using both `paranoia` and `paper_trail`?

Personally, I prefer using `paranoia` for soft-deletion so that you can still join on and interact with associated records that have been archived. You can technically restore soft-deleted data using `paper_trail` but if you want to work with the data without restoring it it's more cumbersome.

**Comment by loicginoux** [comment]
@jeffcarbs Sorry I can't remember the solution I implemented and can't find it in the code...
