### ISSUE TITLE
Possibility to initialize versions to perform bulk insert with activerecord-import gem

### ISSUE THREAD

**Issue by pilgunboris** [airblade/paper_trail#937]
Hello. I [tried to ask this question on stackoverflow.com](http://stackoverflow.com/questions/42846026/how-to-initialize-papertrail-versions-to-perform-bulk-insert-using-activerecord), but there were no response, so I'm not sure if anyone can help me there.

**Context:**
I'm using [activerecord-import gem](https://github.com/zdennis/activerecord-import) to import multiple ActiveRecord documents in single query. Then I'm initializing related associations using saved documents ids and importing them too, and so on.

However, I need to have PaperTrail gem versions with `create` event for all saved documents.
Is there some straightforward way to initialize them to make possible perform bulk insert then?

**Comment by jaredbeck** [comment]
Hi Boris. I'm sorry we don't have enough volunteers to answer usage questions here. As our [contributing guide][1] says, we only accept feature requests and bug reports on github.

[1]: https://github.com/airblade/paper_trail/blob/master/.github/CONTRIBUTING.md

**Comment by pilgunboris** [comment]
@jaredbeck ok, no problem. Maybe, I put it wrong but I thought it can be considered as a feature request, because I wasn't able to find anything related to requested functionality in your user guide, so I think it is not usage question.

**Comment by jaredbeck** [comment]
Please feel free to open a new issue that restates your problem as a feature request. It should clearly state exactly what PT should do differently and why. Thanks!

**Comment by MohdAnas** [comment]
@pilgunboris Did you find any fix for the above problem? I saw your patch as well it didn't work for me. Can you please help?
Thanks

**Comment by pilgunboris** [comment]
> @pilgunboris Did you find any fix for the above problem? I saw your patch on stack as well it didn't work for me. Can you please help?
> Thanks

hey @MohdAnas sorry for the late response, I've just noticed your comment here. I've updated my solution for a newer version on StackOverflow. Did it help you?

**Comment by NemyaNation** [comment]
@pilgunboris @jaredbeck Any updates to this?

It's a much needed feature!

**Comment by pilgunboris** [comment]
@jaredbeck it would be really helpful to make these methods public or to make some public methods to call them: https://github.com/paper-trail-gem/paper_trail/blob/ee1b0002ea8c427947181d0be7ab0f6b1186d8ea/lib/paper_trail/record_trail.rb#L254-L281

As you can see this is a popular request.

**Comment by pilgunboris** [comment]
@NemyaNation I think for now you can try something like 
```Ruby
resource.paper_trail.send(:build_version_on_create, in_after_callback: false)
```
and similar for `build_version_on_update` just with corresponding arguments.

**Comment by NemyaNation** [comment]
@pilgunboris How would this work with the patch you have on stackoverflow, or in a active-record import scenario.
