### ISSUE TITLE
Rails 5.1 migration incompatibility

### ISSUE THREAD

**Issue by travisp** [airblade/paper_trail#949]
In the Rails 5.1 rc1, the migrations created by PaperTrail 7.0.0 do not work and cause this error:

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for
```

The migration has to be updated from 
```
class CreateVersions < ActiveRecord::Migration
```
to something like:
```
 class CreateVersions < ActiveRecord::Migration[4.2]
```

It appears that this is still the case in the master branch of PaperTrail

**Comment by jaredbeck** [comment]
Thanks Travis, that makes sense. How can we change our "migration template" (/Users/jared/git/paper_trail/lib/generators/paper_trail/templates/create_versions.rb) to output the user's rails version?

**Comment by jaredbeck** [comment]
It looks like devise uses erb to accomplish this. 

https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/templates/migration.rb

I don't know if that's an option for us, but it's one thing we could look into.

**Comment by jaredbeck** [comment]
Closed by https://github.com/airblade/paper_trail/pull/950. Will release in 7.0.1. Thanks Travis.

**Comment by dfherr** [comment]
i was actually running 7.0.2. At least this is what my gemfile lock says:

```
  paper_trail (7.0.2)
    activerecord (>= 4.0, < 5.2)
    request_store (~> 1.1)
```
