### ISSUE TITLE
Paper Trail gem with Globalize gem not working

### ISSUE THREAD

**Issue by sidcool1234** [airblade/paper_trail#953]
We are using Rails 3.2.15 and Globalize gem for I18N. We recently integrated Paper Trail Gem for auditing Model changes.

We observed that whichever model fields are marked as translated are not updated in DB.

e.g.

```
class MyModel < ActiveRecord::Base
  translates :name
  has_paper_trail
end
```
When I update the name attribute of MyModel object, it is not saved.

e.g.

> $ m = MyModel.last
> $ m.name = 'different name'
> $ m.save!

The above does not throw any error, but the value is not updated. 

Versions:

Ruby 1.9.3

Rails 3.2.15

Globalize3

paper_trail 2.7.2

**Comment by jaredbeck** [comment]
Hi Siddharth. I'm sorry, but we're not accepting bug reports for paper_trail 2 anymore. The current version of PT is 7.0.1. The latest version of PT that supports rails 3.2 is PT 5. If you can still reproduce the issue using at least PT 5, please open a new bug report, and use our [bug report template][1]. Thanks!

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
