### ISSUE TITLE
Whodunnit with block seems liken not available

### ISSUE THREAD

**Issue by sveredyuk** [airblade/paper_trail#955]
Get this code from readme, but seems like method not accept a block
```ruby
PaperTrail.whodunnit("Dorian Marié") do
  widget.update_attributes :name => 'Wibble'
end
```

#=> ArgumentError: wrong number of arguments (given 1, expected 0)
#=> .rvm/gems/ruby-2.3.0/gems/paper_trail-7.0.1/lib/paper_trail.rb:92:in `whodunnit'

**Comment by jaredbeck** [comment]
Hi Volodya, you are reading the docs for the `master` branch. At the top of the readme, you will find a link for the 7.0.1 docs.
