### ISSUE TITLE
Not compatible with rails 5.1

### ISSUE THREAD

**Issue by asnad** [airblade/paper_trail#960]
As before_filter has been depricated in in rails 5.1 so papertrail is not working with rails 5.1 I needed to change in paper_trail-4.0.0/lib/paper_trail/frameworks/rails/controller.rb and replace before_filter with before_action is there any version update or do I need to create a fork for this.

**Comment by asnad** [comment]
I was able to get it fix by adding this line in my gemfile
gem 'paper_trail', git: 'https://github.com/airblade/paper_trail.git', branch: '5-stable'

**Comment by jaredbeck** [comment]
> [PT 4.0.0 is] not compatible with rails 5.1

Correct. Compatibility with rails 5.1 was added in PT 6. Please see our [compatibility table][1].

> I was able to get it fix by [using] `branch: '5-stable'`

I'm glad you found a solution, but I don't recommend using a branch. Please use an official release instead. The latest release is 7.0.2.

[1]: https://github.com/airblade/paper_trail#1a-compatibility

**Comment by asnad** [comment]
yes agree
