### ISSUE TITLE
Memory bloat issue caused by using paper_trail within an ActiveRecord transaction

### ISSUE THREAD

**Issue by denisahearn** [airblade/paper_trail#962]
Hi,

We are experiencing an issue with memory bloat within an ActiveRecord transaction that is resulting from the after_commit and after_rollback callbacks that paper_trail registers when you define has_paper_trail for an ActiveRecord class.  We are using version 7.0.2 of paper_trail.

The specifics of the memory bloat issue are described in this Rails issue thread: https://github.com/rails/rails/issues/15549

In a nutshell, we have a Ruby process that is opening an ActiveRecord transaction, and then instantiating models of ActiveRecord classes which use paper_trail.  This process has the potential of instantiating hundreds of thousands of models within the transaction.  The lifetime of these objects within the scope of our code is very limited (we don't hold onto references of these objects), however these objects are not getting released by garbage collection because ActiveRecord is holding onto these objects, which is due to paper_trail's use of after_commit and after_rollback callbacks.

The suggested workaround in that issue thread is to not use after_commit and after_rollback callbacks, or not use a transaction.  We need both (a transaction and paper_trail), so I'm wondering if a potential workaround might be for paper_trail to provide a means to unregister those callbacks before the transaction, and then re-register those callbacks after the transaction, and also provide for my code to do the things those callbacks normally do, once my code knows that the transaction was either committed or was rolled back?

The standard behavior of paper_trail automatically handling commit/rollback is fine most of the time for us, but not in the case of this process, which has the potential to instantiate a lot of model instances.  I basically want to shut off this automatic commit/rollback handling during the transaction, and then turn it back on afterwards.

I'm also open to other suggestions if there is a better solution to this problem.

Thanks,
Denis

**Comment by jaredbeck** [comment]
Hi Denis, can you break up your "hundreds of thousands" into batches? If you can do a few dozen medium-sized transactions instead of one massive one, that would be better. If not, you may have to [disable PT][1] temporarily.

Are you using the experimental associations tracking feature? (`PaperTrail.config.track_associations`)

[1]: https://github.com/airblade/paper_trail#2d-turning-papertrail-off

**Comment by denisahearn** [comment]
Hi Jared,

Unfortunately we currently can't commit batches of updates to the database.  The current design of our process requires that everything succeed or fail as one atomic unit.

I am not sure if [temporarily disabling Papertrail](https://github.com/airblade/paper_trail#2d-turning-papertrail-off) as you have suggested will work either.  The reason that ActiveRecord is unable to release the model instances within the transaction is due to the presence of the after_commit and after_rollback callbacks that are registered by the `has_paper_trail` method.

No, we are not using the associations tracking feature.  We explicitly set `PaperTrail.config.track_associations = false` in an initializer to turn off this feature.

Denis

**Comment by jaredbeck** [comment]
Hi Denis, Do you want to do some research into whether ActiveRecord callbacks can be temporarily disabled? Or, what do you think our next step should be. Thanks, -J

**Comment by denisahearn** [comment]
Hi Jared,

Yes, I think it makes sense for me to do some research, and then let you know if I can come up with something that works for my use case, and then we'll take it from there.  

Thanks for replying.

Best Regards,
Denis

**Comment by denisahearn** [comment]
Hi Jared,

I ended up solving my issue by using the code contained in this gist: https://gist.github.com/denisahearn/f12ae66ac70b3f8651a9239302e81566

This solution works for my use case, but may not work in cases where there are commit or rollback callbacks other than the ones registered by paper trail.

Sorry that this code isn't in the form of a pull request for paper trail.  I'm not sure how to generalize this code to handle use cases other than my mine, but I'm hoping perhaps that it might spark some innovation on your side.  I'm fine too if we just leave my solution as a gist for others to use if they run into the same problem I did.

Best Regards,
Denis

**Comment by jaredbeck** [comment]
Hi Denis, 

Glad to hear you found a workaround. I like your design of wrapping the transaction in a class. My biggest concern, at first glance, would be your use of `_commit_callbacks` and `_rollback_callbacks`, which I assume (based on the underscore) are not public API. As such, using those methods would make PT harder to maintain. 

Still, I think there are a few people out there who might run into the same situation as you (hundreds of thousands of model objects in one transaction) and I'd love it if you could write a new section in our readme about what worked for you. You could put your code (from the gist) in doc/examples (I think it's a bit long to put in the readme).

Thanks!
