### ISSUE TITLE
avoid unnecessary AR queries

### ISSUE THREAD

**Issue by dfherr** [airblade/paper_trail#972]
This is a feature or performance improvement request. I'm not sure if it's doable or I'm understanding something wrong, but it has definitely a huge performance impact for me.

When updating a model, which I have "has_paper_trail" activated for it, paper_trail sends a find request for that model even though the data is already in memory. I would like to avoid this additional request as it severly influences performance. (I run mass updates on many rows and therefor prefetch all of them to memory)

Here is a rails debug output that might illustrate the issue:

```
D, [2017-06-02T11:23:25.080397 #52] DEBUG -- :   SQL (0.7ms)  UPDATE "translations_de" SET "msgstr0" = $1, "translator_comments" = $2, "po_file_id" = $3, "updated_at" = $4 WHERE "translations_de"."id" = $5  [["msgstr0", "The Comment text is too long!"], ["translator_comments", "change 14\nexcelrow: 875"], ["po_file_id", 4], ["updated_at", "2017-06-02 11:23:25.078881"], ["id", 1787]]
D, [2017-06-02T11:23:25.084124 #52] DEBUG -- :   Translation::De Load (0.4ms)  SELECT  "translations_de".* FROM "translations_de" WHERE "translations_de"."id" = $1 LIMIT $2  [["id", 1787], ["LIMIT", 1]]
D, [2017-06-02T11:23:25.085500 #52] DEBUG -- :   SQL (0.4ms)  INSERT INTO "versions" ("item_type", "item_id", "event", "object", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["item_type", "Translation::De"], ["item_id", 1787], ["event", "update"], ["object", "---\nmessage_id: 1787\nmsgstr0: The Comment text is too long.\nmsgstr1: \nis_plural: false\nflag: ''\nfuzzy_msgctxt: \nfuzzy_msgid: \nfuzzy_msgid_plural: \ntranslator_comments: 'excelrow: 875'\nid: 1787\npo_file_id: 3\ncreated_at: 2017-06-02 11:23:19.319014000 Z\nupdated_at: 2017-06-02 11:23:19.319014000 Z\n"], ["created_at", "2017-06-02 11:23:25.078881"]]
```

The second line (Select ...) should be avoidable.

I would be willing to make up a pull request, but I need some information where this problem might even come from in paper_trail.

**Comment by jaredbeck** [comment]
> I would be willing to make up a pull request, but I need some information where this problem might even come from in paper_trail.

Thanks Dennis, go for it. I think you will find our [bug report template][1] useful for isolating this. The [rails-callback_log][2] gem may also help, as PT uses a lot of callbacks.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
[2]: https://github.com/jaredbeck/rails-callback_log

**Comment by jaredbeck** [comment]
Are you still working on this Dennis?

**Comment by dfherr** [comment]
No. The effort isn't really worth the outcome, even in my use case.

**Comment by jaredbeck** [comment]
No worries, if you feel like working on it in the future, we can re-open it.
